### ISSUE TITLE
EPub realizes the interaction between front end and back end?

### ISSUE THREAD

**Issue by TJX666666** [futurepress/epub.js#1001]
I mean, add a tag to a page, how to retrieve the data and store it in the background, and then retrieve it and display it in the ePub

**Comment by johnfactotum** [comment]
Do you mean something like https://github.com/futurepress/epub.js/issues/970?

**Comment by TJX666666** [comment]
> Do you mean something like #970?

Yes, save to the modified tags, and the modification results will be displayed the next time these tags are loaded

**Comment by TJX666666** [comment]
> Do you mean something like #970?

bro,Can I manually underline the P tag by operating the DOM node and finally save it to the revision object? If it is not the revision object, where is the modified information saved?
thanks for u concern and reply

**Comment by johnfactotum** [comment]
Whether you underline by `rendition.annotations.underline()` or manually operating on the DOM, the easiest way is to just save the CFI string. You can save it in localStorage, or on the server--however you like it. Then next time when you present the book, you can use the CFI string to underline the same text again. (You can obtain a DOM Range from a CFI string by calling `book.getRange(cfiStringHere)`.)

**Comment by TJX666666** [comment]
> Whether you underline by `rendition.annotations.underline()` or manually operating on the DOM, the easiest way is to just save the CFI string. You can save it in localStorage, or on the server--however you like it. Then next time when you present the book, you can use the CFI string to underline the same text again. (You can obtain a DOM Range from a CFI string by calling `book.getRange(cfiStringHere)`.)

bro,have a problem:
   this.book
              .getRange(
                "epubcfi(/6/10[id1486]!/4[2RHM0-0aebd42b3dd94fc6899a00062929f083]/14,/1:40,/1:72)"
              )
              .then(res => {
                res.startContainer.parentNode.style.textDecoration = "underline";
                console.log(res.startContainer.parentNode); //<p class="bodycontent-text" style="text- 
                                                                                                decoration: underline;"> print sth</p>
              });
          }

The output DOM node attribute has been underlined, but the actual text effect has not been added;
Is it incorrect that I call cfirange to underline DOM?
thank you for u concern and answer ~
