### ISSUE TITLE
Why is it wrong to underline? 

### ISSUE THREAD

**Issue by TJX666666** [futurepress/epub.js#1002]
this.rendition.on("selected", function(cfiRange, contents) {
        contents.underline(cfiRange)//Uncaught TypeError: contents.underline is not a function
  })

**Comment by johnfactotum** [comment]
You need `rendition.annotations.underline`, not `contents.underline`.

**Comment by TJX666666** [comment]
> You need `rendition.annotations.underline`, not `contents.underline`.

bro ,i have a another question : 

rendition.annotations.mark(cfiRange, {'something' : true},(e) =>{
          console.log(e) //no print
 })

Why didn't the code react ? 
What should I do if I want to make a separate note of the selected text and save the node information of the tag to the server?
last problem: How to get the total number of pages and the current number of browsing pages

Thank you for your concern and answer !

**Comment by johnfactotum** [comment]
1. I'm not quite sure what `annotation.mark` does, actually; it doesn't seem to add any visible element to the page.
2. Not sure that I understand your question, but you can easily manipulate the selected or annotated text by using `contents.window.getSelection()` to get a [Selection](https://developer.mozilla.org/en-US/docs/Web/API/Selection) object, or use `book.getRange(cfiRange)` to get a [Range](https://developer.mozilla.org/en-US/docs/Web/API/range) object. You can then call `toString()` on those objects to get the selected text, or do any number of DOM manipulations you need to perform.
3. See https://github.com/futurepress/epub.js/issues/744
