### ISSUE TITLE
Question on Phonegap Issue

### ISSUE THREAD

**Issue by hsdk123** [futurepress/epub.js#101]
I've just been going through Google Groups and noticed a thread last November on how the iframe implementation prevents phonegap usage. Is this still an issue, or is automatic iframe construction no longer done?

https://groups.google.com/forum/#!topic/epubjs/hrgxfebdUGQ

**Comment by JakeHartnell** [comment]
With so many people wanting to use this library with Phonegap (some with success), it would be really nice if people could contribute a guide in the form a quality blog post or section in our wiki.
