### ISSUE TITLE
Prev not showing the correct page at certain viewport sizes

### ISSUE THREAD

**Issue by edsilv** [futurepress/epub.js#1013]
I'm working on a StencilJS Web Component here using epubjs: 

https://github.com/UniversalViewer/uv-ebook-components/tree/master/src/components/uv-ebook-reader

Everything generally seems to be working, except we're seeing a strange issue for the "Advice from a Caterpillar" chapter of this ebook: https://s3.amazonaws.com/epubjs/books/alice/OPS/package.opf

I've made a short video to demonstrate. First I'm using https://github.com/futurepress/epubjs-reader, which doesn't seem to ever exhibit the problem. Then I use the StencilJS web component, which skips a page on clicking prev, but only at certain resolutions. We need the reader to be in a Web Component to integrate it with another app, and can't use epubjs-reader because it uses the entire page.

https://youtu.be/NQtw9niY7qM

Logging out the layout data seems to show no difference between the two when the viewport is exactly the same size. Could it be css related? I've run out of ideas, so any help you could offer is most welcome!

**Comment by edsilv** [comment]
I was using a custom theme:

```
this._rendition.themes.register("custom", {
  "*": {
    "font-family": "'Stix', serif !important",
    "font-variant-numeric": "oldstyle-nums !important"
  }
});
```

Removing this fixed it.

**Comment by elliotdickison** [comment]
This issue still occurs when you have a custom theme. Removing the theme was not an option for me, so I hacked around this issue by imperatively scrolling to the end of the epub container after moving to the previous chapter:

```
const container = document.querySelector(".epub-container")
container.scrollLeft = container.scrollWidth
```
