### ISSUE TITLE
Jump to next or previous chapter on top amd bottom arrow keys.

### ISSUE THREAD

**Issue by bharat-savior** [futurepress/epub.js#1020]
Hello Everyone, 
I have just started using following epub.js library its working as a charm. 
It fulfilled most of my requirements. But I am stuck at one requirement which is jumping on next or previous chapters on click of top arrow and bottom arrow keys. 

Can anyone help me out how I can implement that. 

I am using normal JavaScript version which I got form following repo: https://github.com/futurepress/epubjs-reader/tree/master/reader

Thank you

**Comment by HBArck** [comment]
@bharat-savior use vanila js to intercept those events and in success callback trigger click on arrows

**Comment by bharat-savior** [comment]
@HBArck Thank you for suggesting. I will definitely work on this.
