### ISSUE TITLE
rendition.annotations.remove(cfi) does not remove the highlight

### ISSUE THREAD

**Issue by OpenSesyme** [futurepress/epub.js#1038]
I Am adding highlight to a searched text using the following piece of code:
          rendition.annotations.add("highlight", cfi, {}, (e) => {console.log("highlight clicked", e.target);} , "hl", {"fill": "blue", "fill-opacity": "0.3", "mix-blend-mode": "multiply"});
   which adds the highlight perfectly fine, 

and I try to remove the highlight using the following code
rendition.annotations.remove(CFI)
 but it does not remove the highlight.

I have tried to log annotations and my CFI to make sure that the CFI I am providing exists in annotations and it does but still, highlight does not get removed.

I highly appreciate any help

**Comment by OpenSesyme** [comment]
This issue is with the minified version, when I replaced the minified version with the normal from the highlights example it works fine now... DO NOT FORGET TO UNCOMMENT LINE 10500 AND COMMENT LINE 10501 AND THEN REPLACE this FROM LINE 10500 WITH _this_8 FOR COVERURL TO WORK.

**Comment by sengemann** [comment]
@OpenSesyme - Good Find. You should still make a Pull Request with this so that it makes its way into the distributed version for everyone.

**Comment by csantanu** [comment]
> This issue is with the minified version, when I replaced the minified version with the normal from the highlights example it works fine now... DO NOT FORGET TO UNCOMMENT LINE 10500 AND COMMENT LINE 10501 AND THEN REPLACE this FROM LINE 10500 WITH _this_8 FOR COVERURL TO WORK.

This is still a problem in the new release. It seems the fix did not get pulled into the released version.
