### ISSUE TITLE
rendition.themes.fontSize dont work on some epubs

### ISSUE THREAD

**Issue by superbem** [futurepress/epub.js#1039]
rendition.themes.fontSize(...) dont work on some epubs that have font-size style set inside the epub.
`rendition.themes.default({ "p": { "font-size": "normal"}});` is the same, it wont override if it is set inside.

I think is the same as this:
`<style>
	.c{font-size:10px;}
	p{font-size:30px;}
</style>

 <p class="c" >test</p>`

<script>
//the solution is to loop the array and set the fontSize on each class.
	var x = document.getElementsByTagName("p")[0]; 
	x.style.fontSize="30px";
	console.log(x.className);
</script>`

Could you implement this on epub.js fontSize method or so?
Or can you explain an help to implement this?

**Comment by superbem** [comment]
I'm using epub.js to render .epub books, but I cant set fonSize in some ebooks, it wont override existing classes with the font-size already set on the ebook;
I tried to set the fontsize with this but neither works in a epub that have font-size already set:
`rendition.themes.default({ "p": { "font-size": "normal"}});`

The solution is to loop each child class and reset to desired size. 
I dont know how to do this.

Can anyone point me to the right diretion?

**Comment by johnfactotum** [comment]
Try increasing [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) with`!important`.

**Comment by superbem** [comment]
> Try increasing [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) with`!important`.

Thanks I solved with:
`rendition.themes.default({ "p": { "font-size": "medium !important"}});`
