### ISSUE TITLE
How can i show subheading of toc and zoom or click event at any image ?

### ISSUE THREAD

**Issue by Ramkesh9** [futurepress/epub.js#1045]
Thank you for beautiful library, i used this and it help me a lot, but i am stuck at 2 points:

1.) can you let me know how can i show subheading in toc, (heading ( heading 1 ) are showing properly but sub heading are not (heading 2) ?

Like:
chapter 1
- heading 1
- heading 2

chapter 2 :
- heading 1
- heading 2
- heading 3

2.) how can i get tap event on any specific image (i just want to zoom any image at tap or directy zoom webview for images) ?

please assist me to figure it out.

**Comment by SamuelPremji** [comment]
> Thank you for beautiful library, i used this and it help me a lot, but i am stuck at 2 points:
> 
> 1.) can you let me know how can i show subheading in toc, (heading ( heading 1 ) are showing properly but sub heading are not (heading 2) ?
> 
> Like: chapter 1
> 
> * heading 1
> * heading 2
> 
> chapter 2 :
> 
> * heading 1
> * heading 2
> * heading 3
> 
> 2.) how can i get tap event on any specific image (i just want to zoom any image at tap or directy zoom webview for images) ?
> 
> please assist me to figure it out.

Did you figure it out?
