### ISSUE TITLE
RTL books in continuous mode are not paging after commit 915ab2e

### ISSUE THREAD

**Issue by alidbc** [futurepress/epub.js#1053]
After commit 915ab2e107f7d95d44a9fbc48b91409c6ac8c3e2 RTL books are not turning pages anymore

**Comment by fchasen** [comment]
Should be fixed in `epubjs@0.3.87`
If not, have you got a epub that is failing to turn pages that I could test with?

**Comment by looknear** [comment]
In general the #view need some RTL adjustments and other fixes, like reverse next and prev. But it is working fine.
Maybe Ali mean on double spread?

**Comment by alidbc** [comment]
I have to dig deeper as many merges happened almost at the same time 😆

**Comment by alidbc** [comment]
Here is my settings
{
      manager: "continuous",
      flow: "paginated",
      width: "100%",
      height: "100%"
}
to avoid the problem and have the same results i removed continuous manager and kept default

if you want to simulate it; modify an epub book spine attribute "page-progression-direction" to rtl and render it with the above settings

**Comment by alidbc** [comment]
it happens with books modified manually by me
