### ISSUE TITLE
How to set background color of the book while switching themes?

### ISSUE THREAD

**Issue by csantanu** [futurepress/epub.js#1060]
While switching from light to dark theme/mode, the text and background renders correctly but moving from one chapter to another, shows the book's default background color (white or transparent). This is problematic for dark mode as there are flashes of white between the chapters and very irritating to the eye. How to set the iframe's background color to the same color as the theme? Any help will be greatly appreciated.

**Comment by johnfactotum** [comment]
Setting the theme only changes the color of the page inside the iframe. To solve the flashing problem, you need to set the background of the parent div with the same color.

See the example CSS file:

https://github.com/futurepress/epub.js/blob/0e3104461df9c02f001e44972b7fede741e95ed5/examples/examples.css#L27-L37

It sets `ajax-loader.gif` as the background image of the `#viewer` div so it will show a loading spinner when moving from one chapter to another.

**Comment by csantanu** [comment]
Thanks for the suggestion. I am using epubjs in an ionic setup. So how to set the background color of the parent div in the runtime, when switching the themes say from light to dark ?

**Comment by csantanu** [comment]
This worked by changing the background color of the "book" div in the runtime, like this -

this.el = document.querySelector('#book');
switch(theme) {
case "black":
this.el.style.setProperty('background', "#000000");

Thanks for the pointers.
