### ISSUE TITLE
iFrame moving with page turn

### ISSUE THREAD

**Issue by csantanu** [futurepress/epub.js#1067]
I am using 0.3.73 in an ionic setup. For certain devices, like One Plus 6T, as the page turns forward, it starts shifting the iframe (left padding increases) progressively. The text starts cutting off at some stage and spills over to the next page. This stops, when there is a chapter transition and the iframe refreshes back to normal text setting. But it starts again in the same manner for this chapter. I am using this rendition method (apparently it is stopping another issue - page skipped from happening).
this.rendition = this.book.renderTo("book",{ flow: 'paginated', contained: true, height: '100%', width: '100%'}

**Comment by fchasen** [comment]
Thanks for the report, sounds like the container size might be changing while the views are loading.

I'm not very familiar with ionic but could you try setting size with `width: 100vw` and `height: 100vh`? Doubt it will make a difference but worth a try as that atleast is a stable size.

You might also want to try setting width and height to a known size like 200px by 300px and see if that stops the issues.

**Comment by csantanu** [comment]
Here's the book scss code snippet, where the container is setup. It's already 100% for both width and height. I cannot set it to a fixed area as it will not be adaptive.

 #touchlayer,
    #book {
        width: 100%;
        height: 100%;        
    }
    #book {
        z-index: 0;
        
    }
    #book iframe {
        border: none;
        background: #FFFFFF;
        position: absolute;
        min-width: 100%;
        min-height: 100%;
        z-index: 99;
        -webkit-user-select: auto;
        user-select: auto;
    }
    .scroll-content {
        overflow-y: hidden;
    }

**Comment by wuyu8512** [comment]
我有同样的问题，但是这个问题只在安卓Chrome上出现，火狐无法复现
I have the same problem, but this problem only appears on Android Chrome, Firefox cannot reproduce

**Comment by wuyu8512** [comment]
https://github.com/geek1011/ePubViewer

在这个项目里，我无法复现此问题，但我将epubjs升级之后，则出现问题，我检查了版本，依稀记得是3.6.1之后才出现的

In this project, I can't reproduce this problem, but after I upgraded epubjs, there was a problem, I checked the version, and vaguely remembered it only appeared after 3.6.1

**Comment by csantanu** [comment]
> https://github.com/geek1011/ePubViewer
> 
> 在这个项目里，我无法复现此问题，但我将epubjs升级之后，则出现问题，我检查了版本，依稀记得是0.3.61之后才出现的
> 
> In this project, I can't reproduce this problem, but after I upgraded epubjs, there was a problem, I checked the version, and vaguely remembered it only appeared after 0.3.61

Yes, you are right. It appeared in the late versions (I am using latest master branch). Also, it's not happening in every device even with the same resolution - we tested in Vivo Z1Pro and One Plus 6T (both same res 1024x2436), it's not happening in Vivo model ! In ionic chrome is used as the web view, so it seems a bit device specific but not sure which is impacting.

**Comment by csantanu** [comment]
> Thanks for the report, sounds like the container size might be changing while the views are loading.
> 
> I'm not very familiar with ionic but could you try setting size with `width: 100vw` and `height: 100vh`? Doubt it will make a difference but worth a try as that atleast is a stable size.
> 
> You might also want to try setting width and height to a known size like 200px by 300px and see if that stops the issues.

I tried setting with viewport width/height - to no avail. Initially I was using the 0.4 version for testing out, where this issue was not occurring. I had to move to more stable release, since 0.4 had other problems. But now this issue has resurfaced. Any clues / direction on how this can be fixed ? thanks in advance.

**Comment by csantanu** [comment]
> Thanks for the report, sounds like the container size might be changing while the views are loading.
> 
> I'm not very familiar with ionic but could you try setting size with `width: 100vw` and `height: 100vh`? Doubt it will make a difference but worth a try as that atleast is a stable size.
> 
> You might also want to try setting width and height to a known size like 200px by 300px and see if that stops the issues.

I have re-run the code with the beta 0.4 package and the problem disappeared for the set of devices that I had mentioned. We are using EPUBJS for a vernacular language project in India and currently this issue is creating disruption for many readers. It will be very helpful, if you can give a lead on which section I can compare/study between the 0.4 and 0.3.73 release version, to understand and fix this issue. Rendition API? I cannot use the 0.4 as is, since there are other bugs in the distribution package. Just need some cues :) Many thanks in advance.

**Comment by rafaelsaback** [comment]
**TR;DR; in my case (running on mobile), this was happening whenever the container width was not divisible by 8. A workaround was to use the biggest number that is divisible by 8 and smaller than the screen width**

I've faced this bug when trying to use EpubJS on React Native. As suggested by @fchasen, I tried setting a fixed width to see how it behaved. Luckily enough I randomly chose `400px`. And it worked. Then I tried using my device's screen width, i.e. 411px. It didn't work. After debugging, I noticed that the bug happened whenever the container width was not divisible by 8.

The workaround I've come up with was to set the container width to be equal to the biggest number that is divisible by 8 and smaller than the screen width. For example, in my case my device had 411px of screen width, so I set the container width to 408px and it worked fine.

To calculate that, you can do it more or less like this:

```js
// This first line is React Native specific. Just find a way to get the screen width.
const screenWidth = Math.round(Dimensions.get('window').width);
const remainder = screenWidth % 8;
const containerWidth = screenWidth - remainder;
```

**Comment by csantanu** [comment]
@rafaelsaback fantastic find !! this worked like a charm. Strangely, the device which had the issue (oneplus6T) has a device resolution of 1024x2340 but the platform inner width yielded 412 px !! So, this computation solved the problem. Many thanks for Sharing. Closing the issue.

**Comment by rafaelsaback** [comment]
@csantanu I'm glad it worked for you as well 🙂

**Comment by desmondsmall** [comment]
Experienced this in 0.3.93. The following line caused the bug:

`rendition.themes.default({ "body": { "border": "1px solid black" } })`
