### ISSUE TITLE
Shown Highlighted area was not moved along with the text after the font size changed.

### ISSUE THREAD

**Issue by LDHo** [futurepress/epub.js#1081]
Hi, I am currently encountered the issues that after I set the fontSize to bigger or to smaller by calling function rendition.fontSize('200%'), the paragraph that I highlighted with background-color: yellow was not moving along with the fontSize changed characters. Is there any solution? Is the problem was due to that the epubCFI was not changes accordingly based on the fontSize? 
The code below is what I used for highlighting.
`  this.rendition.on('selected', (cfiRange, contents) => {
     if (this.enableHighlight) {
         this.rendition.annotations.highlight(cfiRange, {}, (e) => {
            console.log("highlight clicked", e.target);
         });
         contents.window.getSelection().removeAllRanges();
       }
})
`
and this is the code that I used to adjust the font size

`
 configureFontSize(action: FontSizeAction) {
    const convertNumberToPercent = (fontSize: number) => {
      return fontSize.toString() + '%';
    };
    if (action === FontSizeAction.ADD) {
      this.fontSize += 10;
      this.rendition.themes.fontSize(convertNumberToPercent(this.fontSize));
    }
    else if (action === FontSizeAction.MINUS) {
      this.fontSize -= 10;
      this.rendition.themes.fontSize(convertNumberToPercent(this.fontSize));
    }
    this.updateProgressBarValue(this.rendition.currentLocation());
  }
`
This was the screenshot that I have highlighted certain text before I change the font size.
![Screenshot from 2020-06-17 17-43-35](https://user-images.githubusercontent.com/30370361/84882784-56862f80-b0c2-11ea-91be-614dfa57a320.png)

This was the screenshot after I change the font size.
![Screenshot from 2020-06-17 17-44-14](https://user-images.githubusercontent.com/30370361/84882793-584ff300-b0c2-11ea-870f-0b505215dd90.png)

As shown in figure, the highlight area was not moving along with the selected text after the font size changed. Hope someone can help me with this. Thanks.

**Comment by johnfactotum** [comment]
When the font size changes, the highlights needs to be re-rendered, which can be done with something like:

```js
this.rendition.views().forEach(view => {
  if (view.pane) view.pane.render()
})
```

See https://github.com/johnfactotum/epubjs-tips#re-render-annotations

**Comment by LDHo** [comment]
@johnfactotum, it works perfectly. Thanks in advance.
