### ISSUE TITLE
New maintainer? New releases?

### ISSUE THREAD

**Issue by burtonator** [futurepress/epub.js#1082]
I'm curious does this project need a new maintainer?  There aren't any releases since Oct 2018... Almost 20 months.  There are bugs that we're running into and if there aren't going to be any releases coming out I'd have to fork and just work from that branch.  

Love epub.js otherwise!

**Comment by johnfactotum** [comment]
There have been many recent releases. They just aren't tagged or published as releases on GitHub. The versions are [being bumped](https://github.com/futurepress/epub.js/commit/26075c2d498a88843f97ca359c88f7261659db8c), and published on [npm](https://www.npmjs.com/package/epubjs):
![image](https://user-images.githubusercontent.com/50942278/85190646-c30f5300-b2a9-11ea-920f-b9508db64a39.png)

**Comment by fchasen** [comment]
Thanks, for the kind words!

Apologizes for the slow down, library is still actively maintained and developed. Will try to get PRs out faster.

We got a lot of great fixes for the RTL and vertical language support but I didn't review them quickly enough and they aren't all working together quite right at the moment. Should be fixed and released fairly soon.

The 0.4 branch is a bit stale now, but currently planning out rebasing it as it can better take advantage of some of the newer apis that weren't available before. (such as Service workers, Sandboxed iframes and resize observers!)

The speed of releases should be increasing (and will make sure to update the releases page...)

**Comment by alper** [comment]
What's the status of the library currently?

**Comment by aehlke** [comment]
npm releases stopped around a year ago
