### ISSUE TITLE
Navigation returns wrong href.

### ISSUE THREAD

**Issue by Losses** [futurepress/epub.js#1084]
When my book initialized, the `Book.loaded.navigation.toc.tocByHref` looks like this:
![image](https://user-images.githubusercontent.com/1384036/85203125-0ca97d80-b33e-11ea-8471-2ad9c95d2c51.png)
and the `Book.loaded.spine.spineByHref` looks like this:
![image](https://user-images.githubusercontent.com/1384036/85203262-15e71a00-b33f-11ea-83fd-314cebce4b6d.png)

They are not consistent.

This caused a problem: I can't get `Section` based on the `href` provided by `navigation.toc`, so I can't navigate based on toc, which is done in this example:
https://github.com/futurepress/epub.js/blob/master/examples/renderless.html

In the example above, it cached the `href` of the `toc` with:
![image](https://user-images.githubusercontent.com/1384036/85203182-8ccfe300-b33e-11ea-9420-4e38c9635931.png)
(https://github.com/futurepress/epub.js/blob/master/examples/renderless.html#L33)
While the option changed, it switch chapters with:
![image](https://user-images.githubusercontent.com/1384036/85203213-bee14500-b33e-11ea-9e52-8da04007c3f9.png)
https://github.com/futurepress/epub.js/blob/master/examples/renderless.html#L42
and
![image](https://user-images.githubusercontent.com/1384036/85203221-cbfe3400-b33e-11ea-81b7-cb551819c2e6.png)
https://github.com/futurepress/epub.js/blob/master/examples/renderless.html#L62

In my case, the link between toc and spine broke, I don't know if it's a bug, help wanted.

**Comment by johnfactotum** [comment]
I think this is https://github.com/futurepress/epub.js/issues/469.

The path in `spine` is relative to to the `.opf` file, but the paths in `toc` are relative to the nav/ncx file, hence the discrepancy.

To solve this, you need to resolve the relative paths in the TOC based on `book.packaging.navPath` or `book.packaging.ncxPath`. Something like this:
```js
const resolveURL = (url, relativeTo) => {
    // HACK-ish: abuse the URL API a little to resolve the path
    // the base needs to be a valid URL, or it will throw a TypeError,
    // so we just set a random base URI and remove it later
    const base = 'https://example.invalid/'
    return new URL(url, base + relativeTo).href.replace(base, '')
}

const basePath = book.packaging.navPath || book.packaging.ncxPath

const href = book.navigation.toc[0].href

// this will give you the path relative to the .opf file
const resolvedPath = resolveURL(href, basePath)

// this should work now
book.spine.get(resolvedPath)
```

**Comment by Losses** [comment]
@johnfactotum Wow, it works! Thanks for you help!
