### ISSUE TITLE
Can epub.js allow vertical scrolling ?

### ISSUE THREAD

**Issue by carbontracking** [futurepress/epub.js#109]
Hello, 

I appreciate that the question may go outside most e-readers that I've seen but I'm wondering if it is possible to have a page flow vertically with epub.js.

My wish is to create an epub file with one html file corresponding to a physical page in a paper book. I'm creating epub versions of textbooks for my son and I want him to follow the same page structure as his classmates on their paper version. Note that I'm setting the default font to 28px by default so text takes up alot of space.

Best regards / Colm

**Comment by JakeHartnell** [comment]
Closing as no discussion for awhile. We will be introducing a continuous scrolling example soon.
