### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by csantanu** [futurepress/epub.js#1097]
Is there a plan for a new release soon? The last release was about couple of years back.

**Comment by johnfactotum** [comment]
0.3.88 was released just a few days ago...? https://github.com/futurepress/epub.js/releases/tag/v0.3.88

**Comment by csantanu** [comment]
> 0.3.88 was released just a few days ago...? https://github.com/futurepress/epub.js/releases/tag/v0.3.88

My Bad. Didn't notice it. Closing this.
