### ISSUE TITLE
Problem setting font

### ISSUE THREAD

**Issue by bksubhuti** [futurepress/epub.js#1098]
We are using the epub side by side with another text and we are having trouble setting the font.  
We are using the following code according to the documentation.  We also tried with font-family which is not documented.

While some epubs we use have embedded font and css, I  deleted those fonts and to have no-css file in Sigil.  However, still it is not being set to the selected font passed in.  The font name is correct because it is being used in other parts of the program.

The project is located https://github.com/bksubhuti/Tipitaka-Pali-Projector
and need firefox and must set about:config for  file.uri.strict to be set to false to have local file reading possible.

 
```
  rendition.themes.default({
            p: {
                'font-size': `${PaliFontSize}pt`,
                'line-height': '150%', 
                'font': `${PaliFontName}`
            },
            body: {
            'padding-left': '20px !important',
            'padding-right': '20px !important'
            }
        });
```

**Comment by bksubhuti** [comment]
Can set the font if the font is embedded in the epub.  
Documentation is wrong.. It should be set by "font-family" and not "font"

**Comment by johnfactotum** [comment]
`font` is a shorthand property, and [unless it's set to a system keyword, it must include values for `font-size` and `font-family`](https://developer.mozilla.org/en-US/docs/Web/CSS/font#Syntax). So something like `font: serif;` is invalid in CSS. You can use something like `font: 12pt serif;`, which is valid, if you want.

>Documentation is wrong

What documentation is that?

**Comment by bksubhuti** [comment]
Yes.  that is good and it worked.
Another problem was the default Sigil file had a font css which was causing problems. (Now Deleted)

Your support is well appreciated.  
The other bug fix was verified as working .. last line getting cut off.

As for documentation..I request you add an example as you gave above.
![image](https://user-images.githubusercontent.com/18184280/87672422-f2c25580-c798-11ea-8060-f98406bcb56e.png)

**Comment by johnfactotum** [comment]
The documentation is talking about `rendition.themes.fontSize()` and `rendition.themes.font()`, not `rendition.themes.default()`.

**Comment by bksubhuti** [comment]
okay.. I understand. the code we used was "rendition.themess.default".  How do we do the "overrides" font size and font (-family)?
I searched through the example and did not find.
