### ISSUE TITLE
Error: JSZip lib not loaded

### ISSUE THREAD

**Issue by sanket5** [futurepress/epub.js#1099]
I m loading a book as 

 this.book = ePub(data); 
where data is an epub file..

i am getting an error as: 
ERROR Error: Uncaught (in promise): Error: JSZip lib not loaded
Error: JSZip lib not loaded
    at j.checkRequirements (epub.min.js:1)
    at new j (epub.min.js:1)
    at H.unarchive (epub.min.js:1)
    at H.openEpub (epub.min.js:1)
    at H.open (epub.min.js:1)
    at new H (epub.min.js:1)
    at l (epub.min.js:1)
    at EpubviewerComponent.renderBook (epubviewer.component.ts:112)

At 112 the book is loading...

I am using these scripts:
<script src="https://cdn.jsdelivr.net/npm/epubjs/dist/epub.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.5/jszip.min.js"></script>

**Comment by csantanu** [comment]
I am facing the same issue with the new release 0.3.88.

**Comment by fchasen** [comment]
Can you try loading the `jszip.min.js` script tag before `epub.js`?

**Comment by csantanu** [comment]
> Can you try loading the `jszip.min.js` script tag before `epub.js`?

Yes this worked for me. Thanks.

**Comment by sanket5** [comment]
Thanks It worked ...
