### ISSUE TITLE
Font size change cuts off last few pages access

### ISSUE THREAD

**Issue by csantanu** [futurepress/epub.js#1103]
In the new release, if you increase the font in the middle of reading, and then proceed, strangely the navigation gets stuck before the end of the book. The progress% show just under 100% and the page progression stops. Unless again the font size is reduced, the page refreshes back and shows the remaining bit. We are using ePUBJS in a Cordova (ionic) setup in Android app.

**Comment by alikazemkhanloo** [comment]
It also happens when changing the `font-family`. Some fonts takes more space to show, but the total page returned in 'relocated' event is not updated.

**Comment by christiaan** [comment]
I worked around this issue by calling the following right after changing the font.

```js
epub.manager.clear();
epub.display(lastLocation);
```
Where last location is the value that was last emitted by the `relocated` event.

**Comment by csantanu** [comment]
@christiaan I tried this method but after font change, this is taking me to the start of the book i.e the cover page.

**Comment by christiaan** [comment]
Are you sure you passed a proper lastLocation to the display() call? When you pass it null or undefined it goes to the first page of the book.

**Comment by csantanu** [comment]
@alikazemkhanloo I did a local build with this change and the problem has been fixed. Ran several tests and the fix works :-)
