### ISSUE TITLE
Getting HTML links to work in an ebook

### ISSUE THREAD

**Issue by Frimples** [futurepress/epub.js#111]
I have an online book site and have posted a couple of epub books based on the epub.js code:

http://drawingbooks.org/epubs/b_line/index.html
http://drawingbooks.org/epubs/b_plaster/index.html

I'm trying to get this book to work but the html links do nothing when I click on them:

http://drawingbooks.org/epubs/demo2/dev.html

The NOC TOC works, if I right click a link it will open properly, but it does nothing in the iframe.

Thanks for any help.

**Comment by JakeHartnell** [comment]
No discussion for a while, @fchasen / @Frimples has this been resolved?

**Comment by fchasen** [comment]
Need to make a test for this.

**Comment by JakeHartnell** [comment]
Closing this for now, feel free to reopen if there is still an issue in v0.3
