### ISSUE TITLE
Texts Cut in Vertically Right To Left Writing Mode

### ISSUE THREAD

**Issue by MrRogerHuang** [futurepress/epub.js#1119]
I am developing a PWA app for reading some HTML Chinese books by epub.js 0.3.88. I first convert a HTML to an epub and then feed it to epub.js.
(This is the source code if anyone is interested in it: https://github.com/MrMYHuang/cbetar2 and checkout ePubReadingView branch)
I try to show the Chinese books in their traditional text directions: writing from right to left and vertically
However, this screenshot shows epub.js cuts texts vertically at the browser left edges as showed in the red rectangle.
![image](https://user-images.githubusercontent.com/49478723/91692030-4814c380-eb9b-11ea-881b-65c48fcbe293.png)
If I turn the text directions to writing from left to right and horizontally, epub.js works well without text cuts.

I provide an example epub with CSS property, `writing-mode: vertical-rl`. Anyone can try to load it by epub.js with `book.renderTo('viewer', { width: "100%", height: "100%", defaultDirection: 'rtl'})`:
https://drive.google.com/open?id=1BCJFJww2B-4V7CHbJrL_YdFaFI4A4khx

Is this a epub.js bug?

**Comment by MrRogerHuang** [comment]
After using browser inspector to study the views generated by epub.js, I understand the magic of it to achieve HTML pagination for horizontal writing mode by CSS and JS: `column-fill: auto`, `overflow: hidden`, render content in an iframe. Then horizontally scroll a epubjs-container div...

Unfortunately, epub.js doesn't work well with `writing-mode: vertical-rl` or `writing-mode: vertical-lr`
It might cut texts at browser edges as shown in the screenshot in the previous post.

However, I saved the epub.js generated magic HTML and use browser inspector to tune CSS for vertical writing mode. After try and error, I achieve a magic prototype for HTML pagination for vertical writing mode by CSS (works on Chrome and Safari):
![image](https://user-images.githubusercontent.com/49478723/92090338-e4400400-ee01-11ea-9185-74a6fd90052e.png)
The source HTML can be download here:
https://drive.google.com/open?id=1sGJAGl2qF1bsAS1pjVbvCYrhX4Dqzndc
(Note, I use CSS `column-rule-style: solid; column-rule-width: 1px;` to show the pagination boundaries.)
My magic is the code in the HTML:
`writing-mode: vertical-rl; width: 644px; height: 71656px`
That is: turn on vertical writing mode. The long vertical texts are paginated vertically (page by page in vertical direction). Thus, in theory, we can use JS to switch between pages perfectly without text cut! I hope someone can implement this magic in epub.js, thanks. Otherwise, I could implement it (I feel stressed 😂) .

**Comment by MrMYHuang** [comment]
Sorry, after more debugging of my HTML to ePub to epub.js viewer program ( https://github.com/MrMYHuang/cbetar2  ), I find epub.js does work perfectly with vertical RTL writing ePub. The problem of text cuts comes from bad formatted ePub files. To make epub.js correctly working with vertical RTL, it shall set the writing-mode on html tag, e.g.:
```
html {
    writing-mode: vertical-rl;
}
```
and set option `defaultDirection: 'rtl'` to book.renderTo.

**Comment by mbret** [comment]
Do you see the same problem with gecko (firefox) or webkit (safari) ? There is known bug on blink (chrome) which can cut vertical text innapropriately.
