### ISSUE TITLE
How to set single column as min screen width

### ISSUE THREAD

**Issue by csantanu** [futurepress/epub.js#1132]
In tablets which have wider screens, the book renders in two columns by default. How to set a single column for all devices i.e mobile or tablets so that the text is displayed in the maximum width area.

**Comment by johnfactotum** [comment]
Set `spread` to `"none"` for the rendition.

```js
const rendition = book.renderTo('viewer', {
      width: '100%',
      spread: 'none'
});
```

Alternatively you can set `minSpreadWidth` to a higher value than the default (which is 800).

**Comment by csantanu** [comment]
Perfect. The spread parameter set to none works nicely for Tablets. Thanks a ton.
