### ISSUE TITLE
Pages transition style and duration 

### ISSUE THREAD

**Issue by EINBOX** [futurepress/epub.js#1147]
Hi, as a automation test engineer, I need to automate page transition style and speed of each animation duration.
Please let's know is there any to capture of animation style and animation speed when page moves left or right.

**Comment by EINBOX** [comment]
solved myself

**Comment by techinvein** [comment]
@EINBOX can you please mention the code you have used here? so that we can also try that. Thanks

**Comment by EINBOX** [comment]
Hey sorry, Its a wrk around using page transmission property... But some times it returns wrong speed.. Still thinking to fix

**Comment by jadayash** [comment]
any update on this @EINBOX ?
