### ISSUE TITLE
single page at a time without scrolling the content in epub.js (v.0.3)

### ISSUE THREAD

**Issue by Aryesh-M** [futurepress/epub.js#1154]
Hello,
I tried below code:  
```
let rendition = book.renderTo('textLayer', {
				height: 600,
				width: "100%",
				flow: "scrolled-doc"
			});
```
which is showing one section on one page with a scroll bar, I want to display page content without a scroll bar i.e., extra content on the next page irrespective of the section. [Here](https://epubjs.readthedocs.io/en/latest/examples/single.html) I found **single.html** file (the exact scenario I want) but don't know the code for displaying only a single page without scrolling page.
Please help me with this @fchasen .

**Comment by johnfactotum** [comment]
You can force one column by setting `spread` to `none`.

```js
let rendition = book.renderTo('viewer', {
      width: '100%',
      spread: 'none'
});
```

**Comment by Aryesh-M** [comment]
Yes, that is working! Thanks, @johnfactotum.
