### ISSUE TITLE
Is it possible to highlight content in an ePub?

### ISSUE THREAD

**Issue by hugohabel** [futurepress/epub.js#116]
I am trying to figure out if it is possible to highlight content in an ePub. I saw 2 files that may include this functionality: hooks/extensions/highlights.js and hooks/extensions/annotate.js

I guess the first one is to display highlights and the second one is for creating them. But I am not sure, the second one has several lines commented out.

If the functionality is not implemented yet, how can I help to implement it?

**Comment by JakeHartnell** [comment]
I'm working on a new example integration of [Hypothes.is](https://hypothes.is) which will add highlighting and annotation functionality. 

It is possible to highlight content in the epub using something such as annotator.js or hypothesis for example, but as highlighting requires storage of highlight data, it is perhaps out of the scope of the core of this library.
