### ISSUE TITLE
Possible method to access content of a Section

### ISSUE THREAD

**Issue by sivasatvik** [futurepress/epub.js#1161]
As seen from the documentation, a section is equivalent to a chapter in a book. So if I want to access the content of that chapter, is it currently possible using **book.spine.get()** component (This should return a HTML output, theoretically)? If so, at which point should it be called in order to get an output other than undefined.

**Comment by mcthulhu** [comment]
Try: rendition.on("rendered", function(section) {
		var currentChapter= rendition.getContents()[0].content.textContent;

**Comment by sivasatvik** [comment]
Ah. This seems to work. Thanks for letting me know @mcthulhu

**Comment by mcthulhu** [comment]
Another way to do it that might be simpler:

	var iframe = document.querySelector("div div div div iframe");	
	var html=iframe.contentDocument.documentElement.innerHTML;

The querySelector part might be different in your application.  I'm doing this after the book is already displayed.  I can modify the HTML (global replace) and then put it back into the iframe.
