### ISSUE TITLE
How to implement please?

### ISSUE THREAD

**Issue by Pete2021** [futurepress/epub.js#1167]
Hi, I would very much like to use this code on my website allowing users to view epubs hosted on my server. I'm really struggling to implement it and have spent several hours trying to make sense of the help file etc.

Could you give me a simple example of what script to run in my html to open an ePub file stored on my server:
e.g. 
https://mywebsuite/epubfile.epub

Thanks so much for your time!

**Comment by mskoenz** [comment]
Hi! I have the same issue: I followed your guide to no avail.
Here is what I did:

* Added `epub.min.js` to my `assets` dir of my jekyll project
* Added your `alice_without_cover.epub` to my `assets/img`
* Added a jekyll post (parts shown here):
  ```html
  The photobook is here.
  <div id="area">
  </div>
  Done
  
  <script src="/assets/epub.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.5/jszip.min.js"></script>
  
  <script>
    console.log("hello");
    var book = ePub("/assets/img/alice_without_cover.epub");
    var rendition = book.renderTo("area",  {width: 600, height: 400});
    var displayed = rendition.display();
    console.log(displayed);
  </script>
  ```
* Running jekyll with docker locally (localhost:4000)
* Tested on safari and firefox, both behave the same:
* <img width="310" alt="Screenshot 2021-03-01 at 12 17 25" src="https://user-images.githubusercontent.com/1257706/109490130-1a480300-7a88-11eb-9b1d-9a6883a7b555.png">

The code runs, the ebook is found, the displayed variable on pending, but no ebook visible on the screen.

How can I fix this?

**Comment by cbednarski** [comment]
I ran into the same issue. As noted in #1248, jszip must be loaded BEFORE epub.js.
