### ISSUE TITLE
Is ie11 not supported anymore? 

### ISSUE THREAD

**Issue by Sqrtme** [futurepress/epub.js#1172]

**Comment by Jaifroid** [comment]
Looks like it isn't. IE11 is history, but it's still a good proxy for older browsers.

![image](https://user-images.githubusercontent.com/4304337/233309785-bdbe4397-4493-4ef9-93a2-c46a7a9a1204.png)

**Comment by OriIdan** [comment]
The only use I know for IE (all versions) is to download chrome or firefox
:-)

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com
