### ISSUE TITLE
Use epub.js with UIWebView (iOS)

### ISSUE THREAD

**Issue by AlanFloyd** [futurepress/epub.js#120]
Hello. Could anyone help me to integrate epub.js into a iOS app, using UIWebView. I have several epub files in my app and depending on users choice, the epub should be shown. Any help is welcome, thanks.

**Comment by JakeHartnell** [comment]
-> [forum](https://github.com/futurepress/epub.js/issues/197)

**Comment by anoop4real** [comment]
@AlanFloyd  Did you figure out this?

**Comment by JakeHartnell** [comment]
Closing as much has changed since 2014 and no response from OP. I still recommend the forum for this kind of stuff.
