### ISSUE TITLE
Tips for using epub.js on local server

### ISSUE THREAD

**Issue by EvanofMT** [futurepress/epub.js#1203]
I've been able to make epub.js work using the public link "https://cdn.jsdelivr.net/npm/epubjs/dist/epub.min.js", but I don't understand how to use a copy of the file on my own server.  I've tried copying just "epub.min.js" to my server, but the script seems to be missing other dependencies.  This file by itself doesn't render the epub file.

I want to have a "local" copy of the javascript on the local server in case internet access is lost (a possibility for the project I'm working on).

I'm new to node.js programming and I'm wondering if I'm missing dependencies on my server.  The "Run Locally" portion of the Readme file does not include enough information to help me since I'm not very familiar with node.js.

Can someone elaborate or point me in the right direction to learn how to implement Epub.js locally?

**Comment by johnfactotum** [comment]
You just need `epub.min.js` and a copy of JSZip. See the [_Getting Started_](https://github.com/futurepress/epub.js/blob/master/README.md#getting-started) section in README.md, and the [examples](https://github.com/futurepress/epub.js/tree/master/examples).

**Comment by EvanofMT** [comment]
Thanks!  I tried this before, but just realized I had the scripts out of order.  I placed epub.min.js first like this:

<script src="epub.min.js"></script>
<script src="jszip.min.js"></script>

but it needs to be the reversed order, like:

<script src="jszip.min.js"></script>
<script src="epub.min.js"></script>

Thank you for the confirmation that I was mostly on the right track.
