### ISSUE TITLE
Font Size Change

### ISSUE THREAD

**Issue by Rohan-Rajesh** [futurepress/epub.js#1211]
Hi,

I want to implement buttons that increase and decrease font size, I looked through the docs and found the function that changes the font size i.e
`rendition.themes.fontSize('100px');`

But after running this function, it only shows up when I resize my browser window and the reader refreshes, is there any workaround to this issue

Any help would be appreciated
Thanks

**Comment by Rohan-Rajesh** [comment]
Hi,

For anyone facing this problem here's how I solved it:

Basic Logic: I basically set the `<div id="viewer"></div>`'s innerHTML to null and then rebuild the reader again...

Here's the basic code:
On font size change

Setting the reader to null:
`
document.getElementById("viewer").innerHTML =  '<div id="loader"><img src="img/loader.gif" /></div>';
`

Rebuilding the Reader:
`
reader = ePubReader(
        "http://pustaka.co.in/tam/epub/family/villan-engira-kathanayagan.epub",
        {
          restore: true,
        }
      );
`

Then set the default font size to the new value
`
rendition.themes.default({
    p: { "font-size": `${fontSize}px !important` },
});
`

That's it, this basically refreshes the reader while applying the default font size to the changed value... The only thing left to do is saving the user's last read location so that after refreshing the reader puts them back to the page they were reading

**Comment by xinmans** [comment]
> 

how to apply to code？
