### ISSUE TITLE
Contents addScript broken?

### ISSUE THREAD

**Issue by sorig** [futurepress/epub.js#1234]
Hi,

In a previous version of epub.js I was able to load scripts into a book's html using the `addScript` method of the `Contents` class. In version 0.3.90, I am no longer able to do that, due to the sandboxing attribute on the iframe view. 

I have tried setting `{"allowScriptedContent": true}`, when rendering the epub file, but this does not allow me to run my injected script. The problem is in [iframe.js](https://github.com/futurepress/epub.js/blob/228d9913e045a0515f5d22637178384850d8810a/src/managers/views/iframe.js#L94). Here, the `allowScriptedContent` setting is set, but the conditional also requires the section of the book to have a "scripted" property. My book is not scripted so it does not have that property, but I do want to inject and run my own script. This does not seem to be possible currently.

Is there a setting somewhere that I have missed that would make `addScript` work again?

**Comment by fchasen** [comment]
Published in `0.3.92`
