### ISSUE TITLE
CFI generated for `itemref` incorrectly uses `idref` instead of `id` for ID assertion

### ISSUE THREAD

**Issue by johnfactotum** [futurepress/epub.js#1236]
Given the following [example package document](http://idpf.org/epub/linking/cfi/epub-cfi.html#sec-path-examples) in the [spec](http://idpf.org/epub/linking/cfi/epub-cfi.html):
```xml
<?xml version="1.0"?>

<package version="2.0" 
         unique-identifier="bookid" 
         xmlns="http://www.idpf.org/2007/opf"
         xmlns:dc="http://purl.org/dc/elements/1.1/" 
         xmlns:opf="http://www.idpf.org/2007/opf">
    
    <metadata>
    	<dc:title>…</dc:title>
    	<dc:identifier id="bookid">…</dc:identifier>
    	<dc:creator>…</dc:creator>
        <dc:language>en</dc:language>
    </metadata>
    
    <manifest>
        <item id="toc"
              properties="nav"
              href="toc.xhtml" 
              media-type="application/xhtml+xml"/>
        <item id="titlepage" 
              href="titlepage.xhtml" 
              media-type="application/xhtml+xml"/>
        <item id="chapter01" 
              href="chapter01.xhtml" 
              media-type="application/xhtml+xml"/>
        <item id="chapter02" 
              href="chapter02.xhtml" 
              media-type="application/xhtml+xml"/>
        <item id="chapter03" 
              href="chapter03.xhtml" 
              media-type="application/xhtml+xml"/>
        <item id="chapter04" 
              href="chapter04.xhtml" 
              media-type="application/xhtml+xml"/>
    </manifest>
    
    <spine>
        <itemref id="titleref"  idref="titlepage"/>
        <itemref id="chap01ref" idref="chapter01"/>
        <itemref id="chap02ref" idref="chapter02"/>
        <itemref id="chap03ref" idref="chapter03"/>
        <itemref id="chap04ref" idref="chapter04"/>
    </spine>
    
</package>
```

Here is a test file containing the example package document: [cfibase.zip](https://github.com/futurepress/epub.js/files/7778834/cfibase.zip) 

**Expected behavior:**

The base CFI for the first chapter should be `/6/4[chap01ref]`.

**Actual behavior:**

Epub.js will generate `/6/4[chapter01]`, which incorrectly uses the ID of the `item` referenced by the `itemref`, instead of the ID of the `itemref` itself.

**Comment by OriIdan** [comment]
I think this is the correct behavior, it uses the id of the item, there is
no use for id in itemref and it is not required by EPUB.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by johnfactotum** [comment]
> I think this is the correct behavior, it uses the id of the item

See the linked spec and the examples in it. If I'm not mistaken, ID assertion should take the ID attribute of the element.

> there is no use for id in itemref and it is not required by EPUB.

Yes, there is. See https://www.w3.org/publishing/epub32/epub-packages.html#sec-itemref-elem.

It's an optional attribute. So if you don't use it, then the CFI will simply not contain an ID assertion. But if it does have an ID, then the corresponding CFI [must include an assertion](http://idpf.org/epub/linking/cfi/epub-cfi.html#sec-path-xmlid).
