### ISSUE TITLE
how to get the progress a reader made on a book using eupbjs

### ISSUE THREAD

**Issue by mohamadabdelhady** [futurepress/epub.js#1240]
I am building a website for reading book online and I want a way to get the progress mad by a user on a book so I can save it.

**Comment by OriIdan** [comment]
Use book.locations.percentageFromCfi(currCfi) where currCfi is the current
location CFI.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by mohamadabdelhady** [comment]
Do you know how to save location.start.cfi into a variable outside of the scope of the relocated function it keep give "undefined" when ever i console.log outside the scope of the function

**Comment by mohamadabdelhady** [comment]
> Use book.locations.percentageFromCfi(currCfi) where currCfi is the current location CFI. You can get the current CFI with the relocated event. the relocated event sends an object with information about the current page. rendition.on("relocated", function(location) { console.log(location.start.cfi) });
