### ISSUE TITLE
Shouldn't the lang attribute be set on the content document?

### ISSUE THREAD

**Issue by tjmtmmnk** [futurepress/epub.js#1260]
When using an iframe in the Viewer, there is a problem that the Japanese "..." should be centered but is biased.

![Screen Shot 2022-03-22 at 12 40 51](https://user-images.githubusercontent.com/31027514/159436992-d8878cea-f659-4d30-87db-b5816f0ec644.png)

![Screen Shot 2022-03-22 at 17 18 51](https://user-images.githubusercontent.com/31027514/159437272-751ccffb-6075-4788-abb1-1408b6d8d03c.png)

(the first is incorrect, the second is correct)

This is probably due to the fact that the `lang` attribute is not set when displaying html in an iframe.

I have a concrete example: https://jsfiddle.net/40wouf1z/
Specifying `lang='ja'` for the html in the `srcdoc` will result in the intended display.

So I propose to set `documentElement.lang` in `Contents` to `metadata.language` obtained from `Packaging`.

If this change is found to be reasonable, I would like to send a PR. Thank you in advance.

**Comment by johnfactotum** [comment]
The spec seems to suggest otherwise. The EPUB 3.2 spec [says](https://www.w3.org/publishing/epub32/epub-packages.html#sec-opf-dclanguage),
> This value is not inherited by the individual resources of the Rendition.

The EPUB 3.3 draft [says](https://w3c.github.io/epub-specs/epub33/core/#sec-opf-dclanguage) more clearly in a note,
> Publication Resources do not inherit their language from the `dc:language` element(s). EPUB Creators must set the language of a resource using the intrinsic methods of the format.

In other words, it is the book that should have set the attribute. That said, in the absence of the attribute in the content document, I would say that falling back to the metadata property would be reasonable behavior.

**Comment by OriIdan** [comment]
The dc:lang should not be the method a reading system determines the
directionality.
Directionality should be determined using the dir attribute of the body of
each xhtml file and the page-progression-direction of the spine.
This is what I understand from the specification.
N.B. I was on the metadata subcommittee of the EPUB version 3.01 and 3.1.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by johnfactotum** [comment]
This issue isn't about direction, though. It's about language-specific glyph variants. They opened a different issue about direction at #1257.

**Comment by tjmtmmnk** [comment]
@johnfactotum 

Thank you for the reply!
I had missed the specification specifying that Publication Resources does not inherit `dc:language`.

For each element of content([content](https://github.com/futurepress/epub.js/blob/master/src/contents.js#L31).querySelector('*')), how about setting the language if it is already set, and setting `dc:language` if it is not set?

**Comment by tjmtmmnk** [comment]
oh, it's clean! thank you!

**Comment by tjmtmmnk** [comment]
It worked well! Thank you!
