### ISSUE TITLE
 why   a blank area of horizontal sliding will appear

### ISSUE THREAD

**Issue by alsonY** [futurepress/epub.js#1296]
When the selected event is used on the mobile terminal, a blank area of horizontal sliding will appear

![991666337663_ pic](https://user-images.githubusercontent.com/32659772/197139493-cf20d9bb-bc95-43cf-95a1-dfdd23e30d54.jpg)

**Comment by robiulhassanshakil** [comment]
are you doing any continuous scrolling in your application? can you help me with that please.

**Comment by alsonY** [comment]
> 

I just long press the screen and it will appear
