### ISSUE TITLE
increase total pages of epub after increasing font in uiwebview.

### ISSUE THREAD

**Issue by iAnurag007** [futurepress/epub.js#130]
I am working on epub reader currently. I successfully read epub file in UIWebView. bUt my problem is i have two buttons for increasing and decreasing font. What i want is when i increase the font size , the total number of pages of epub should increase and vice versa. I am using AepubReader for reference, but not the Touch XML parsing used in AepubReader. (https://github.com/fedefrappi/AePubReader) but not able to integrate it in my code. Any help would be appriciated

**Comment by canado** [comment]
Hi iAnurag007
Did you manage to make it work ?
I m going through the same problem : (
