### ISSUE TITLE
Epub needs to be decrypted before it can be used. Where can it be decrypted

### ISSUE THREAD

**Issue by heavenswen** [futurepress/epub.js#1317]
My epub is encrypted and needs to be decrypted to display normally. How do I decrypt before content parsing？

**Comment by tienn2t** [comment]
Hello, have you solved this issue yet? Could you please share the code with me? I also need to encode and decode the content before displaying it.

**Comment by heavenswen** [comment]
> Hello, have you solved this issue yet? Could you please share the code with me? I also need to encode and decode the content before displaying it.
I read the api and couldn't get it to work, so I made a simple change directly in the source code。
https://www.npmjs.com/package/@geeboo/epub?activeTab=code
