### ISSUE TITLE
Failed to find epub resource path.

### ISSUE THREAD

**Issue by ux-ui** [futurepress/epub.js#1322]
Paths starting with "./" in the epub resource.

In the process of changing to blob,

"./" I can't load the file because it's changed without including the text.

"./" Is there any way to change url including?

I'm in a hurry.

**Comment by ux-ui** [comment]
How do I use Epub.js v0.4?

How do I load files through the service worker?

**Comment by johnfactotum** [comment]
Take a look at the v0.4 branch: https://github.com/futurepress/epub.js/tree/v0.4. AFAICT v0.4 is still work in progress, and I haven't tried it myself.

Also, you might be able use v0.3 and implement the service worker part yourself. It's similar to serving unpacked EPUBs with a server, except the service worker works on the client side.

IMO using service workers is not really ideal, though, as it's not really something a service worker is designed to do, but more like abusing its ability to intercept requests. It would be much better and easier to just set up a real server.

**Comment by ux-ui** [comment]
to appreciate the solution

**Thank you for your answer.**

I have a headache.

### First of all, I think we should look for the implementation of the service worker again!

Is there a bunch of code that could be an example?
