### ISSUE TITLE
Bocked script execution in 'about:srcdoc' because the document's frame is sandboxed and the 'allow-scripts' permission is not set

### ISSUE THREAD

**Issue by danyun123** [futurepress/epub.js#1329]
I rendered this ebook in vue3 and reported an error，Ebooks can be rendered on the page

![image](https://user-images.githubusercontent.com/100011153/235354415-85a1d2ef-6430-4569-b8fd-809daff939d5.png)

Here is my Vue3 code

![image](https://user-images.githubusercontent.com/100011153/235354463-997927a4-7ce8-40fa-9794-41716ddbc1e2.png)

**Comment by ompurwar** [comment]
hey did you find any solution to this?

**Comment by danyun123** [comment]
> hey did you find any solution to this?

No, I've ignored the question for the moment

**Comment by daGaiGuanYu** [comment]
把 `allowScriptedContent: true` 放在 `renderTo` 的参数里试试  
https://github.com/futurepress/epub.js#scripted-content

**Comment by danyun123** [comment]
> 把 `allowScriptedContent: true` 放在 `renderTo` 的参数里试试 https://github.com/futurepress/epub.js#scripted-content

感谢！！

**Comment by isener** [comment]
> 把 `allowScriptedContent: true` 放在 `renderTo` 的参数里试试 https://github.com/futurepress/epub.js#scripted-content

It simply adds `allow-scripts` to the iframe and works! Thanks for the suggestion.

**Comment by Libpzzz** [comment]
> > 把参数`allowScriptedContent: true`放在`renderTo`尝试https://github.com/futurepress/epub.js#scripted-content
> 
> 它只需添加`allow-scripts`到 iframe 即可运行！感谢您的建议。

![image](https://github.com/user-attachments/assets/0cf91135-5cab-4c7d-ab76-f8277a9161d0)
I am using version 0.3.90.It doesn't seem to have come true.Can you give me some advice?
