### ISSUE TITLE
Issues getting epub to work with Require/ r.js

### ISSUE THREAD

**Issue by njj023** [futurepress/epub.js#134]
Hi guys,

Thanks for making this awesome library, I can't wait to use it! 

I am currently trying to get epub.js set up in my Grunt build system that uses grunt-contrib-requirejs to concatenate and import all required files. I was able to get all the source code for epub.js through Bower.

But when I call a require on epub.js, I get a "mismatched anonymous define module" which according to requirejs (http://requirejs.org/docs/errors.html#mismatch) stems from the fact that the combined epub.js file has several define modules (for RSVP) and an anonymously defined module such as this:
define(function(){ return ePub; });

I could just call require on your base.js but that wouldn't load all the dependencies such as RSVP.

So are you guys aware of how to get this running with RequireJS? Any help would be greatly appreciated. Thanks.

**Comment by Khrystyna** [comment]
@njj023 

Hi! I am trying to use epub.js in my Backbone + RequireJS app and without luck. I included build/epub.js and, as I see, it has RSVP included, at the top. 

However, I get Uncaught ReferenceError: RSVP is not defined (epub.min.js:3018). Could you please help me to fix it?
