### ISSUE TITLE
Minified XML causes 'container.xml not found'

### ISSUE THREAD

**Issue by Aonodensetsu** [futurepress/epub.js#1382]
When the XML in `META-INF/container.xml` is minified into one line, epubjs errors with `File not found` despite the XML being valid.

**Comment by johnfactotum** [comment]
Can you provide an example file? It seems that `DOMParser.parseFromString()` doesn't really throw on malformed data and would return an empty document if desperate. So even in the case of a totally invalid container.xml, Epub.js says `No RootFile Found` rather than `Container File Not Found`.

**Comment by Aonodensetsu** [comment]
Example [EPUB](https://c.00t.in/min) that does not work.
Same [EPUB](https://c.00t.in/unmin) opened in 7zip and unminified container.xml.

**Comment by johnfactotum** [comment]
I haven't checked out the files but

1. You're using Epub.js v1/v2? You should probably consider upgrading to v3.
2. In the screenshot, the error is from before the XML gets parsed so it probably has nothing to do with the content of the file.

**Comment by Aonodensetsu** [comment]
Resaving the file with no changes also works so i guess a weird encoding header it might be.
