### ISSUE TITLE
Force only one page/image in the screen

### ISSUE THREAD

**Issue by aron-bordin** [futurepress/epub.js#139]
Hi!,
In my ePub, each page is an image. But when I read it, I can see two images in the same screen. How can I force to show only one page/image, without dividing it by two?

And how can I auto resize these images? I tested the reader example and it auto resize everything, but I cannot figure out how to do that. 

Thx

In this screenshot, the reader shows two pages. 
![screenshot_2014-05-27-15-23-57 1](https://cloud.githubusercontent.com/assets/4960137/3095988/ac62d7fc-e5ce-11e3-985f-a4b18a51d9f5.png)

**Comment by bassburak** [comment]
you can use, ../hooks/default/smartimages.js in your ePub project.
