### ISSUE TITLE
Support non-integer Page Numbers in PageList (eg. i, ii, iii)

### ISSUE THREAD

**Issue by centogram** [futurepress/epub.js#146]
In EPUBJS.Parser.prototype.pageList can we convert the 
page = parseInt(text) call to simple page = text inside getPages(parent) function ?

Would also need to update EPUBJS.Pagination.prototype.cfiFromPage to find both integer and non-integer indices in this.pages

**Comment by fchasen** [comment]
Still need to fix this. Does anyone have an epub they could share that have non integers in the page list?

**Comment by JakeHartnell** [comment]
> Does anyone have an epub they could share that have non integers in the page list?

Ditto. Closing for now.
