### ISSUE TITLE
ePub not showing up in Internet Explorer

### ISSUE THREAD

**Issue by fubarslayer** [futurepress/epub.js#150]
Using epub.js (downloaded master branch with v0.2.1) on a personal website and trying to view ePubs in Windows 8.1 with Internet Explorer 11.

I can see that the iframe appears and getMetadata and getToc work but the content of the ePub does not show up (tried several ePubs).

I can see the following info with F12 - Console:
HTML 7007: One or more blob URLs were revoked by closing the blob for which they were created. These URLs will no longer resolve as the data backing the URL has been freed.

All tested ePubs work in the following combinations:
Windows 8.1 + Chrome/Firefox
Ubuntu 12.04 + Chrome/Firefox
Android 4.4.2 + Chrome/Dolphin/Firefox

It looks like this is some kind of bug in Internet Explorer.
Possibly related:
http://stackoverflow.com/questions/20654531/ie-frees-blob-urls/24351008#24351008

**Comment by yxbwzx** [comment]
I found that if there is no content in the "Titile" tag in all of the xhtml file or html file( the unzip epub file)
then the epub will not show in IE.
I'm test in Windows 8.1 with Internet Explorer 11,
when I am remove the content in the title tag, it doesn't work in IE
this is my test file :"epub.js-master\reader\moby-dick\OPS\cover.xhtml"
hope the team can fix this bug.
btw: en is not my private language :)
