### ISSUE TITLE
Error: this.zip.getMimeType not a function

### ISSUE THREAD

**Issue by dsk7** [futurepress/epub.js#176]
If using the original minimized jszip from http://stuk.github.io/jszip/ (like suggested in https://github.com/futurepress/epub.js/blob/master/README.md), the above error message appears when I try to open a zipped epub file.

The missing function can be found in https://github.com/futurepress/epub.js/blob/master/libs/jszip/mime-types.js and is automatically built into your jszip.js.

Using your jszip.js or additionally including mime-types.js will solve this issue.

It would be nice to have that in the main readme file.

Cheers and keep up the good work!

**Comment by fchasen** [comment]
Thanks! Will try to include that file with the releases as well.
