### ISSUE TITLE
Fixed layout syntax error

### ISSUE THREAD

**Issue by madmox** [futurepress/epub.js#177]
An error occurred while opening an epub with fixed layout format:

    An invalid or illegal string was specified

    EPUBJS.Layout.Fixed.prototype.format@http://www-dev.testsite.com/js/epub.js:5118:16
    EPUBJS.Renderer.prototype.load/<@http://www-dev.testsite.com/js/epub.js:6153:18
    invokeCallback@http://www-dev.testsite.com/js/epub.js:1542:18
    publish@http://www-dev.testsite.com/js/epub.js:1215:8
    publishFulfillment@http://www-dev.testsite.com/js/epub.js:1632:6
    flush@http://www-dev.testsite.com/js/epub.js:227:8

It seems to be a syntax error on line 5118 of epub.js:
`var viewport = documentElement.querySelector("[name=viewport");`
should read:
`var viewport = documentElement.querySelector("[name=viewport]");`

The source file can be found [here](https://github.com/futurepress/epub.js/blob/da11659d6cb0426904d9359ada92d5abc198bd6a/src/layout.js#L128).

**Comment by fchasen** [comment]
Thanks for reporting this, fixed on the latest master.
