### ISSUE TITLE
Can't load JavaScript files from zipped ePubs

### ISSUE THREAD

**Issue by madmox** [futurepress/epub.js#180]
When I include JavaScript files in an ePub archive, and reference it in the package file and in the main xhtml document as a script resource, the JS are never loaded.

Actually it works when the ePub is not zipped, but when it is, the relative URLs in the xhtml are correctly replaced with Blob URLs pointing to valid copies of the JS files from the archive, but it seems the browser is unable to load them as scripts from there (even though the blob is created with an "application/javascript" mime type and has the same domain as the iframe).

Here is [an example](http://s000.tinyupload.com/index.php?file_id=09204455623903517019).

**Comment by JakeHartnell** [comment]
Is this still a problem? I'm issue cleaning at the moment so we can get a better idea of what actually needs work, so closing for now. Feel free to reopen with updates / more details.
