### ISSUE TITLE
IE displaying cover + np1 np2 no more content

### ISSUE THREAD

**Issue by canado** [futurepress/epub.js#184]
I can view the cover on IE but I can only read few pages, then, no more pages

**Comment by canado** [comment]
I managed to make it work but I had to merge some code between the IE file and the other files : (
Can we have an unique solution to make this works on all browsers ?

**Comment by canado** [comment]
And it's not working on ipad, 
Is there a branch with the code working on both Desktop ( chrome/safari/ff/IE ) AND tablets (android/iOS) AND phones (android/iOS) ?


Thanks

**Comment by fchasen** [comment]
Sorry for the delay in responding, do you have a epub you could share that isn't working?
Also what version of IE is failing?

Have you included wgxpath for the IE issues?
I tend to install wgxpath via a hook like the one here: https://github.com/futurepress/epub.js/blob/master/hooks/extensions/wgxpath.js

```javascript
EPUBJS.Hooks.register("beforeChapterDisplay").wgxpath = function(callback, renderer){

  wgxpath.install(renderer.render.window);

  if(callback) callback();
};

wgxpath.install(window);   
```

**Comment by canado** [comment]
I found the code in another branch but I had to mix it with other source of codes,
Do you have a branch which can work on all platform at once ?

**Comment by JakeHartnell** [comment]
Not helpful. Closing.
