### ISSUE TITLE
How can i get current page number in epubjs api ?

### ISSUE THREAD

**Issue by bassburak** [futurepress/epub.js#188]
Hi everyone,
I see the lastPage, firstPage, totalPages data in my book json after the generate pagination. But i want to catch current page index.

**Comment by fchasen** [comment]
You should be able to listen to the ```book:pageChanged``` event to get the ```anchorPage``` which will be your current page.

Something like this:

```javascript
            book.on('book:pageChanged', function(location){
                console.log(location.anchorPage, location.pageRange)
            });
```

from https://github.com/futurepress/epub.js/blob/master/examples/pagination.html

**Comment by bassburak** [comment]
works perfectly! thank you :)
