### ISSUE TITLE
getToc() return an empty array on ie 

### ISSUE THREAD

**Issue by Genet** [futurepress/epub.js#190]
Call the function getToc() always return an empty array.
querySelector with namespace seem doesn't work well and always return null.

https://github.com/futurepress/epub.js/blob/master/src/parser.js#L262
```javascript
EPUBJS.Parser.prototype.nav = function(navHtml, spineIndexByURL, bookSpine){
   var navEl = navHtml.querySelector('nav[*|type="toc"]'), //-- [*|type="toc"] * Doesn't seem to work
```

**Comment by fchasen** [comment]
Do you have a book I can test with?

**Comment by Genet** [comment]
I used the example Single.html and the given book "../reader/moby-dick/".

**Comment by claytonk** [comment]
See https://github.com/futurepress/epub.js/issues/235#issuecomment-143008704 for changes need to get TOC working in IE.

**Comment by fchasen** [comment]
Looks like IE won't allow for querying for `<nav epub:type="toc">` added a function to deal with namespace querys in the latest master.
