### ISSUE TITLE
Epub file doesn't work on ie

### ISSUE THREAD

**Issue by Genet** [futurepress/epub.js#191]
If i use the reader with an epub file container (not a unzipped directory URL), i have a blank page and no error on all versions of ie.
I just changed the URL "../books/moby-dick/" to "../books/moby-dick.epub" and added wgxpath and jszip libraries in the Single.html example.

**Comment by canado** [comment]
do you manage to make IE works with an unzipped directory ?

**Comment by Genet** [comment]
Yes it works with an unzipped directory.

**Comment by fchasen** [comment]
What version of IE isn't working with the .epub zipped epub?

**Comment by Genet** [comment]
IE 9, 10 & 11 on Windows 7 (https://www.modern.ie/en-us/virtualization-tools#downloads)

**Comment by pateljatin** [comment]
noticed this on IE11, Win 7.

**Comment by JakeHartnell** [comment]
No discussion for awh
