### ISSUE TITLE
Permission denied IE

### ISSUE THREAD

**Issue by canado** [futurepress/epub.js#192]
I had to clean my ftp, and I couldn't find my previous file : (
So I had to start back from the epubjs source files

I checked the ie.html which includes the wgxpath
The cover is loading that means the xgxpath works
The titlepage.xhtml loads as well

but when on titlepage.xhtml,  I click next I have this message error
Permission denied undefined
Could not load Chapter: /dev_IE/books/moby-dick/OPS/toc-short.xhtml

if I look deeper in the code I can tell that in the file rsvp.js ( under define("rsvp/instrument",  )
has this object

promise._detail: typeError: Permission denied

description "Permission denied"
message "Permission denied"
name "TypeError"
number -2146828218

then in book.js, this error triggers a catch error in the function

EPUBJS.Book.prototype.displayChapter

render.then(function(rendered){
function(error) {
		// handle errors in either of the two requests
		console.error("Could not load Chapter: "+ chapter.absolute);
		book.trigger("book:chapterLoadFailed", chapter.absolute);
		book._rendering = false;
		defer.reject(error);
	});

Now if I open Charles's webdebugging
I can tell that 
-package.opf is loaded
-cover.xhtml is loaded
-titlepage.xhtml is loaded
-toc-short.xhtml is loaded

so everything seems fine, but still the js code returns Permission denied on toc-short.xhtml and so the page is not displayed !
Any idea ?
thanks

**Comment by canado** [comment]
Something weird in core.js
in EPUBJS.core.request / function handler() {
I do alert(r) and I can see the html code of the toc, so it does load the file and somehow I have the error 
Permission denied undefined

**Comment by canado** [comment]
Turns out, 
if you have one epub with one cover and one chapter, everything is fine, no error.
but if you have one epub with one cover and multiple chapters or toc etc ... on IE, it can't "load" the next chapter and render it onto the iframe. I still don't know why

**Comment by fchasen** [comment]
Thanks for digging into this, I will try to reproduce it on a virtual machine. 
What version of IE should I test with?

**Comment by canado** [comment]
: ) Basically IE 11 ( edge ) but here is the full description
Browser CodeName: Mozilla
Browser Name: Netscape
Browser Version: 5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; rv:11.0) like Gecko
Cookies Enabled: true
Browser Language: en-US
Browser Online: true

User-agent header: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

**Comment by pateljatin** [comment]
I've noticed the same issue now as well. V11 as well. (11.0.16) - on Windows 7.  I'll try Win 8 next.

**Comment by MarkisLt** [comment]
Finaly i've found a solution.
in hooks.js
there is event : renderer:chapterUnloaded, this causes a problem in IE.
FIX:

hooks.js file:
			renderer.on("renderer:chapterUnloaded", function(){
				try {
					item.removeEventListener('load', size);
				} catch(e) {
					//console.log(e);
				}
				renderer.off("renderer:resized", size);
			});

**Comment by fchasen** [comment]
Many thanks to @MarkisLt for tracking this down!
