### ISSUE TITLE
Epub access denied on ie11.

### ISSUE THREAD

**Issue by SeregaSh** [futurepress/epub.js#195]
The uPub doesn't work in IE11 (everything is ok in others). I work with zipped "*.epub" file.
The first issue is in the "EPUBJS.Unarchiver.prototype.getUrl" method. The "entry.getBlob" function returns not correct tempUrl. I added the code in this function:
if (window.navigator.msSaveOrOpenBlob) {
            url = tempUrl;
            url = url.split('blob:')[1];
            var img = document.createElement('img');
            img.src = url; // set string url
            url = img.src; // get qualified url
            img.src = null; // no server request
            tempUrl = escape('blob:' + url);
}
But after that, in the function "this.iframe.onload", after making "this.iframe.contentWindow.location.replace(url);" we can't get access to the "render.iframe.contentWindow" - the IE writes "access denied".
Please help. Thanks.

**Comment by pateljatin** [comment]
+1 - I am getting the same error. Did anyone find a solution to this?

**Comment by fchasen** [comment]
This issue should be fixed, `this.iframe.contentWindow.location.replace(url)` is no longer used.
