### ISSUE TITLE
how can i reload currentChapter without setLeft

### ISSUE THREAD

**Issue by bassburak** [futurepress/epub.js#196]
Hi,
I want to reload viewport from current chapter for some reasons.  But I can't find any way to do this.
After scale font size, the api sends me wrong currentpage and totalpages number. Anyway only solution  i found, 

//refresh viewport
book.prevChapter().then(book.nextChapter()));

but its not good solution, i need to some better way.
Thank you.

**Comment by JakeHartnell** [comment]
> I need to some better way.

Then figure it out.
