### ISSUE TITLE
Font change only applies to header

### ISSUE THREAD

**Issue by Anzumana** [futurepress/epub.js#198]
hey,
Using
book.setStyle("font-family","Times New Roman")
Only applies that Style to the headers of the different chapters in the example moby dick epub.
Is there a away to apply the style to the entire epub?
Regards,
Anzumana

**Comment by fchasen** [comment]
I'd guess that the css styles in the epub for other text items are more specific.
You could try ```book.setStyle("font-family","Times New Roman !important")```

**Comment by Anzumana** [comment]
i tried that did not work. any other ideas?
This is the case for me using the moby dick sample book.
So you should be able to replicate the issue.
Thanks for all the great work btw :)

**Comment by Anzumana** [comment]
when i remove the css font entry inside the epub the style get applied. to perfect but it works.
