### ISSUE TITLE
Playframework issues

### ISSUE THREAD

**Issue by nmuldashev** [futurepress/epub.js#200]
I have problems to open book through Playframework 1.2.5.3
In console I have some warnings:
"Not yet Rendered" and "not found, try fuzzy match" and in browser I see source code of epub. When I proxy book through NGINX it works. Why is it so?

And second problem is how to open exact page of book? I'm saving each CFI when user open each page. User want to continue reading on page he stopped.
My code is:
document.onreadystatechange = function() {
		if (document.readyState == "complete") {
			EPUBJS.filePath = "@{'public/epubplayer/js/'}/libs/";
			EPUBJS.cssPath = "../public/epubplayer/css/";
			// fileStorage.filePath = EPUBJS.filePath;
			var currentState = "${Resource.currentState}"
			reader = ePubReader("/public/CORs/${resource.id}/${resource.corName}/");
		}
	};

and in EPUBJS.Renderer.prototype.page function I added code:

	if(pg >= 1 && pg <= this.displayedPages){
		this.chapterPos = pg;
		jQuery.ajax({
			url:updateCurrentPositionUrl,
			method:"POST",
			data: {resourceId:resourceId, position: this.getVisibleRangeCfi().start}
		});

**Comment by fchasen** [comment]
I'll have to look into the Playframework a bit, not sure what it is.

To restore to a previous locations you could pass it in the reader settings

```
reader = ePubReader("/public/CORs/${resource.id}/${resource.corName}/", {
     previousLocationCfi: YOUR_CFI
});
```

or 

```
reader.book.goto(YOUR_CFI)
```

**Comment by fchasen** [comment]
Also the easiest way to save the location would be to listen to the `pageChange` event.

```javascript
reader.book.on('renderer:locationChanged', function(cfi){
    jQuery.ajax({
        url:updateCurrentPositionUrl,
        method:"POST",
        data: {resourceId:resourceId, position: cfi}
    });
});
```

**Comment by nmuldashev** [comment]
Thanks. It works.
What about :
"Not yet Rendered" and "not found, try fuzzy match" and in browser I see source code of epub. When I proxy book through NGINX it works. Why is it so?

**Comment by fchasen** [comment]
I would guess there is something going on the the mime type of the document.
If you inspect the response headers what is the content-type of the un-proxyed html content vs nginx proxyed html content?

**Comment by nmuldashev** [comment]
Which files?
