### ISSUE TITLE
Blank screen on Blackberry

### ISSUE THREAD

**Issue by ersten** [futurepress/epub.js#201]
Awesome script, but my Blackberry device (Bold 9900) shows permanent blank screen.
No book content, no warnings, no errors - absolutely empty screen. Other html-elements on same page shows correctly.
On my desktop all working right.

How I may debug this script and find the issue?

Thanks.

**Comment by fchasen** [comment]
Yikes, thanks for reporting this -- not sure how to test on a blackberry.
I'd guess that the browser doesn't support xpath or possibly doesn't support css3 columns.

Do you know of a better feature support document then this one? http://docs.blackberry.com/en/developers/deliverables/11844/BB_Browser_content_support_by_version_438586_11.jsp

**Comment by JakeHartnell** [comment]
No discussion for awhile, no way to reproduce. Closing, unless someone can provide more insight into what might be the issue.
