### ISSUE TITLE
responseType error

### ISSUE THREAD

**Issue by apolkingg8** [futurepress/epub.js#202]
I got this error message on Android 4.3 with Cordova 3.6 and Crosswalk 10.
```
Uncaught InvalidStateError: Failed to read the 'responseXML' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'document' (was 'arraybuffer').
```
It's happened when I try to `open` a local and zipped `.epub` file (ex: `file:///storage/emulated/0/AnEpubBook.epub`), but it's works fine when I `open` a unzipped epub dir.

**Comment by gterrono** [comment]
@apolkingg8 Did you get this to work? I'm running into a similar error. It works fine with zipped and unzipped epubs in the assets folder, but it has this error when trying to open an epub from /storage.

**Comment by apolkingg8** [comment]
@gterrono No. I added a native plugin and unzip files before open with epub.js.

**Comment by gterrono** [comment]
But it works opening from `file:///storage`?
