### ISSUE TITLE
Footnote not working in zipped epub

### ISSUE THREAD

**Issue by Infernion** [futurepress/epub.js#203]
Hi guys!
Footnotes didn't show when book in *.epub, if it in the dir footnote is showing. 

My code is below:

```
</p><a   epub:type="noteref" href="#n1">1</a></p>

<aside epub:type="footnote" id="n1">
    <p>
    These have beenkjjjjjjjjj corrected in this EPUB3 edition.
    <a href="http://vk.com">VK</a>
    <img src="0302.png"/>
    </p>
</aside>
```

and it creates this link: `blob:http%3A//dev%3A8000/4fee7ff1-5769-42a4-b49e-bbb148f8a81d#n1`

**Comment by JakeHartnell** [comment]
See: https://github.com/triplecanopy/b-ber-boiler/issues/8

**Comment by chrisovato** [comment]
Same issue, any ideas on how to solve it?
the link has expired.
