### ISSUE TITLE
It is not possible to load book with itemref prefixed by ns in content.opf file.

### ISSUE THREAD

**Issue by bielskij** [futurepress/epub.js#205]
Hi,

  on some ebooks epub.js crashed on book parsing stage. I've found that method getElementsByTagName("itemref") returns empty list if itemref in content.opf file is prefixed by it's namespace. Please find following fragment of my content.opf:

``` xml
  <ns0:spine toc="ncx">
    <ns0:itemref idref="titlepage" />
    <ns0:itemref idref="id18" />
    <ns0:itemref idref="index_split_001.xhtml" />
    <ns0:itemref idref="Section0001.xhtml" />
  </ns0:spine>
```

Only one solution I've already found is to replace usage of method getElementsByTagName() with method getElementsByTagNameNS with "*" as first parameter (namespace wildcard). 

You can see the change in my fork of epub.js repository (last commit).

Best Regards,

**Comment by fchasen** [comment]
Would you be able to submit a pull request for this?

**Comment by JakeHartnell** [comment]
If anyone else has this issue feel free to reopen. Addition a `.epub` file that demonstrates this problem would be appreciated.
