### ISSUE TITLE
Problem with display .epub book on android WebView

### ISSUE THREAD

**Issue by harutinnnn** [futurepress/epub.js#208]
When use .epub on android webview displays the following -> white Cover and after ne nothing works. And on the browser to working normaly. If the problem is in the cover and can not download it as soon as possible to make so that cover and other images are not shown. 

Thanks in advance

**Comment by bahinapster** [comment]
use setallowuniversalaccessfromfileurls 

Good luck

**Comment by watf** [comment]
¿Did you fix this?

**Comment by fchasen** [comment]
As @bahinapster mentioned, http://developer.android.com/reference/android/webkit/WebSettings.html#setAllowUniversalAccessFromFileURLs(boolean) might help or this could be related to https://github.com/futurepress/epub.js/issues/272.

**Comment by JakeHartnell** [comment]
No follow up in almost two years.
