### ISSUE TITLE
layoutOveride is being ignored

### ISSUE THREAD

**Issue by gterrono** [futurepress/epub.js#209]
I was trying to make a reader with a fixedLayout, but nothing I saw in the other issues/documentation seemed to be working.

I think the issue is with [this function](https://github.com/futurepress/epub.js/blob/master/src/book.js#L1246). When I switched all the `this.layoutOveride` to `this.settings.layoutOveride`, the solution suggested in #132 worked as expected.

**Comment by fchasen** [comment]
Thanks, fixed in https://github.com/futurepress/epub.js/commit/e27708537ef3184700b12954f39270c5119ac3d0.
