### ISSUE TITLE
generatePagination doesn't work a second time

### ISSUE THREAD

**Issue by benwalsh** [futurepress/epub.js#210]
I'm want to regenerate pagination on certain events, like when the screen is resized. On initial page load the `generatePagination` promise callback works fine:

```
this.epub.generatePagination().then(function (pages) {
   *[ do some stuff ]*
});
```

However when I call this method on subsequent occasions the callback is not processed. The method returns an `l` object that looks like this:

`l {_id: 1234, _label: undefined, _subscribers: Array[0], constructor: function, _guidKey: "rsvp_[timestamp]-"…}`

Am I doing something wrong? Should I be using a different method to regenerate the pagination?

**Comment by bahinapster** [comment]
This works for me 


                Book.ready.all.then(function(){
                Book.generatePagination().then(function () {
                    console.log(Book.pagination.totalPages);
              });
              });
