### ISSUE TITLE
Can't play video contained in an EPUB file

### ISSUE THREAD

**Issue by dmartel** [futurepress/epub.js#211]
Hello,

I have a problem with an EPUB containing video.
(Creative Commons Shared Culture, available here: http://idpf.github.io/epub3-samples/samples.html)

(I don't see anything about this problem here...)

Using the unzipped version of the EPUB: it's working without any problem.

``` javascript
    var book = ePub("reader/cc-shared-culture/");
```

Using the zipped version of the EPUB: I can't play the video.

``` javascript
    var book = ePub("reader/cc-shared-culture.epub");
```

The error is:

``` javascript
Uncaught ReferenceError: checkReadingSystemSupport is not defined
```

Apparently the browser does not load the JavaScript file "**shared.js**" of the **p20.xhml** file.

Do you have any idea of the problem ?

Moreover, if anyone has another EPUB file containing video to test...

Thanks.

**Comment by fchasen** [comment]
Thanks for sending an example, I'll take a look.

**Comment by JakeHartnell** [comment]
An updates on this? It's been over two years...

Closing for now, but if this is still an issue feel free to reopen.
