### ISSUE TITLE
Zoom functionality / Permalink functionality

### ISSUE THREAD

**Issue by mrmayfield** [futurepress/epub.js#214]
Hi there, and thanks for the module.

Is there any way to zoom in or out on the text and have it reflow? That's one of the main advantages of the epub format that I can think of, and I can't seem to find this functionality in the module.

Also, is there anyway to have a permanent URL anchored to, say a specific page or specific chapter? Thanks again.

**Comment by truonghoangnguyen** [comment]
are you mean : http://www.onelib.org/epub/kinh-tuong-ung-bo
try incr/decr font size in `+`, `-` button.

You can used `epub.setStyle`
below is my code example implement in angular.
 
              scope.vm.epub = ePub("myepub.epub", { restore: true});
                .... then in change font size function:
              // val = 1 for incr, -1 for decr font size
              scope.fontSide = function (val){
                var intv = 10;
                scope.settings = scope.settings || {styles:{}};
                if (!scope.settings.styles.fontSize) {
                    scope.settings.styles.fontSize = "100%";
                }

                var fontSize = parseInt(scope.settings.styles.fontSize.slice(0, -1));
                if (val > 0) {
                    scope.settings.styles.fontSize = (fontSize + intv) + "%";
                }
                else {
                    scope.settings.styles.fontSize = (fontSize - intv) + "%";
                }
                scope.vm.epub.setStyle("fontSize", scope.settings.styles.fontSize);
            };

**Comment by sadabjr** [comment]
is it also work for pdf zoom in and zoom out?
