### ISSUE TITLE
Deadlock in Book.js

### ISSUE THREAD

**Issue by MaxDaten** [futurepress/epub.js#216]
Hi, 

maybe I'm lacking in insight, but is there a possible deadlock introduced here?

[Book.js L110](https://github.com/futurepress/epub.js/blob/aaa57035655e1595d439d8da233a3c27e6eb60c6/src/book.js#L110) & [Book.js L111](https://github.com/futurepress/epub.js/blob/aaa57035655e1595d439d8da233a3c27e6eb60c6/src/book.js#L110)

The `this.opened` or `this.defer_opened` promise seems to be never resolved or rejected but is used in [Book.js L658](https://github.com/futurepress/epub.js/blob/aaa57035655e1595d439d8da233a3c27e6eb60c6/src/book.js#L658)

additional `EPUBJS.Book.prototype.open` introduced a new local `opened` promise without using or setting `this.opened` promised. Is this intentional?

The spooky thing is, epub.js works on desktop browsers like chrome, firefox or safari for me, but it shouldn't, if I'm right. But under some still unknown circumstances epub.js stops working on mobile browsers or when bundled in a cordova app.

Maybe related:
#215

**Comment by fchasen** [comment]
Thanks for digging into this, I need to look into cordova a bit, I'd guess that the request to get the book files is failing. Overwriting this function might be needed to work with cordova: 
https://github.com/futurepress/epub.js/blob/aaa57035655e1595d439d8da233a3c27e6eb60c6/src/core.js#L14-L91

If the book request is successful, that deferred should be resolved at https://github.com/futurepress/epub.js/blob/aaa57035655e1595d439d8da233a3c27e6eb60c6/src/book.js#L160 or https://github.com/futurepress/epub.js/blob/aaa57035655e1595d439d8da233a3c27e6eb60c6/src/book.js#L169

 ```EPUBJS.Book.prototype.open``` introduces it's own deferred, as well as resolving the global deferred, as it could (but probably shouldn't be) used multiple times to open different books.

**Comment by MaxDaten** [comment]
Hi and thank for the reply. I had time to investigate it a bit further. Your hint helpt a lot, and you are right.  I've overwritten the request function with my own, and it worked. Somehow the error message was suppressed by the Safari Development Tool. Thanks for your help.
