### ISSUE TITLE
Issue with epub width/height ratio while rendering/scalling/resizing

### ISSUE THREAD

**Issue by vipul-jain** [futurepress/epub.js#217]
I am using epub.js/reader/dev.html file as base of my project for rendering epubs. but it has fixed height/width container for loading epubs but i want epub reader should take dynamic window height/width and should fit to it. 

also it should work well on resize.. i have completed most of stuff like resizing, fit to screen by default, zoomin-zoomout but issue coming is with different devices and scaling/zoom epub conatiner not displaying text properly..sometime it's getting cut from left/right sides and some times two cloumn getting visible . i want to have single column always even if we do zoomin-zoomout and load in different devices.

as i want to support zoomin-zoomout feature, i am doing it by scaling epub container. it works well for portals and few small devices too but it is now creating issues for me as mac's safari don't support scaling using CSS's transform property. and if i change width of epub container dynamically for scaling it will not loading up properly as width is going to changed but -webkit-column-width and -webkit-column-gap defined while rendering epub is based on previous width.

So it will be good if you guys can help me for achieving this requirement.

Thanks,
Vipul

**Comment by JakeHartnell** [comment]
-> [forum](https://groups.google.com/forum/#!forum/epubjs)
