### ISSUE TITLE
Search on epub returning incorrect result sometimes.

### ISSUE THREAD

**Issue by vipul-jain** [futurepress/epub.js#218]
I am using https://github.com/futurepress/epub.js/blob/master/reader/dev.html. here, Search returns incorrect result sometimes and also not display any results even if it's exist. and when results are there and we click on it most of time it throws us to cover page only.

Can anybody help me with this?

Thanks,
Vipul

**Comment by JakeHartnell** [comment]
The issue tracker is not the place for this, might I suggest posting in the [forum](https://groups.google.com/forum/#!forum/epubjs)?
