### ISSUE TITLE
Detecting when the size of the window changes to give a new maximum value range (Pagination)

### ISSUE THREAD

**Issue by Grovertb** [futurepress/epub.js#222]
Detecting when the size of the window changes to give a new maximum value range (Pagination)

for example: http://archivos.owlgroup.org/owl/ebook/grover.jtb@gmail.com/56

**Comment by fchasen** [comment]
Sorry for the confusion but the pagination is based on the `pageList` which assigns a page number to a cfi location which doesn't change based on the screen size.

You can call use `book.renderer.getRenderedPagesLeft()` to return the number of pages left to be read or `book.renderer.pagesInCurrentChapter()` to get all the *displayed* pages in a chapter.
