### ISSUE TITLE
Only works on firefox

### ISSUE THREAD

**Issue by ianiD** [futurepress/epub.js#223]
So, I made this simple epub reader using epub.js. When I run it on firefox, it works with no problems, but when I run it on chrome or opera I get these errors:
![capture](https://cloud.githubusercontent.com/assets/5314253/7959806/bbe88874-0a04-11e5-8fe6-5914cc7b5487.PNG)

**Comment by duongcuong96** [comment]
i think you need to use local Server
open .html directly on browser is not allowed due to secure reason
