### ISSUE TITLE
Jumping to Chapter

### ISSUE THREAD

**Issue by mattpramschufer** [futurepress/epub.js#224]
When utilizing the Hypothesis example, how would you go about jumping to a specific chapter in the ebook.  My current code is 

```javascript
 $(function () {

                    EPUBJS.VERSION = "0.1.6";
                    EPUBJS.filePath = "js/libs/";
                    EPUBJS.cssPath = "../reader/css/";

                    var reader = ePubReader(epubUrl);
                        reader.book.displayChapter(3);

                });
```

Which does not work.  If I remove the displayChapter, it works no problem but when trying to make it jump to specific chapter it does not work.  Can anyone give any guidance, or is this a bug?

**Comment by yinhaibo** [comment]
I deem that you need to call after the ebook has load successfully.
```
reader.book.ready.all.then(function(){
  reader.book.displayChapter(3);
});
```
