### ISSUE TITLE
Require('epubjs') in node.js

### ISSUE THREAD

**Issue by coppercash** [futurepress/epub.js#226]
I want to require **epub.js** in my node module, so I can get the HTML text output from `renderTo`.

Actually I already started to write a wrapper module, until I saw

``` javascript
    //Node
    module.exports = ePub;
```

in `base.js`

It seems you have already handled this requirement. 

But when I run

```
var window = GLOBAL;
var epubjs = require('./base.js');
```

I got `TypeError: Cannot read property 'extend' of undefined`. It seems I am supposed to load `underscore` as a dependency.

So 2 questions:
1. Do I need to wrap (which means solve all dependencies) **epub.js** if I want to require it in a node module?
2. Can I run **epub.js** without browser environment if I only want HTML text as output? 

Thanks for providing such an excellent lib.

**Comment by fchasen** [comment]
Sorry this is something that just keeps getting pushed off, but the library doesn't work well in node yet.
The v0.3 branch is better but still will have issues - mostly around loading the files for the filesystem.

**Comment by JakeHartnell** [comment]
Does anyone want to explore this more? Would be awesome if it worked in Node. : )

**Comment by adius** [comment]
+1

**Comment by JakeHartnell** [comment]
https://www.npmjs.com/package/epub.js
