### ISSUE TITLE
Thumbs up for Angular

### ISSUE THREAD

**Issue by KarinaLibrary** [futurepress/epub.js#23]
Sorry, not really an issue, but give a +1 for going the Angular.js route... 

"A framework (backbone / angular / ?) to use for our reader demo (which we suspect is going to start expanding quickly)"

**Comment by matewilk** [comment]
Hey,

Yes, there is an backbone example, but not fully implemented and with errors. I can fix them myself, but it would be nice to have at least details.html template included in the repository, or is it just an empty div ?

**Comment by androidovshchik** [comment]
Hi!
i wrote a simple library for using epubjs with angular4+
https://github.com/androidovshchik/AngularEpubViewer
i'll be glad to have feedback in issues or pull requests
