### ISSUE TITLE
[sloved] (please help) ePub.js continue reading mode ? 

### ISSUE THREAD

**Issue by duongcuong96** [futurepress/epub.js#234]
Hi! anyone please help me to how to continue reading in ePub js ? 
its always return first page when i reload
i had try this : 
     var Book = ePub({restore:true});
          Book.open("book.epub");
i can read a book but cannot continue reading it ! 
Please help me,thanks ! 
(and sorry my bad English -_-)

**Comment by duongcuong96** [comment]
Thanks for anyone cares my question ! 
after workaround,i find that i can getCfi and use gotoCfi to go to last saved cfi !

**Comment by matewilk** [comment]
How have you manage to save cfi? Are you saving it to db, cookie, store? 
If it is db, how do you keep it in sync, when the user closes the browser window?

**Comment by duongcuong96** [comment]
i save it in localStorage,just a string cfi,and after the user come back to continue reading,i just show "continue reading" box and the user just click this button to continue reading last chapter
Any ideal for better "continue reading mode" ? please let me know ! Thanks !

**Comment by fchasen** [comment]
Unfortunately this is something that is implemented in v0.3 but still is a ways off from being production ready, so closing for now.
If get a chance, please try out example here: https://github.com/futurepress/epub.js/blob/v0.3/examples/single.html

Feedback is much appreciated.

**Comment by duongcuong96** [comment]
thanks ! ill try it soon !
