### ISSUE TITLE
reader/dev.html loads indefinitely

### ISSUE THREAD

**Issue by jacksonrayhamilton** [futurepress/epub.js#239]
If I `cd epub.js` and start a development server with `python -m SimpleHTTPServer 1024`, and then visit `localhost:1024/reader/dev.html` in a browser, the spinner is displayed indefinitely.

I think this is due to the `book.ready.toc` promise never resolving. Can you please look into this?

**Comment by jacksonrayhamilton** [comment]
I believe the issue what that you were missing some scripts on that page:

```html
...
<script src="../src/pagination.js"></script>
<script src="../src/events.js"></script>
<script src="../src/locations.js"></script>
<script src="../src/shims.js"></script>
<script src="../src/storage.js"></script>
```

**Comment by fchasen** [comment]
Ah, thanks - I've switched to using `grunt watch` and should probably just remove `dev.html`.
