### ISSUE TITLE
How to disable beforeChapterDisplay event while pagination is process

### ISSUE THREAD

**Issue by yinhaibo** [futurepress/epub.js#240]
I using beforeChapterDisplay to zoom image using smartimages hook.
But there is a problem while enable pagination function. Pagination seem to call beforeChapterDisplay event while every chapter load background by pager. The current display chapter's data will be overwrite. Chapter data generate from beforeChapterDisplay event using hooks.

In my smartimages hook, I collected all image object to a list, I use to show a photo gallery while a IMG clicked. The gallery can show all images in current chapter. It works when pagination function is disabled.

I want to ask:
Is there any options for pagination to make the beforeChapterDisplay event calling will be ignore.

**Comment by fchasen** [comment]
The pagination renders just as it would on screen but hidden, so currently it need to call `beforeChapterDisplay`.

I'd suggest switching to using locations, they work almost the same way but are faster to generate and don't require require rendering the whole book.

A usage examples is at https://github.com/futurepress/epub.js/blob/master/examples/locations.html

**Comment by yinhaibo** [comment]
Yes, I got it.
I move image zoom code to img click event handler. That works very well.

And I add a showing chapter name function in renderer:chapterDisplayed listener, it works, and just called in chapter displayed, like:
Book.on('renderer:chapterDisplayed', chapterChange);

Thank you very much. 
I am trying use epub.js for my Android/iOS project using cordova.

**Comment by JakeHartnell** [comment]
> I am trying use epub.js for my Android/iOS project using cordova.

It seems like a lot of people are doing so. If someone could take a first stab at creating a guide to this on the wiki that would be greatly appreciated.
