### ISSUE TITLE
Cross origin request on EPUBJS.core.request 

### ISSUE THREAD

**Issue by bahinapster** [futurepress/epub.js#242]
Hello ,

I am trying to use this reader on chrome and android devices ,but i am facing an issue with cross origin on XMLHTTP REQUEST . so is there is any way to override this function .

otherwise i have tried to add some cross origin headers with no results .

xhr.setRequestHeader("Access-Control-Allow-Origin", "*");

**Comment by fchasen** [comment]
What error are you getting when you try to make a request cross origin?
Could you try with this book: https://s3.amazonaws.com/moby-dick/

**Comment by fchasen** [comment]
This seems to be working fine. See `basic.html` example to test with s3.
