### ISSUE TITLE
Phonegap whitelist for blob URI

### ISSUE THREAD

**Issue by voliva** [futurepress/epub.js#243]
I'm leaving this here in case it could help other people. Maybe it would be nice to check I'm not *too* wrong and put it into the documentation?

Using your library to display epubs in a phonegap/cordova app it worked in my browser, in my phone's borwser but not when it was packaged into an app (Android).

After debugging a lot, I found out that cordova doesn't accept the blob URI when Epub.js tries to load it in the iframe. Finally, I found out that in phonegap, using the white list plugin, it's required to have this line in config.xml file:
`<allow-navigation href="blob:*" />`

You can find my question in stackoverflow: http://stackoverflow.com/questions/31941634/epub-js-phonegap-not-working-because-of-blob-uri

**Comment by JakeHartnell** [comment]
Thanks @voliva, but the issue tracker is probably not the best place for this. It seems like a lot of people are using Epub.js with phonegap. Might I suggest creating a page on the wiki for Phonegap integration?

**Comment by voliva** [comment]
Sure, I haven't thought about the wiki. When I find some time I'll try to fill it :)

My apologies for dirtying the issue tracker...

**Comment by JakeHartnell** [comment]
@voliva thanks! 

No worries, we've been a little lax in maintaining it, but alas it is time to reduce clutter!
