### ISSUE TITLE
Namespace reader classes and ids

### ISSUE THREAD

**Issue by jacksonrayhamilton** [futurepress/epub.js#248]
The reader application uses very general class and id names. e.g., `#sidebar`, `.view`. If one were to drop the reader into his own website, there's a high likelihood these class names will clash with those of existing stylesheets.

This problem could mitigated by prefixing all the reader's classes and ids with a common string; e.g., `#epubjs-reader-sidebar`, `.epubjs-reader-view`. It's a little extra typing on your end to save many minutes&mdash;perhaps hours&mdash;of head-scratching for those integrating the reader.

**Comment by JakeHartnell** [comment]
+1

**Comment by JakeHartnell** [comment]
If anyone still feels strongly about this, the appropriate place to make a PR is here: https://github.com/futurepress/epubjs-reader
