### ISSUE TITLE
which js libs to include for .epub? "zip not defined"

### ISSUE THREAD

**Issue by isimmons** [futurepress/epub.js#25]
Hi,
I'm trying out the demo using one of my own .epub books. It seems to recognize it is a zipped up .epub file and be attempting to unzip it but I get the error "Uncaught ReferenceError: zip is not defined" from zip.min.js.

Can you provide the documentation for how to use .epub files?

Thanks

**Comment by shenzhuxi** [comment]
I'm thinking that it may be better to keep epub.js as a simple epub parser lib and leave unzip, file storage, pagination and etc. to the application layer of the readers.

**Comment by hajarghaem** [comment]
Hi @fchasen,
I use  JSZIP to zip my unzipped epub file. But the output is not valid epub. I have all files in the output epub but when I use epubcheck for validating my epub it gives me the following errors:

ERROR(RSC-001): file.epub/file.epub(-1,-1): File 'OEBPS/image/3904.png' could not be found.
ERROR(RSC-001): file.epub/file.epub(-1,-1): File 'OEBPS/image/backoffice.jpg' could not be found.
ERROR(RSC-001): file.epub/file.epub(-1,-1): File 'OEBPS/image/cvr-cm-berichten.jpg' could not be found.
ERROR(RSC-001): file.epub/file.epub(-1,-1): File 'OEBPS/image/icon-author.png' could not be found.
ERROR(RSC-001): file.epub/file.epub(-1,-1): File 'OEBPS/image/macro-after.jpg' could not be found.
ERROR(RSC-001): file.epub/file.epub(-1,-1): File 'OEBPS/image/macro-before.jpg' could not be found.
ERROR(RSC-001): file.epub/file.epub(-1,-1): File 'OEBPS/image/pdf-output.jpg' could not be found.
ERROR(RSC-001): file.epub/file.epub(-1,-1): File 'OEBPS/image/print-centric-wf.jpg' could not be found.
ERROR(RSC-001): file.epub/file.epub(-1,-1): File 'OEBPS/image/xml-centric-wf.jpg' could not be found.
ERROR(RSC-001): file.epub/file.epub(-1,-1): File 'OEBPS/image/xml-input.jpg' could not be found.

I have all of them in my book. Could you please help me with your thought?
Thanks in advance,
Hajar
