### ISSUE TITLE
Select TOC with subitems

### ISSUE THREAD

**Issue by watf** [futurepress/epub.js#251]
Hi everyone,

I'm trying to show the subitems of the ebook, as reader.js in its full version does, but in a select instead of ul-li a (links), like promises.html

I have this code, where shamelessly I put a piece of code of reader.js, hoping it'll work and show me the subitems. It didn't, of course.

            Book.getMetadata().then(function(meta){

                document.title = meta.bookTitle+" – "+meta.creator;
                
            });

            Book.getToc().then(function(toc){

              var $select = document.getElementById("toc"),
                  docfrag = document.createDocumentFragment();

              toc.forEach(function(chapter) {
                var option = document.createElement("option");
                option.textContent = chapter.label;
                option.ref = chapter.href;

                docfrag.appendChild(option);

                var subitems;
                if(chapter.subitems.length > 0) {
                     var othercaps = document.createElement("option");
                       othercaps.textContent = chapter.label;
                        othercaps.ref = chapter.href;
                           docfrag.appendChild(subitems);
                      }
                     

              });

              $select.appendChild(docfrag);

              $select.onchange = function(){
                  var index = $select.selectedIndex,
                      url = $select.options[index].ref;
                  
                  Book.goto(url);
                  return false;
              }

            });

            Book.renderTo("viewer");

I clearly have no idea what's going on. ¿Why subitems (sub-chapters, sub-articles, whatever the book has in it) doesn't show up and gives me an error?

Thanks so much in advance.

**Comment by watf** [comment]
So nice library by the way. Your way of managing epubs is pretty brilliant.

Keep it up guys!

**Comment by watf** [comment]
¿Does anyone got an answer to this?

I could show all the chapters, but using $select.onchange only works in chapters, not sub chapters.
Thank you!

**Comment by fchasen** [comment]
Have a look at the code here, which recursively generates the TOC items: https://github.com/futurepress/epub.js/blob/master/reader_src/controllers/toc_controller.js#L9-L46

**Comment by AK0088154** [comment]
above page does not exist
https://github.com/futurepress/epub.js/blob/master/reader_src/controllers/toc_controller.js

**Comment by fchasen** [comment]
Moved to https://github.com/futurepress/epubjs-reader/blob/master/src/controllers/toc_controller.js
