### ISSUE TITLE
Problem on Android Webview

### ISSUE THREAD

**Issue by matikbird** [futurepress/epub.js#262]
Hi everyone,

I am getting this error in default browsers:
Illegal constructor TypeError: Illegal constructor
    at [object Object].getUrl (http://192.168.1.4/mobile/js/epub.min.js:3:29401)
    at [object Object].url (http://192.168.1.4/mobile/js/epub.min.js:2:12589)
    at [object Object].displayChapter (http://192.168.1.4/mobile/js/epub.min.js:3:12710)
    at [object Object].displayChapter (http://192.168.1.4/mobile/js/epub.min.js:2:4217)
    at [object Object].startDisplay (http://192.168.1.4/mobile/js/epub.min.js:2:3079)
    at http://192.168.1.4/mobile/js/epub.min.js:2:2864
    at p (http://192.168.1.4/mobile/js/epub.min.js:1:19428)
    at o (http://192.168.1.4/mobile/js/epub.min.js:1:19347)
    at u (http://192.168.1.4/mobile/js/epub.min.js:1:20077)
    at e (http://192.168.1.4/mobile/js/epub.min.js:1:15100)

I load epub.min.js > zip.min.js > reader.js, and everything works fine in chrome and other browsers.. But I really need to work in default Android browsers.

I tested the example in several devices, and in every one i'm getting the same error (i'm using weinre to debug)

Note: The book is loaded (at least, it shows the chapters), but i'm not sure why this is happening, the screen stays blank, and of course.. the error.

I'd appreciate any ideas, thanks

**Comment by fchasen** [comment]
That is a strange error! What version of Android is this on?

**Comment by watf** [comment]
So far, I tried in several devices, starting from 4.0.3 ICS 'till 4.4. Didn't check on 5.0 yet, I am more worried about the older versions.

The curious part is that in Chrome/Opera/other webkits, works fine, but in default browser (webkit 534.30) load the chapters/metadata, but not the text. So, it is not a zip problem. I've changed the styles (the closed issues were a great help here) but no. The text is floating there, somewhere in the DOM I presume.

You can check out in your phone, I've uploaded an example for to not complicate the question:
 · http://m.unwritten.in

**Comment by watf** [comment]
Fred, by chance.. ¿do you have an example that you know is working in default browsers on Android?

I've checked out every single issue, every example (android-patch.html is outdated by the way, there are files that no longer exist in the last master)

I am only including epub.min.js, zip.min.js and render.js (for bookmarks, and that stuff).
¿Am I missing a script?

**Comment by fchasen** [comment]
The android patch shouldn't be needed anymore as I've added that switch into master.

Looks like the issues is the `new Blob` constructor which isn't supported in older Android version and the deprecated BlobBuilder api needs to be used: http://stackoverflow.com/questions/15293694/blob-constructor-browser-compatibility

Can you try including this polyfill? https://github.com/eligrey/Blob.js

**Comment by JakeHartnell** [comment]
No discussion in almost two years, closing.
