### ISSUE TITLE
build-directory missing

### ISSUE THREAD

**Issue by trondhuso** [futurepress/epub.js#264]
It could be that I have misunderstood a few things, but when I look into the examples and also the readme-file, it says the epub.min.js-file is to be found in the build-directory.
In the git-repository there isn't a build-directory.

Could you describe how to set up this? It looks very promising, and I want to try it in a project.

Trond

**Comment by fchasen** [comment]
We removed the build folder, as you can generate it by running `grunt` or `grunt watch`
(You may need to run `npm install` first)

I think that is confusing for now, so I'll probably add it back again and deal with merge conflicts until we setup something better.

**Comment by trondhuso** [comment]
Hi Fred, Thanks for the follow up. 
The confusing part now is with the involvement of nmp - which I kind of feel is related to node.js - confuses me. 
I'll try the grunt command you are referring to.

**Comment by fchasen** [comment]
Build directory is back in the latest master
