### ISSUE TITLE
Chapter not utilizing `withCredentials` setting

### ISSUE THREAD

**Issue by jacksonrayhamilton** [futurepress/epub.js#266]
If I set the `withCredentials` setting to `true`, I expect all AJAX requests to have that setting. But `Chapter` does not use the setting [here](https://github.com/futurepress/epub.js/blob/d730673b9cac6e85e31439dba93a0326d076259c/src/chapter.js#L32) (it should be passed as the third parameter).

**Comment by fchasen** [comment]
Thanks, will update.
