### ISSUE TITLE
receiving general error

### ISSUE THREAD

**Issue by trondhuso** [futurepress/epub.js#267]
Using this code:

<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Hornfels bok</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <meta name="apple-mobile-web-app-capable" content="yes">

                
                
        
        <script src="js/build/epub.min.js"></script>
        

		
		<script src="js/libs/jszip/jszip.min.js"></script>

        <style type="text/css">

          body {
            overflow: hidden;
          }

          #main {
            position: absolute;
            width: 100%;
            height: 100%;
          }

          #area {
            width: 80%;
            height: 80%;
            margin: 5% auto;
            max-width: 1250px;
          }

          #area iframe {
            border: none;
          }

          #prev {
            left: 40px;
          }

          #next {  
            right: 40px;
          }

          .arrow {
            position: absolute;
            top: 50%;
            margin-top: -32px;
            font-size: 64px;
            color: #E2E2E2;
            font-family: arial, sans-serif;
            font-weight: bold;
            cursor: pointer;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
          }

          .arrow:hover {
            color: #777;
          }
           
          .arrow:active {
            color: #000;
          }
        </style>
        
         <script>
            "use strict";
            
            var Book = ePub("epub/Hornfels.epub");
            
        </script>
    </head>
    <body>
        <div id="main">
          <div id="prev" onclick="Book.prevPage();" class="arrow">‹</div>
          <div id="area"></div>
          <div id="next" onclick="Book.nextPage();"class="arrow">›</div>
        </div>

        <script>            
            
            Book.renderTo("area");

        </script>
    </body>
</html>

I receive this error message:

error { target: <img>, isTrusted: true, currentTarget: <img>, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1441056777292147, originalTarget: <img>, explicitOriginalTarget: <img>, NONE: 0 }

The Epub is created using InDesign. 

I found this in the content.opf-file:
package xmlns="http://www.idpf.org/2007/opf" xmlns:dc="http://purl.org/dc/elements/1.1/" unique-identifier="bookid" version="2.0"

Trond

**Comment by fchasen** [comment]
Do other epubs work? It might be an issue with rendering an epub 2.0. We only really support epub 3.
