### ISSUE TITLE
Hide the left arrow on the first page and the right arrow on the last page.

### ISSUE THREAD

**Issue by lionel-m** [futurepress/epub.js#27]
It would be nice.

Thanks

**Comment by jbhorsewriter7** [comment]
Please add this!!!

**Comment by DavidPetit** [comment]
Hi!

Are there some mews about this?

**Comment by JakeHartnell** [comment]
Closing this as it belongs in the Reader repo: https://github.com/futurepress/epubjs-reader/issues/1
