### ISSUE TITLE
2 pages landscape mode Issue

### ISSUE THREAD

**Issue by bahinapster** [futurepress/epub.js#270]
Hello ,

I have an issue with landscape mode on Ipad where i still get only one page instead of two pages

**Comment by MarkisLt** [comment]
Most likely it's css problem

**Comment by bahinapster** [comment]
@MarkisLt  I have tried many solutions with no solution , do you have the media query for ipad ?

**Comment by fchasen** [comment]
Could you try setting `minSpreadWidth: 768px` (or less) in your book settings.

Just seeing now that this isn't mentioned in the documentation, will update.
https://github.com/futurepress/epub.js/blob/master/src/book.js#L18

**Comment by bahinapster** [comment]
@fchasen  Thank you so much it works after changing it into 768px

**Comment by fchasen** [comment]
Great, that might make a better default then `800px` then. Close this issue when I update and document.

**Comment by bahinapster** [comment]
Hello Again , i am facing a new issue after changing the value from Integer 800 into  String 800px

It's start to split into 2 pages in all devices !!!

**Comment by fchasen** [comment]
Oh yes, that should be an integer not a string, so just *768*. I'll add that to the documentation as well.

**Comment by Sofianio** [comment]
Hi, i think this isn't the right place but i had the same pb, and now i do get the 2pages but not in the right order with RTL books,
how do i fix this please.
Thank you

**Comment by fchasen** [comment]
@Sofianio, could you create a new issue for that?
