### ISSUE TITLE
Problem with some arabic books 

### ISSUE THREAD

**Issue by bahinapster** [futurepress/epub.js#271]
Hello ,

I have an issue with some books where the reader can't recognize the toc and the reader crash 

exemple of books : http://www.ibooks.ae/?download=%D8%A5%D9%82%D8%A7%D9%85%D8%A9%D8%A7%D9%84%D8%B5%D9%84%D8%A7%D8%A9

did any one faced this issue ?

**Comment by bahinapster** [comment]
@fchasen  can you confirm this please ?

**Comment by fchasen** [comment]
No issues for me in Chrome 45.

**Comment by bahinapster** [comment]
weird :/   , i have this problem with almost all the books on http://ibooks.ae/ 

+ i can't open zipped epub directly

PS :  devices used :  Iphone + Ipad

**Comment by fchasen** [comment]
I'll give it a test on iOS. Did you see this happening in the emulator or just on device?

**Comment by bahinapster** [comment]
Both

2015-09-09 4:48 GMT+02:00 Fred Chasen <notifications@github.com>:

> I'll give it a test on iOS. Did you see this happening in the emulator or
> just on device?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/futurepress/epub.js/issues/271#issuecomment-138760913>
> .
>



-- 
Ibrahim MESLEM

Microsoft Student Partner & Coca Cola Scholarship Alumni

*Exchange Manager* @ *O*ut*G*oing e*X*change ;
*LC* in Babez | *AIESEC* in Algeria

Mobile: +213 698 888 033

Skype:  bahi.meslem

**Comment by JakeHartnell** [comment]
Any updates on this? @bahinapster 

Is this still an issue with the v0.3 branch?
