### ISSUE TITLE
BUG-Cannot load ebook from externalData directory in new version

### ISSUE THREAD

**Issue by yinhaibo** [futurepress/epub.js#272]
In current new version, the reader cannot load ebook from external directory, but previous version can works.
I am using current version(2015.9.3) to update my old code, ebook will cannot load ebook from external directory.

Environment:
Android: Cordova + epub.js
Error:
EPUBJS.Book.prototype.loadPackage   <-- Error position in book.js
Could not load book at: META-INF/container.xml <-- Error message in console
file:///android_assets/www/books/progit/ <-- OK, in app directory, they works.
file:////storage/sdcard1/Android/data/cn.vbook/files/default/... [My new prosition] <--Cannot load and the error object contain container.xml file in packageXml.catch(function(error) {});.

I need read book in external data directory for video, so I donot how to fix it.
Please give me some hits, thanks very much.

**Comment by yinhaibo** [comment]
Yes, the problem exist in current release also.
I found some change in core.js file.
```
@@ -50,14 +50,14 @@ EPUBJS.core.request = function(url, type, withCredentials) {
        if(type == "binary") {
                xhr.responseType = "arraybuffer";
        }
        xhr.send();
        function handler() {
                if (this.readyState === this.DONE) {
-                       if (this.status === 200 || this.responseXML ) { //-- Firefox is reporting 0 for blob urls
+                       if (this.status === 200 || thhis.response || this.responseXML) { // || this.responseXML-- Firefox is reporting 0 for blob urls
                                var r;
```

The reason is this.status equal 0 while load local file using file:// path in cordova environment. So, I change current code to:
```
if (this.status === 200 || this.response || this.responseXML) { 
```

If anyone have more advice, please tell me. And I don't know that what problem will lead into.

**Comment by fchasen** [comment]
Ah, interesting that it returns 0. Might just check for `status === 0` as well.

Good discussion of the issue here: http://simonmacdonald.blogspot.com/2011/12/on-third-day-of-phonegapping-getting.html

**Comment by peeter-tomberg** [comment]
I ran into this problem also, local files are served with the status of 0.

Related stuff I found:
https://bugzilla.mozilla.org/show_bug.cgi?id=331610
https://github.com/winjs/winjs/issues/208

**Comment by fchasen** [comment]
Updated in v0.2.10

**Comment by CharanjeetTuteja** [comment]
Hello,
I cant access file from internal storage i.e.,
file:////storage/emulated/0/epub1.epub

it is working for 
file:///androi_asset/epub1.epub
Can any one guide for the same? How to do this?

**Comment by hesampour** [comment]
I have the same problem. did you fins any solution?

**Comment by chiemekailo** [comment]
Did anyone get a solution yet?

My case differs slightly, when load from `file:///android_asset/ePub-folder-path/` it loads fine with other assets `(css: <link href=“css/style.css”>, img: <img src=“img/my_photo.jpg”)`, but when loading from documents directory `file:///storage/emulated/0/ePub-folder-path/` the xhtml text loads fine, **but the resources (css,img) do not load**.

**How can I get around this?** I know about running a server **_(eg. GCDWebServer for iOS)_** from the document directory of the device, but I have no experience to tie it back to the ePubJS instance to properly serve the resource files.
