### ISSUE TITLE
Epub.js leaks to the global namespace

### ISSUE THREAD

**Issue by peeter-tomberg** [futurepress/epub.js#273]
Example: 

```html
<script>var _ = [];</script>
<script src="http://futurepress.github.io/epub.js/build/epub.min.js"></script>
<script>console.log(_);</script>
```

We're using the library lodash which is defined in the global namespace with _
After including epub, the variable is overwritten and breaks our application.

**Comment by fchasen** [comment]
There is a build version that doesn't include underscore here: https://github.com/futurepress/epub.js/blob/master/build/epub_no_underscore.js

But I'll update to use http://underscorejs.org/#noConflict
