### ISSUE TITLE
Pagination error:Total pages have different result in first load and pagination

### ISSUE THREAD

**Issue by yinhaibo** [futurepress/epub.js#274]
I create a EPUB directory, which have only a chapter and with some text, images and videos.
In simulator iPhone 6, the chapter first load have only 3 pages, and after pagination, total pages is 4 pages.
I track renderer.js mapPage function. I found some strange problem:
1. the renderer of current display chapter and the hidden renderer of pagination have different render result(different page count).
2. the mapPage does not check non text node in html. there be **lack one page** while the chapter end with a non-text element, and just the first node on new page, such as a image.

I checkout renderer's style, I got same result:
[First load on startup]
[Log] -webkit-transform: translate(0px, 0); overflow: hidden; width: auto; height: 569.421875px; -webkit-column-axis: horizontal; -webkit-column-fill: auto; -webkit-column-width: 376px; -webkit-column-gap: 80px; (console-via-logger.js, line 173)
[Pagination]
[Log] -webkit-transform: translate(0px, 0); overflow: hidden; width: auto; height: 569.421875px; -webkit-column-axis: horizontal; -webkit-column-fill: auto; -webkit-column-width: 375px; -webkit-column-gap: 80px; (console-via-logger.js, line 173)

(https://github.com/futurepress/epub.js/blob/master/src/renderer.js#L601)
this.layout.colWidth= 375(for first load), **1740** (for pagination)
this.layout.spreadWidth=455, 1820
renderer.doc.documentElement.clientHeight = 569, **0**(for pagination)

**Comment by yinhaibo** [comment]
It took me 4 days to find out, today, I notice there is a small difference in my Log:
**-webkit-column-width:376px**
**-webkit-column-width:375px**
There is 1 pixel between them? Why!!!
I changed following code in:
(https://github.com/futurepress/epub.js/blob/master/src/render_iframe.js#L128)
```
-       this.width = this.iframe.getBoundingClientRect().width || width;
-       this.height = this.iframe.getBoundingClientRect().height || height;
+       this.width = width || this.iframe.getBoundingClientRect().width;
+       this.height = height || this.iframe.getBoundingClientRect().height;
```
(https://github.com/futurepress/epub.js/blob/master/src/book.js#L348)
```
-       renderer.initialize(hiddenEl);
+       renderer.initialize(hiddenEl, width, height);
```

then, it seems ok in pagination.
ONLY ONE PIXEL MAKE BIG DIFFERENCE??

The second problem, I try to add a checkNonText function to calc page position in 
(https://github.com/futurepress/epub.js/blob/master/src/renderer.js#L601)
another question is:
** Why need to re-get XPath from document in PUBJS.Chapter.prototype.cfiFromRange function?**
The node is from DOM tree, I think that it is a normal node or range, why need to research from DOM tree in this function?
(https://github.com/futurepress/epub.js/blob/master/src/chapter.js#L148)

**Comment by fchasen** [comment]
Thanks for tracking this down, column width is only a suggestion in Chrome so if the widths are rounded and don't match up it can make the pages a different length. Seems like a bug if hidden renderer doesn't respect that width - as you found.

**Comment by fchasen** [comment]
The double xpath is so that if something changed in the displayed document dom, we can fuzzy match on the original document and try to find the true CFI position.
