### ISSUE TITLE
2 pages for RTL books

### ISSUE THREAD

**Issue by Sofianio** [futurepress/epub.js#276]
Hi, i do get the 2pages when i set the minSpreadWidth (although i couldn't get it to separate landscape from portrait) but not in the right order with RTL books,
how do i fix this -set the paragraphs (pages) from Right to Left- please.
Thank you.

**Comment by fchasen** [comment]
Can you take a look at the OPF file in your epub and see if the `direction` metadata is set to `rtl`?

Otherwise you can call `book.render.setDirection('rtl')`

**Comment by Sofianio** [comment]
Sorry for the late response but where exactly do i put `book.render.setDirection('rtl')` ?

**Comment by Sofianio** [comment]
The thing is that i can set the horizontal container's CSS to RTL, but the "next page" won't scroll properly (it scrolls the wrong way) therefore not showing the next page.

**Comment by fchasen** [comment]
Yes, make sure to called it before renderTo. Ideally their should be the attribute `page-progression-direction="rtl"` in the `<spine>` tag in the epub's opf file.

**Comment by Sofianio** [comment]
I have done as you suggested (added the attribute `page-progression-direction="rtl"` in the `<spine> ` tag and `book.render.setDirection('rtl')` before `renderTo()`) but there was no result (blank page).

**Comment by fchasen** [comment]
RTL seems to be working fine in my tests. Not sure if this was specific to a certain epub.
