### ISSUE TITLE
How to get the current selection cfi?

### ISSUE THREAD

**Issue by benson-jala** [futurepress/epub.js#277]
Hi,
I tried with currentlocationcfi, generateCfiFromElement, generateCfiFromRangeAnchor to get the cfi.
These methods return only one cfi value based on where the tap occurs.
How to get the cfi for selection of text.

**Comment by fchasen** [comment]
You can listen to `book.on('renderer:selected', function(range){ })` to get the selection when it happens.

**Comment by benson-jala** [comment]
book.on('renderer:selected', function(range){ })
range is an object with anchorNode, baseNode, extentNode etc.

epubcfi.generateCfiFromRange(range, book.renderer.currentChapter.cfiBase);
the above method needs a range object which contains startContainer, endContainer etc..

how to deal with this error?

**Comment by timbod7** [comment]
This code works for me:

```
  book.on("renderer:selected", function(range) {
    var epubcfi = new EPUBJS.EpubCFI();
    var cfi = epubcfi.generateCfiFromRangeAnchor(range, book.renderer.currentChapter.cfiBase);
    console.log("selected:", cfi );
  });
```

**Comment by anatoly314** [comment]
And how can this be done on v0.3?

**Comment by vmartins** [comment]
> And how can this be done on v0.3?

```js
import { EpubCFI } from 'epubjs'

const epubcfi = new EpubCFI(range, your.cfiBase)
const cfi = epubcfi.toString()
console.log("selected:", cfi)
```

https://github.com/futurepress/epub.js/blob/5c7f21d648d9d20d44c6c365d164b16871847023/src/epubcfi.js#L26
