### ISSUE TITLE
percentageFromCfi always return 0

### ISSUE THREAD

**Issue by FelipeBB** [futurepress/epub.js#278]
Hi, the title explain everything :), here is the example:

var currentLocation = book.getCurrentLocationCfi();
var currentPage = book.locations.percentageFromCfi(currentLocation);

currentPage is 0 no matter what, I'm testing inside crosswalk embedded browser in a android device.
Oh , and thanks, epub.JS is a really nice project. :+1: , I'm using it in my final project at University and it's being lifesaver to me until now, thanks again.

**Comment by fchasen** [comment]
Did you generate the books locations first?

We don't do it automatically as it requires loading every page of the book and is somewhat resource intensive.

This example show generating and saving the locations to localstorage: https://github.com/futurepress/epub.js/blob/master/examples/locations.html

**Comment by FelipeBB** [comment]
Hi fchasen, you are right, i forgot to generate book location, now it's working!
Cheers
