### ISSUE TITLE
add a method to get the HTML content from a CFI range

### ISSUE THREAD

**Issue by myguidingstar-zz** [futurepress/epub.js#281]

**Comment by fchasen** [comment]
This would be amazing. 
Will be a large project but excited to find time for this on the roadmap.

**Comment by LordKayBanks** [comment]
@fchasen 
has this method been added yet?

**Comment by fchasen** [comment]
This is possible with v0.3

```js
var book = ePub("https://s3.amazonaws.com/epubjs/books/moby-dick/OPS/package.opf");
book.ready.then(function(){
  book.getRange("epubcfi(/6/14[xchapter_001]!/4/2,/2/2/2[c001s0000]/1:0,/8/2[c001p0003]/1:663)").then(function(range) {
    console.log(range.toString());
  });
});
```

**Comment by Janglee123** [comment]
just curious, how to get a position of the selected text.

**Comment by udusharla** [comment]
> just curious, how to get a position of the selected text.

`this.book.rendition.on("selectedRange", (range) => console.log(range.toString()));
`
