### ISSUE TITLE
js errors running the demo 

### ISSUE THREAD

**Issue by judell** [futurepress/epub.js#285]
Demo link: http://futurepress.github.io/epub.js/reader/

Result:

http://futurepress.github.io/epub.js/reader/js/libs/jquery.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
reader.min.js:1 Uncaught ReferenceError: jQuery is not defined
futurepress.github.io/:28 Uncaught ReferenceError: ePubReader is not defined

**Comment by fchasen** [comment]
Thanks for filling an issue, just updated it.

**Comment by judell** [comment]
Thanks!

**Comment by onigetoc** [comment]
Most of the demo do not work well online
