### ISSUE TITLE
epub.js ajax read

### ISSUE THREAD

**Issue by epubreader** [futurepress/epub.js#287]
how to use ajax to render epub book?

I want to use java parser epub, and then use epub.js to render it by ajax, how to do it?

**Comment by fchasen** [comment]
I'm sorry, I'm don't understand the question. Epub.js should be used to parse the epub if you intend to render it using epub.js.

**Comment by eimhee** [comment]
My meaning is that I don't want to use Epub.js to parse the epub, but I only want epub.js to render the epub.
I think you can use nodejs to parse the epub in server side, and then render the epub book by epub.js in client side

**Comment by Bigismall** [comment]
You don't need render EPUB file, because browser is dooing it (it is HTML). 
You can easly extract EPUB file (with any ZIP archiver), and see the contents. Those are HTML assets + metadata files

**Comment by fchasen** [comment]
You can now pass Epub.js a [Web Pub Manifest](https://github.com/readium/webpub-manifest) you have created from the parsed epub and it will render the content.
