### ISSUE TITLE
Rails and epub.js

### ISSUE THREAD

**Issue by Patrax** [futurepress/epub.js#289]
I've been struggling with this for way too long. Has anyone successfully used epub.js with rails?
I'm getting a lot of route errors, eg:

`ActionController::RoutingError (No route matches [GET] "/read/name-of-book/META-INF/container.xml"):`

What are the essentials to get the epub reader to work properly? If I can't serve an epub from the public directory in my webapp what are my chances of making it work with AWS S3? Should I just disable turbolinks for routing to work?

PS: Sorry about the ambiguous 'issue', I'm just a bit overwhelmed and any help or nudge in the right direction would help a lot.

**Comment by fchasen** [comment]
Sorry to hear you're having issues, epub.js will work great with Rails but going to need some more information to help. 

First which version of Rails are you using?

Is the book is present in the folder `assets/public/read/name-of-book/`? Is it a compressed (.epub) or unzipped?

You might need to switch to using `config.serve_static_assets = true` in your environments  files: https://support.anynines.com/entries/25843538-Rails-Asset-Pipeline-Serve-static-assets-from-the-public-directory

The forum or gitter might also be a good places to reach out for help.

**Comment by Patrax** [comment]
Thank you so much @fchasen ! `config.serve_static_files = true` did the trick. I was so confused why my production environment was misbehaving. Btw, I'm currently using unzipped epubs for my initial attempts and will go onto trying with compressed ones now.

**Comment by fchasen** [comment]
Great. I'd stick with the unzipped files if possible, the load quicker and take up less ram.
