### ISSUE TITLE
Pagination Demo does not work

### ISSUE THREAD

**Issue by Sriram-Ramaswami** [futurepress/epub.js#291]
Hi,
The pagination demo does not seem to work on the site.

Also the pageList is returning 0 for almost all books that I have tested for 

Can you please take a look?

Thanks,
Sriram

**Comment by fchasen** [comment]
Will do, thanks for filing an issue. I'd suggest checking out the locations example instead as it is a much quicker way to generate book position.

**Comment by Sriram-Ramaswami** [comment]
I have tried that out. But how do I calculate the number of pages in a particular book. navigating through percentage is fine but we need page numbers too? Any insight on when the pagination will be up and running?

**Comment by fchasen** [comment]
Sorry I know I need to better document the locations api but you can use the locations number as page numbers (as the Kindle does). I'll make sure the pagination example is working by the end of the week but highly recommend not using it as it renders the entire book which is extremely resource intensive.

**Comment by Sriram-Ramaswami** [comment]
Thanks for the info. If you can document locations a bit it would be great. I have tried using location number as the page number which again gives me a dilemma. I see that the default character break is 150. Which leaves me thousands of locations for a book. How do I actually get the page number from that?

**Comment by fchasen** [comment]
It's not going to match up perfectly for every book but I've found that 1600 gives a pretty close approximation to 1 location per displayed page on a mobile device.

**Comment by hz0324** [comment]
Pagination Demo is still not working

**Comment by fchasen** [comment]
Removed
