### ISSUE TITLE
Links on TOC page do not work since version 0.2.8

### ISSUE THREAD

**Issue by mellenbe** [futurepress/epub.js#293]
It appears that since version 0.2.8 the links on the table of contents page do not work anymore.

The EPUBJS.replace.hrefs method (replace.js) reads the value stored in renderer.render.window.location.href and possibly creates a path for the target (variable "relative") given as a parameter to the method book.goto in link.onclick:

link.onclick = function(){
	book.goto(relative);
	return false;
};

The value stored in renderer.render.window.location.href has changed between versions 0.2.7 and 0.2.8. As a result the generated link targets cannot be found.

Here is a comparison of the values for the first link "Title Page" on the TOC page in the example files basic.html and contained.html:

examples/basic.html:

0.2.7:
renderer.render.window.location.href = http://localhost:8081/books/moby-dick/OPS/toc-short.xhtml
var relative = /books/moby-dick/OPS/titlepage.xhtml

since 0.2.8:
renderer.render.window.location.href = http://localhost:8081/examples/basic.html
var relative = /examples/titlepage.xhtml

examples/contained.html:

0.2.7:
renderer.render.window.location.href = blob:http%3A//localhost%3A8081/57d3edfd-6cca-4d08-a41b-0ba67d216e5c
var relative = titlepage.xhtml
 
since 0.2.8: 
renderer.render.window.location.href = http://localhost:8081/examples/contained.html
var relative = /examples/titlepage.xhtml

"/examples/titlepage.xhtml" does not exist and so the link target cannot be opened.

**Comment by fchasen** [comment]
Thanks for the detailed report, should be a quick fix.
