### ISSUE TITLE
book.locations.generate() parameter ignored

### ISSUE THREAD

**Issue by timbod7** [futurepress/epub.js#294]
The locations example 

https://github.com/futurepress/epub.js/blob/master/examples/locations.html#L135

passes in an integer that is intended (I think) to set the size of the location sections, however the code:

https://github.com/futurepress/epub.js/blob/master/src/locations.js#L17

appears to ignore this value?

**Comment by Sriram-Ramaswami** [comment]
I saw that this issue was happening too. The issue is because the input parameter is not used at all in the generate method. I managed to get around it by setting Book.locations.break attribute to the value that I wanted. Try and see if that works

**Comment by fchasen** [comment]
Ugh, I'll get this fixed asap.
