### ISSUE TITLE
epub load empty element error in html

### ISSUE THREAD

**Issue by yinhaibo** [futurepress/epub.js#296]
This is a good project, I very appreciate that.
I found something goes wrong while I make a empty html element for epub html.
For example:
I wrote html like this:
```
<head>
<script src="js/p5.js"></script>
</head>
<body>
<div class="contents">
</div>
</body>
```
The epub will load this file as this:
```
<head>
<script src="js/p5.js">
</head>
<body>
<div class="contents">
</div>
</body>
</script>
```
and the body will no element in it.

And, If empty div or other element will make same error.
I don't know How to make this file work while need to include some javascript?

**Comment by fchasen** [comment]
Fixed by #290
