### ISSUE TITLE
Documentation is defective

### ISSUE THREAD

**Issue by pkosenko** [futurepress/epub.js#298]
Either documentation is defective, or epubjs doesn't work.  I followed instructions on the readme.md page and got NOTHING.

I think that documentation of the library is sorely substandard.  It seems to rely on "examples" that are not explained.

<h1>EBook Reader</h1>
<div id="book-div">&nbsp;</div>
    <script>
    "use strict";
     var Book = ePub("pg1023-images.epub");
     // var $el = document.getElementById("book-div");
     Book.renderTo("book-div");
</script>

**Comment by fchasen** [comment]
I tend to think examples are the best way to get started, but I completely agree that our documentation is lacking. It's something we are actively trying to improve, particularly the getting started information. People reaching out helps me put that document together so thanks and bare with us!

As the epub is archived (.epub), did you include jszip? You can grab it from the cdn here: https://cdn.jsdelivr.net/jszip/2.5.0/jszip.min.js

Did any errors show up in the console?

**Comment by pkosenko** [comment]
I got it working.  There were a couple issues.  One is related to epub.js and one to server configuration.

Adding in the zip library makes sense if you understand that the code has to unzip an .epub archive.  But adding a zip library is not  mentioned in the documentation, and it isn't necessarily  obvious that it isn't already included.  

I only gave a quick look to the epub.js file and noticed that the  parse() method is NOT in it.  But you never know how things are  interacting until someone TELLS you (or you dive into the underlying library).  So documentation  should mention including the zip.min.js file is necessary (I referenced the one that is included in the github download "libs" folder).

There was actually no error in the console when I first tried without  the zip.min.js file. If something was missing, you would think that  there would be an error message, but there wasn't.

When I added a reference to "zip.min.js", I got an error.

    <script src="scripts/epub.js"></script>
    <script src="scripts/libs/zip.min.js"></script>

Error:

"NetworkError: 404 Not Found - http://localhost:22273/epubjs/pg1023- images.epub"

You might want to add this for people who are using Internet Information Server (I have multiple setups but just happen to be using this one now):

IIS Express server was not configured to deliver up the *.epub mime type.  Believe it or not, I came across the missing mime type error when I first tried serving .json files on IIS Express.  Go figure  why JSON was not in the long list of acceptable mime types. .epub not being there at least makes more sense, since people are not normally delivering .epub files.

I am testing things on my local machine using localhost.  I am using  WebMatrix on Windows 7, and WebMatrix uses Internet Information Server  Express as it's web server. However, the same mimetype issue would be present if using regular full IIS.  So you might want to record the matter in case people are testing/delivering on Internet Information Server.

http://www.chambaud.com/2013/07/09/iis-express-adding-mime-types/

Added the following to the server's "ApplicationHost.config" XML file in the "staticContent" section:

<staticContent . . . >
    <mimeMap fileExtension=”.epub” mimeType=”application/epub+zip” />
</staticContent . . . >

**Comment by pkosenko** [comment]
Okay . . . now that I have got it going . . . maybe I can contribute something to documentation where it is necessary . . . as I get further along with things.

**Comment by fchasen** [comment]
Hummm, this line https://github.com/futurepress/epub.js/blob/master/src/unarchiver.js#L10 should throw an error if zip lib isn't present. I'll investigate it a bit.

**Comment by pkosenko** [comment]
By the way, I also noticed that the Moby Dick example was not working on my Windows Internet Information setup because the extracted epub book has mimetypes that are not defined in IIS Express.

You have to add the following to the IIS Express "applicationhost.config":

        <staticContent . . . >
            <mimeMap fileExtension=".ncx" mimeType="text/xml" />
            <mimeMap fileExtension=".opf" mimeType="text/xml" />
            <mimeMap fileExtension=".xhtml" mimeType="application/xhtml+xml" />
        </staticContent . . . >
