### ISSUE TITLE
How to call EPUBJS.EpubCFI.prototype.functionName

### ISSUE THREAD

**Issue by kewal07** [futurepress/epub.js#299]
I am able to call "EPUBJS.Book.prototype.functionName", ie., i can call prototype functions of Book but i am not able to call prototype functions of the EpubCFI. What i want to do is highlight a piece of text. To select text i use the below code but i am not able to change color/add background highlight color to the selected text:
```javascript 
Book.on("renderer:selected", function(selectedText) {
    temp_highlight=selectedText.toString();
    //Highlight code ??
    console.log(selectedText.toString());
  });
```
Any help would be appreciated? 

I tried using
```javascript  
EPUBJS.Hooks.register("selected").highlight = function(callback, renderer){
    // EPUBJS.core.addScript("js/libs/jquery.highlight.js", null, renderer.doc.head);
    var s = document.createElement("style");
    s.innerHTML =".highlight { background: yellow; font-weight: normal; }";
    renderer.render.document.head.appendChild(s);
    if(callback) callback();
  }
``` 
but could not get it working. Any help please

I also tried looking into https://github.com/futurepress/epub.js/blob/gh-pages/examples/annotator.html but could not get it working.

**Comment by kewal07** [comment]
I figured something out. The below works:
```javascript
var epubcfi = new EPUBJS.EpubCFI();
var mark = epubcfi.createMarker();
```
It creates a span element. Now i add bgcolor to it 
```javascript
mark.setAttribute("style","background:yellow");
```
And then add the marker like below.
```javascript
epubcfi.addMarker();
```
However, i get the error: 
```javascript
Uncaught TypeError: Cannot read property 'steps' of undefined 
```
Lines where error occurs:
```javascript
// Get the terminal step
  lastStep = cfi.steps[cfi.steps.length-1];
```

**Comment by fchasen** [comment]
Highlighting the selected text is going to be tricky at the moment, but is possible. 

I'd suggest using Rangy Highlighter module https://github.com/timdown/rangy/wiki/Highlighter-Module
to highlight the range returned by `renderer:selected`. I'll try to get an example up in the next few days.

This process should get easier in the next couple of months as we are working with Hypothes.is to support Epub annotations.

**Comment by kewal07** [comment]
Hi. I tried with Rangy and was able to highlight.

**Comment by gimox** [comment]
can you post an example of code with rangy?

**Comment by alcfeoh** [comment]
Any update on this? It's a very interesting feature. I tried to use addMarker() as well with no success.
