### ISSUE TITLE
How to detach annotations?

### ISSUE THREAD

**Issue by pkosenko** [futurepress/epub.js#302]
I am having trouble figuring out how to DETACH annotations from the Moby Dick example.  I can create them, but I can't remove them.  There is a hypothesis.js plugin in the "reader/js/plugins" folder (and highlight.js in the "libs/extension" folder), but I haven't yet figured out how it is working yet.
![annotate_detach](https://cloud.githubusercontent.com/assets/4556807/10779279/cfdc6918-7ceb-11e5-8774-258e8aab818a.jpg)

**Comment by fchasen** [comment]
That is an excellent point, there should probably be a little [x] button on the sidebar to do that.
Annotation are a work in progress, but we just received a grant from hypothes.is so there should be big improvements for them coming in the next 2 months.

**Comment by pkosenko** [comment]
Yes, an [x] on the sidebar would work, in the left margin of the annotation line.  I have been checking out (in both senses . . . common English and github) Jake Hartnell's new Hypothesis code, and that isn't there yet.  So you might want to pass that on to him.  It looks like he works for Hypothesis (a contributor on their github repository)?

**Comment by JakeHartnell** [comment]
@pkosenko checkout https://github.com/futurepress/epub.js/pull/309. It should be coming along.

**Comment by sameervaghela2121** [comment]
`rendition.remove(cfiRange, "highlight")`
