### ISSUE TITLE
Not load epub with external script

### ISSUE THREAD

**Issue by minixT** [futurepress/epub.js#305]
Hi,
I was trying to open epub file that use jquery library that is included using version from the cdn server. Unfortunately, library doesn't load this epub and iframe that was created is empty. When I include locale version of that script everything works correctly.

**Comment by fchasen** [comment]
Would there be anyway to make a simple example epub for me to test?

**Comment by minixT** [comment]
Here is an example: https://www.dropbox.com/s/utzitryc214723c/epub.zip?dl=0

**Comment by fchasen** [comment]
Thanks, I'll take a look.

**Comment by fchasen** [comment]
Fixed by #316.
