### ISSUE TITLE
Fixed layout two columns

### ISSUE THREAD

**Issue by 127** [futurepress/epub.js#307]
Is there any convinient way to show two columns for fixed layout?
For example this one shows only one column:
```
var Book = ePub("http://127.ru/tmp/book/", {
              spreads: true, 
              fixedLayout : true,
              width: 600,
              height: 800
            });
```

**Comment by fchasen** [comment]
If the book is fixed layout, it won't be paginated so any column css would have to be in the css of the book.

**Comment by 127** [comment]
True, but it's normal to show next item in spinner manifest as a next FL page
