### ISSUE TITLE
the format of cfi

### ISSUE THREAD

**Issue by eimhee** [futurepress/epub.js#308]
Do you have the format of the cfi?
"epubcfi(/6/12[xepigraph_001]!4/2/28/2/1:0)". 

I think the url can be like epubcfi/[spine_id],
just use the spine of the epub book is enough, why do you need so many parameters?

thanks.

**Comment by yinhaibo** [comment]
spine id is just a index, or a chapter link.
CFI can do more than spine id, such as bookmark(a CFI refer to start position current showing), and note(a CFI refer to a selected range by user).
please refer to CFI specification:(http://www.idpf.org/epub/linking/cfi/epub-cfi-20111011.html)

**Comment by fchasen** [comment]
Thanks at @yinhaibo, that is very true - CFI is a slightly odd format but very powerful at being able to precisely refer to a point in a long text and so it is the preferred way to link to something in epub.js. 

However `book.goto()` supports several other ways of addressing content. You can pass it the href of the chapter, and if you have pagination loaded, the page number or percentage.

https://github.com/futurepress/epub.js/blob/master/src/book.js#L907-L919
