### ISSUE TITLE
Images not loading correct path on reload

### ISSUE THREAD

**Issue by Patrax** [futurepress/epub.js#317]
I'm facing a weird bug were the first time you load an epub, images load correctly. The next times you load the epub, or reload the page, the page that is showing currently, will not load the images because the paths will point to something like ```http://localhost:3000/read/OEBPS/Images/cover.jpeg``` instead of the correct form ```blob:http%3A//localhost%3A3000/988a6a81-eb01-4bd0-8324-13a836bd1ef0``` . You can then go to the next page and images will be loaded correctly and even go back to the previous page and now the image will have been loaded correctly.

I naively tried to force a nextPage() prevPage() when book:ready but it didn't work.

Using Rails 4+, reader.js and 'data-no-turbolink' => true to ensure full reload of the new layout. Also, using zip.js to load the epubs directly.

    document.onreadystatechange = function () {
        if (document.readyState === "complete") {
          EPUBJS.filePath = "../js/libs/";
          EPUBJS.cssPath = "../../../css/";
          // EPUBJS.cssPath = window.location.href.replace(window.location.hash, '').replace('index.html', '') + "/css/";
          // fileStorage.filePath = EPUBJS.filePath;
          var reader = ePubReader('<%= @book.get_book %>', {restore: true, reload: true });
        }
      };

**Comment by jbhorsewriter7** [comment]
I am having the same issue (again using the reader).

Only, I can only get the correct images to load if I navigate back to the cover page.

Please help!

**Comment by jbhorsewriter7** [comment]
It looks to me like you have to change the chapter in order for the images to load correctly again...

**Comment by jbhorsewriter7** [comment]
I have noticed that the demo does not have this issue here: http://futurepress.github.io/epub.js/reader/

I wonder if we are using the wrong files.  I have copied the files from /reader/ - should I be using different files.

(Have downloaded the latest .zip and things seem to be much better - but I am still getting some errors on refresh - I am looking to see what is different between my files and the example...)

**Comment by fchasen** [comment]
That reader example is using an unzipped epub, which was the difference. 
There was a bug that was preventing the urls from being replaced when it was contained.

Thanks for helping track this down, fixed in v0.2.13

**Comment by Patrax** [comment]
Thank you so much @fchasen :) , great work.
