### ISSUE TITLE
visibleRangeCfi contains incorrect end value

### ISSUE THREAD

**Issue by timbod7** [futurepress/epub.js#320]
There appears to be a problem with the page mapping logic. I'm accessing details for the current page like this:

```
  var cfiStart = book.renderer.visibleRangeCfi.start;
  var cfiEnd = book.renderer.visibleRangeCfi.end;
```

When the last page in a chapter starts with a partial paragraph, `cfiStart` correctly contains the reference for the first word on the page. However `cfiEnd` contains a reference for the last word in the *first* paragraph on the page , rather than the last word in the *last* paragraph, as I would expect.

**Comment by fchasen** [comment]
Thanks for all your work fixing this.
