### ISSUE TITLE
Error: unexpected token at line 1 in every js

### ISSUE THREAD

**Issue by BlackHayate** [futurepress/epub.js#324]
epub.js:1 Uncaught SyntaxError: Unexpected token <
epub.min.js:1 Uncaught SyntaxError: Unexpected token <
reader.js:1 Uncaught SyntaxError: Unexpected token <
hooks.js:1 Uncaught SyntaxError: Unexpected token <
ajdj.html:51 Uncaught ReferenceError: ePub is not defined(anonymous function) @ ajdj.html:51
ajdj.html:71 Uncaught TypeError: Cannot read property 'renderTo' of undefined

**Comment by matewilk** [comment]
It seems like your paths are wrong

**Comment by BlackHayate** [comment]
Thank you ^^
