### ISSUE TITLE
Limit pages/chapters

### ISSUE THREAD

**Issue by watf** [futurepress/epub.js#326]
Hi everyone,

I'm trying to limit the book for just a few pages, like a 'free preview', so where the user reach the limit, a dialog pops out saying: «You need to be a member to keep reading this story»

  This is for safety. I know a register on the system is not a big difference, but is for the new authors, so they can feel in a safe enviroment. 

 So, ¿what's the best way to do it? I am not loading the pagination because it takes too much resources from my server, and it starts after the ebook is loaded. 

 Example: • A book has 200 pages, only allow to read 10.
               • A book has 20 chapters, only allow to read 2.
        
______________________________________________________________________________
 If this help to anyone, here's a piece of code to forbid the copy/paste, which I really don't like the idea, but well.. Is the user's work as a writer, I have to respect that.

 EPUBJS.Hooks.register("beforeChapterDisplay").donotcopy = function(callback, renderer){
    var noselect = renderer.doc.createElement('style');
    noselect.appendChild(document.createTextNode("\
      body {\
           -webkit-touch-callout: none;\
    -webkit-user-select: none;\
    -khtml-user-select: none;\
    -moz-user-select: none;\
    -ms-user-select: none;\
    user-select: none;\
      }\
    "));
    renderer.doc.head.appendChild(noselect);
    if(callback){callback(); } 
}

**Comment by fchasen** [comment]
The entire chapter is loaded at a time, so you won't be able to limit them receiving that, but you could check that they are signed in before serving the next chapter.

If you wan't to display a login prompt after x number of pages, you could listen for the `locationChanged` event and display a prompt with a counter. Something simple could look like:

```javascript
var locationsViewed = 0;
book.on('renderer:locationChanged', function(locationCfi){
    locationsViewed++;
    if (locationsViewed > 10) {
       // Display Login Prompt
   }
});
```

**Comment by watf** [comment]
I did a little change, but It worked! Thanks!

var locationsViewed = 0;
var cfiactual = book.getCurrentLocationCfi();
book.on('renderer:locationChanged', function(cfiactual){
locationsViewed++;
 if (locationsViewed > 20) {
     ebookpremium(); // call function that will forbid the book
       book.gotoCfi(0);
      };
   });

**Comment by ezequiel9** [comment]
In case someone still need it. This works without problems as well. 

`rendition.on("locationChanged", function(locationCfi){
    // ....
});`
