### ISSUE TITLE
epub not working in drupal

### ISSUE THREAD

**Issue by cstpraveen** [futurepress/epub.js#327]
I have tried to install epub module in drupal 7. But it is not working well... The problem is the the iframe asks for dev.html. But in the reader directory it only has index.html. 
So we need to create dev.html or modify the code to index.html.

**Comment by fchasen** [comment]
Could you provide a link to the epub module?

**Comment by fchasen** [comment]
Will need to update the drupal plugin. `dev.html` ins't needed anymore and has been removed.
