### ISSUE TITLE
Not working well

### ISSUE THREAD

**Issue by cstpraveen** [futurepress/epub.js#329]
I have tried epubjs on drupal. It has some big issue I think.
In drupal this converts all epub files as directory in sites/default/files/epub_content directory. I am drupal services to render epub. I have did making view of epub. Now that is working fine. But the problem is when I try to click TOC in the book it is not triggering the specific page. But TOC in the menu will triggers the correct page. I don't know why. I'll explain that issue in detail.
I have triggered the reader.js to render the file. This brings TOC and bookmarks options well. The toc in the sidebar menu was working perfect. But within the epub not working any hyperlinks. I have visited toc within epub file and clicked the page link. But not working.

**Comment by fchasen** [comment]
If you have a link I can view, it would help greatly in debugging this.

**Comment by cstpraveen** [comment]
I am so sorry. I have tried that via local...

**Comment by JakeHartnell** [comment]
No follow up in almost 2 years... closing for now.
