### ISSUE TITLE
Proper way of displaying book cover

### ISSUE THREAD

**Issue by spg** [futurepress/epub.js#335]
Am I doing this right? It works for me, but looking for better alternatives (if any exist):

```
$("#cover").attr("src", Book.store.urlCache[Book.cover]);
```

**Comment by matewilk** [comment]
+1

I'm interested too how to do it properly.

Can you explain what Book object is ? Is it a ePub instance ?

**Comment by fchasen** [comment]
Good question, there isn't currently a good way to get the url from storage. 

Seems like it should be a function that returns a promise with the url, since it might need to load from storage. Here is the `book.coverUrl()` I'll add after a little more testing:

```javascript
//-- Returns the cover
EPUBJS.Book.prototype.coverUrl = function(){
	var book = this;
	return this.ready.cover.promise.then(function(url) {
		if(this.settings.fromStorage) {
			return this.store.getUrl(book.contents.cover);
		} else if(this.settings.contained) {
			return this.zip.getUrl(book.contents.cover);
		}else{
			return book.contents.cover;
		}
	}.bind(this));
};
```

**Comment by fchasen** [comment]
I've added the `Book.coverUrl()` method to master. Will document and add to the next release notes.
