### ISSUE TITLE
Uncaught ReferenceError: RSVP is not defined on Electron.js

### ISSUE THREAD

**Issue by smoqadam** [futurepress/epub.js#336]
Hi
I want to create an epub reader based on Electron.js 

but I get the following error on developer console : 

```Uncaught ReferenceError: RSVP is not defined ``` book.js:1308

**Comment by fchasen** [comment]
How are you including epub.js?

**Comment by smoqadam** [comment]
First I want to include epub.js from npm repository but it seems epub.js doesn't exist on it.
Finally I included epub.js in classic way !!!

            <script src="js/epub.js-master/build/epub.js" ></script>

**Comment by fchasen** [comment]
You could always grab it from the cdn at http://www.jsdelivr.com/?query=epub.js

It is on npm: https://www.npmjs.com/package/epub.js
and bower: http://bower.io/search/?q=epub.js

**Comment by benwalsh** [comment]
I have the same issue, using `bower`.

If I include `epub.js/build/epub.js` the error is at `book.js:1329`, if I include `epub.js/build/epub.min.js`, it is at `parser.js:280`

**Comment by jacobmischka** [comment]
Same issue. I can't get `epub.js` to work in electron at all, just RSVP error.

**Comment by JakeHartnell** [comment]
PRs for this would be welcome, I believe @fchasen is focused on the v0.3 branch.

**Comment by fchasen** [comment]
RSVP is a dependency that ePub.js relies on.

It should be included at the top of the built ePub.js file, I'll double check the packages on bower and npm. 

How are you loading epubjs? Are you using require or a script tag?

(Also you can always grab RSVP.js from npm or bower)

**Comment by jacobmischka** [comment]
I'm using a script tag, and it happens with even just downloading the latest release from github. I've also included RSVP manually, still no luck.

**Comment by fchasen** [comment]
Updates in v0.2.14 should make the dependencies work with Electron. I think the issue stems from it having `module.exports` defined and confusing our umd loader.

Tested with [Electron quick-start](https://github.com/atom/electron-quick-start) using 

```js
npm install epub.js
```

and then putting the basic example in index.html and loading epub.js via 

```js
<script src="node_modules/epub.js/build/epub.js"></script>
```

**Comment by jacobmischka** [comment]
It does indeed, thank you very much!

**Comment by gimox** [comment]
there is a problem jet. including  a minified file with rsvp and all dependence, it work in the web but electron require a npm install to work including twice the library.

**Comment by zmyspc** [comment]
I am using electron and webpack and get a similar rsvp error.
'can't load module  rsvp'
without webpack everything is fine.
