### ISSUE TITLE
Source maps use wrong path

### ISSUE THREAD

**Issue by jacksonrayhamilton** [futurepress/epub.js#337]
I've installed epub.js via npm. I'm serving epub.js via `/node_modules/epubjs`. `epub_no_underscore.js` threw an error, but the source file showed up blank in my developer tools. I manually updated the paths in `epub_no_underscore.js.map` to:

```json
{
  "sources": [
    "../libs/rsvp/rsvp.js",
    "../src/base.js",
    "../src/book.js",
    "../src/chapter.js",
    "../src/core.js",
    "../src/epubcfi.js",
    "../src/events.js",
    "../src/hooks.js",
    "../src/layout.js",
    "../src/locations.js",
    "../src/pagination.js",
    "../src/parser.js",
    "../src/render_iframe.js",
    "../src/renderer.js",
    "../src/replace.js",
    "../src/storage.js",
    "../src/unarchiver.js",
    "../libs/mime-types/mime-types.js"
  ]
}
```

And then the source could be found. Maybe something is being built incorrectly?

**Comment by fchasen** [comment]
Could you try with the `epub.js` file?

We don't require underscore anymore so that file is out of date and should be removed.

**Comment by jacksonrayhamilton** [comment]
Tried with `epub.js`, but I had to make the same change to the sourcemap in order to go to the correct file (without the change I just got a line from the built file).

**Comment by fchasen** [comment]
Ah gotcha, I added a `sourceRoot` as '../' which fixed it for me in chrome.
Feel free to reopen if that didn't fix it for you.

**Comment by jacksonrayhamilton** [comment]
Great, it's fixed for `epub.js`. But the problem continues to affect `reader.js.map`.

**Comment by fchasen** [comment]
Ah thanks, that should be fixed now as well.
