### ISSUE TITLE
Reader - Styling Fonts... etc.

### ISSUE THREAD

**Issue by jbhorsewriter7** [futurepress/epub.js#338]
This may not be an issue - just something that I need help understanding.

I would like to be able to set a custom font for the viewer.  Specifically I would like to use a font installed on my sever using the css @font-face code.

I have had issues even changing the font to an already installed font (like tahoma).

But I have never been able to get one of my css-installed fonts to work.  Ever.

**Comment by fchasen** [comment]
You could create a hook that loads customs CSS with the font-face code.

I'd try specifying the `@font-face` urls in `custom.css` absolutely.

```javascript
EPUBJS.Hooks.register("beforeChapterDisplay").customFonts = function(callback, renderer, chapter) {
  EPUBJS.core.addCss("custom.css", function() {
    callback();
  }, renderer.doc.head);
};
```

**Comment by jbhorsewriter7** [comment]
This works great!  Maybe this should be somewhere in documentation...

**Comment by fkazemi5236** [comment]
but we cant use @font-face or @import fomt urls

**Comment by fkazemi5236** [comment]
Can you give an example in the same demo code?
