### ISSUE TITLE
Bookmark Titles...

### ISSUE THREAD

**Issue by jbhorsewriter7** [futurepress/epub.js#339]
Is there any way to make the titles of the bookmarks more cohesive.  They don't seem to make a lot of sense.  (Is there an option to use chapter numbers or something?)

**Comment by fchasen** [comment]
I agree that would make sense to include the chapter information with the bookmarks (and perhaps group them by chapter).

**Comment by JakeHartnell** [comment]
Not sure what the issue is here. Feel free to reopen to restate the problem or propose a solution.
