### ISSUE TITLE
Add animation to page transition

### ISSUE THREAD

**Issue by lpccoder** [futurepress/epub.js#34]
Hello, is possible to add an animation like http://jsfiddle.net/wdm954/DkZsY/2/ when the user clicks next/previous page?

**Comment by KevinBeckers** [comment]
Is there any news on this subject?

**Comment by geek1011** [comment]
I just figured it out! This will give you a slide animation.

````javascript
EPUBJS.Hooks.register('beforeChapterDisplay').pageAnimation = function (callback, renderer) {
    var style = renderer.doc.createElement("style");
    style.innerHTML = "*{-webkit-transition: transform {t} ease;-moz-transition: tranform {t} ease;-o-transition: transform {t} ease;-ms-transition: transform {t} ease;transition: transform {t} ease;}";
    style.innerHTML = style.innerHTML.replace("{t}", "0.5s");
    renderer.doc.body.appendChild(style);
    if (callback) {
        callback();
    }
};
````

**Comment by geek1011** [comment]
Also, at the moment, to support desktop and laptop devices, epub.js needs to be patched by adding the following code somewhere before you start using epub.js, but after you load the library. The only difference this makes is that epub.js will use css transforms on desktop devices as well as mobile devices to move the pages.

````javascript
EPUBJS.Render.Iframe.prototype.setLeft = function(leftPos){
    this.docEl.style[this.transform] = 'translate('+ (-leftPos) + 'px, 0)';
}
````

**Comment by anoop4real** [comment]
Hi,
Does v0.3 support page flip animation?

**Comment by lawrence-eka** [comment]
Hi there. Nice transition effect, at least it allows the user a cue that the page has flipped. But how to also add the capability for bottom up (and top down) transitions? Oddly enough, some users prefer flicking their finger up/down to turn the pages.

**Comment by geek1011** [comment]
@lawrence-eka This is not possible in v0.2, as the pagination is achieved with columns the width of the screen. Naturally, columns are horizontal, so what you are asking is not possible. This may be possible in v0.3 though.

**Comment by pulkitnandan** [comment]
I'm using v0.3 and it renders next page by shifting the visible region of parent div. Need separate divs for each page to achieve effect like https://codepen.io/tailofmoon/pen/JXmvea?page=1& . But will it be a big change in epubjs?

**Comment by LDHo** [comment]
@pulkitnandan did you get your answer? Because I am using v0.3 as well.
