### ISSUE TITLE
Images Cut-Off on Small Screens...

### ISSUE THREAD

**Issue by jbhorsewriter7** [futurepress/epub.js#340]
When I have images in an epub file they are getting cut off on the right side if my screen is very small.

(It looks like the images are a little wider than the page - with only a max-height being set.)

I have tried adding a max-width of 100% and this seems to fix the issue... is this something to add to the image styles?

**Comment by Grovertb** [comment]
use smartimages.js

**Comment by jbhorsewriter7** [comment]
I included the file... nothing is different.  Is there something else I should be doing?

I am using the reader file.

**Comment by Grovertb** [comment]
the link of your page to see your viewfinder? and help test

**Comment by gerhardsletten** [comment]
I think the easiest way would be to add a extra stylesheet for the iframe

```
/* We need to set a height/width for the iframe to render at correct size on mobile divices */
reader = ePubReader(url,{
  width: parseInt(window.getComputedStyle(document.getElementById('viewer')).width), 
  height: parseInt(window.getComputedStyle(document.getElementById('viewer')).height)
});

/* Add a extra css to the reader iframe */
reader.book.addHeadTag('link', {'rel':'stylesheet', 'href':'css/reader.css'});
```

And in this reader.css:

```
img {
	max-width: 100%;
	height: auto !important;
}
```

**Comment by jbhorsewriter7** [comment]
That's basically what I did... I don't know if they are planning to make any changes to the actual library.

**Comment by mithunmo** [comment]
Images are still not rendering properly in epub3. 
How should we fix it ?
