### ISSUE TITLE
Page Divider Bar displaying behind pages?

### ISSUE THREAD

**Issue by jbhorsewriter7** [futurepress/epub.js#341]
On a large screen when two pages are displayed, sometimes only the top of the divider bar is visible.

I added the following z-index:

#divider.show {
    z-index: 1000;
}

Seemed to fix it?

**Comment by fchasen** [comment]
It is possible the book has a background that is covering the bar?

I think I'd prefer to have the possibility that convent can cover the divider rather than accidentally obscure something.
