### ISSUE TITLE
Accessing ePub outside of http root

### ISSUE THREAD

**Issue by hcsdrose** [futurepress/epub.js#343]
I am using php to deliver a epub file that is below http root:

serveepub.php?book=$mybook

FuturePress is unable to load the file because it is a non .ePub file extension.

How can I pass FuturePress a file outside of the root and have it recognize it as being an ePub?

**Comment by fchasen** [comment]
If the file is a .epub zip file, you can pass the `contained: true` option to force it to parse it as it would a .epub

```javascript
var Book = ePub("serveepub.php?book=$mybook", {contained: true});
```

**Comment by hcsdrose** [comment]
Worked perfectly. Thank you!
