### ISSUE TITLE
Community needs organization

### ISSUE THREAD

**Issue by JakeHartnell** [futurepress/epub.js#344]
Clearly this library is useful to people, but currently the issue tracker is a mess, there is little documentation, we don't have a good roadmap of what features need to be supported, etc.

My questions to the over 1,200 people who have starred this project:
- How do we turn epub.js into a strong open source project?
- Who wants to be involved?

Discuss.

**Comment by fchasen** [comment]
I'd love to get an idea of the projects people are using epub.js for and ideally would like to start featuring them.

My thoughts on a rough roadmap:
- [ ] Moving Reader app to it's own repo at: https://github.com/futurepress/epubjs-reader 
- [ ] Clean up issues, to move Reader related ones to the new repo
- [ ] Patch up the existing documentation as much as possible
- [ ] Add Zip, Offline support and RTL to v0.3
- [ ] Test out v0.3 early 2016

The v0.3 version is a huge clean up of the cruft that has accumulated, brings more options for rendering epubs, is much better tested and will be better documented. It's not quite ready for use yet though.

Unfortunately there are large breaking changes to the api, but the end result will be much simpler to work with. I hope to have a compatibility script that will ease the transition.

A preview of the api is here: https://github.com/futurepress/epub.js/blob/v0.3/API.js

In general, I'd like to move discussion and questions which aren't "close"-able over to the gitter chat at https://gitter.im/futurepress/epub.js

Also many many thanks to everyone who have been submitting pull requests and answering questions in the issues.

**Comment by hz0324** [comment]
It's a great project, but hard to use. For example, I want to change the distance of tow paragraphs, but I dont know how just reading the document. I'd like to contribute more, but having no idea where I can help.

**Comment by coler-j** [comment]
The top priority should really be documentation. As a newcomer to this library, I don't even have any idea what the difference between epub.js and epub.js reader are (other than guessing) the epub.js is a demo app or something?

**Comment by coler-j** [comment]
I just abandoned this project and went to the _slightly_ better documented Readium libraries https://readium.org/

It seems to work better off the shelf anyways (i.e. the epub.js test project had JS issues reading the TOC of a sample epub, and the readium test project worked right away).

**Comment by fchasen** [comment]
Sorry you had to abandon Epub.js, but Readium is a great project!

Agreed the reader split isn't clear enough, and the reader's code has become a bit stale (written in ES5). 

Epub.js handles the parsing and provides an api for rendering of the book content, while the reader is just an example of how to integrate that API into a more complex reading app.

I hope to replace the reader with a component library for the different UI parts you to need to assemble a custom reader as soon as possible.
