### ISSUE TITLE
Broken Table of Contents - newest update...

### ISSUE THREAD

**Issue by jbhorsewriter7** [futurepress/epub.js#345]
With this newest update (which amazingly resolves the issue with .zip / url) I have a new issue that my table of contents is missing and bookmarks do not work.

But with my .epub files - both from Gutenburg.  Here is one:

http://www.gutenberg.org/ebooks/42671.epub.images?session_id=c3e8dc0d59bbc45d16132d8f247f3bf81869a887

It appears that it is an issue with cover images - but I am not sure.  Will be doing some more testing...

**Comment by jbhorsewriter7** [comment]
I get these two errors in chrome:

TypeError: a.forEach is not a function(…)
Uncaught ReferenceError: spreads is not defined

**Comment by fchasen** [comment]
Looking into this. Seems to be an issue with the ncx file mime type.

`loadXml` returns the error: `TypeError: Failed to execute 'parseFromString' on 'DOMParser': The provided value 'application/x-dtbncx+xml' is not a valid enum value of type SupportedType.`

**Comment by jbhorsewriter7** [comment]
I wondered... what is your suggested method for editing ePub files?  I tried this one called Calibre... it seems to do strange things to the ePub files as well.

**Comment by fchasen** [comment]
Should be fixed in master. The toc of that book is pretty odd though, as it repeats the top level "PRIDE AND PREJUDICE:" 3 times.

Most often I just unzip the epub and edit it in a text editor. Happy to go into more detail on gitter (https://gitter.im/futurepress/epub.js)

**Comment by jbhorsewriter7** [comment]
Thank you for the fix!  Yes.  Gutenburg's .epub files seem to be very strange...
