### ISSUE TITLE
how to add night mode

### ISSUE THREAD

**Issue by wangwy** [futurepress/epub.js#349]
I added a css file, the file context is 
html {
    -webkit-filter: invert(1) hue-rotate(180deg);
    filter: invert(1) hue-rotate(180deg);
}
img, video{
    -webkit-filter: invert(1) hue-rotate(180deg);
    filter: invert(1) hue-rotate(180deg);
}
body {
    background: black;
}

but after the second page of image of each chapter are not displayed.

What should i do?

**Comment by fchasen** [comment]
This is a really really cool idea.
I'll have to test a few things out but it should work just fine. 

How are you adding this css?

**Comment by wangwy** [comment]
http://wangwy.github.io/testExample/epub/books/xiaowangzi/index_split_001.html

when the filter style together with column style, image of the second column does not show.

**Comment by watf** [comment]
Well, that's easy!

function night(){
  book.setStyle("background-color", "#000000");
  $('#viewer').css('background-color','#000000'); // or #main
  book.setStyle("color", "#ffffff");
  }

Change the colors that you want to use.
To call the function, add a button (with ID #night)
$(document).on("click","#night",function() { night(); });

So, this way, you can add how many colors you'd like.

**Comment by watf** [comment]
PD: Also, this way's saved on localstorage, so the browser will remember which color the user selected.

**Comment by wangwy** [comment]
If a book has its own background style like 
```
<body>
  <div style="background-color: red; border-right: solid 2px #F0C3D5; .....">
   .......
  </div>
</body>
```

**Comment by JakeHartnell** [comment]
🍾 

Night mode should probably go in the [epubjs-reader repo](https://github.com/futurepress/epubjs-reader)
