### ISSUE TITLE
IE throwing Permission Error...

### ISSUE THREAD

**Issue by jbhorsewriter7** [futurepress/epub.js#350]
So, this is very strange.  But now when I run /reader/ in IE I cannot load the first chapter.

I am getting a permission error:

![image](https://cloud.githubusercontent.com/assets/1674953/11696070/1707647a-9e78-11e5-9d91-c055ac46eb04.png)

**Comment by fchasen** [comment]
Thanks, turns out this was an issue in the smartimages hook. Fixed in https://github.com/futurepress/epub.js/commit/443eada6393cc23b27dedb3898be0b208c74e2f1

**Comment by jbhorsewriter7** [comment]
Yay!!!!

It does look like if I add the custom css code then it breaks in IE as well.  For now I will just not run the custom css in IE.  I should be fine without it.  

But running this breaks IE:

                  EPUBJS.Hooks.register("beforeChapterDisplay").customFonts = function(callback, renderer, chapter) {
                      EPUBJS.core.addCss(EPUBJS.cssPath+"custom.css", function() {
                          callback();
                      }, renderer.doc.head);
