### ISSUE TITLE
Text cut-off

### ISSUE THREAD

**Issue by benjick** [futurepress/epub.js#364]
![text](http://i.imgur.com/XmBdE3x.png)

This is shown in my phone as well (Nexus 5X). Any way to solve this?

**Comment by fchasen** [comment]
You could update the reader css or set the height using window.innerHeight.
I'll add an example of this.

**Comment by tbergen1** [comment]
What is the example that was made for this situation?  I am constantly finding the right edge of the my text cut off by half a letter or so.  I am using the standard css from the examples and no amount of widening or shortening the margins seems to fix it.

**Comment by prsolucoes** [comment]
Any solution from latest version of epubjs?

**Comment by fchasen** [comment]
Shouldn't be an issue anymore on v0.3
