### ISSUE TITLE
Loading forever in Opera browser

### ISSUE THREAD

**Issue by Infernion** [futurepress/epub.js#371]
In Opera browser for computer (tested in 30+ versions, http://www.opera.com/about/products) loading epub runs forever. It just blank screen with loading circle. No errors rised.  

it's strage because Opera based on chromium and should work propper. But maybe have some issuse...

Here is link http://wiki.allatra.club/reader/сэнсэй-ii-исконный-шамбалы/
+++++
Update: just plain epub.js is works normal, but reader.js do not

**Comment by fchasen** [comment]
That link works fine for me in Opera 34.0

**Comment by Infernion** [comment]
Seems this is Opera bug on Linux platform...
