### ISSUE TITLE
Support for CSS setting of certain elements in the book

### ISSUE THREAD

**Issue by hz0324** [futurepress/epub.js#378]
for example, I want to change the CSS of all the images inside the book as below because all the images now are overflowing their containers.

`img{
 width:auto;
 height:auto;
 max-width:100%;
 max-height:100%;
}`

But I cannot find a way to correct it unless to change the source code of the project. I suppose there will be more needs like this one.

**Comment by Grovertb** [comment]
use smartimages.js

**Comment by hz0324** [comment]
thank you very much. You really help me out.
