### ISSUE TITLE
is that possible to read a local epub file and render it to the browser? 

### ISSUE THREAD

**Issue by hz0324** [futurepress/epub.js#380]
I would like to build a web app that allows user to select a** local epub file **and read it right away.
I have tried a lot of method to do it, but all failed. But I still think it is doable.

In this article [Using files from web applications](https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications) the author described a way reading local files and show it on the browser. At the end of the article, he said it is possible to display a local PDF file and Video file.

I guess it is also possible to do it with EPUB files. But I cannot figure out how. So is this possible to do it right now? If not, please let me know what can be done to make it happen. I am more than happy to help here.

Thanks.

**Comment by hz0324** [comment]
This how I did it following the instruction of the article I mentioned before.
````
<script src="/public/js/epubjs/epub.js"></script>
<script src="/public/js/epubjs/libs/zip.min.js"></script>


<input type="file" id="input" onchange="handleFiles(this.files)">
<div id="book" style="height: 100%;width:100%;">


</div>

<script>
    function handleFiles(files){
        var fileReader=new FileReader;
        var myBookFileObecjt=files[0];
        var objectURL = window.URL.createObjectURL(myBookFileObecjt);
        console.log("file name="+myBookFileObecjt.name);
        console.log("file size="+myBookFileObecjt.size);
        console.log("file type="+myBookFileObecjt.type);
        console.log("file objectUrl="+objectURL);

        var book = ePub(objectURL);
        book.renderTo("book")
    }

</script>
````


this is the error it shows:
![123](https://cloud.githubusercontent.com/assets/5040078/12846006/eb4df4ca-cc44-11e5-8907-37e43f0d7695.png)

As you can see, I have got a ObjectURL as {blob:http%3A//127.0.0.1%3A3000/d5d65108-8de5-41c9-a0c4-568d586106c2}. But I don't know how to deal with it. If you know anything about these, please let me know. Thank you very much.

**Comment by hz0324** [comment]
I find how to do it. You can use FileReader.readAsArrayBuffer to make it happen

**Comment by hihemant84** [comment]
Hi hz0324, did you get any way to solve your issue yet. Actually I am also facing similar kind of issue.

**Comment by hz0324** [comment]
Not yet, I am moving on to NW.js, so I am not having this problem anymore.
