### ISSUE TITLE
Keep getting error from nowhere

### ISSUE THREAD

**Issue by hz0324** [futurepress/epub.js#381]
Hi, guys. Whenever I loaded a book I am getting the errors like bellow. It gives no clue where they come from. Anyone know what happened?
![1234](https://cloud.githubusercontent.com/assets/5040078/12864159/a601c742-ccbd-11e5-9762-36d00ed6526d.png)

**Comment by fchasen** [comment]
Happy to help you track down what is going on but could you ask on the google group or on gitter?

**Comment by hz0324** [comment]
I would like to, but google group seems not active now. The latest post is about half year ago. I have tried to find a room on gitter. I tried epub and epubjs, no related room shows up. What's the room name on gitter? Thanks
