### ISSUE TITLE
Scrolling chapter instead of paging

### ISSUE THREAD

**Issue by jonhargett** [futurepress/epub.js#382]
Is v.3 where scrolling is introduced, or is possible in the current version? If v.3, any ideas on when that will be tagged?

**Comment by alexandprivate** [comment]
I am looking for the same thing. Any idea ?

**Comment by jonhargett** [comment]
@alexandprivate Not yet. One idea I had that I haven't tried yet is, just use this library to parse the epub and tell me what the URL is and then display that URL in my own iframe.

**Comment by alexandprivate** [comment]
hummmmmm sounds good but could your iframe be truncated too ??? at this point I do get the scroll showed but not functional because  the area keeps truncated.

**Comment by alexandprivate** [comment]
here is the version 3 https://github.com/futurepress/epub.js/tree/v0.3 ... "continuous" render looks close to what we need but in this case the entire book have been render not a page

**Comment by alexandprivate** [comment]
@jonhargett have you notice a short pause after the spinner vanish away and before the content loads ?

**Comment by alexandprivate** [comment]
@jonhargett problem almost solved ... set the area > iframe the document height and bomm !

**Comment by fchasen** [comment]
v0.3 will support single paged scrolling views.

You can see an example here: http://fchasen.com/epubjs/v0.3/examples/single.html

code: https://github.com/futurepress/epub.js/blob/v0.3/examples/single.html

This isn't production ready yet, but should be ready for testing mid March.

**Comment by kkmehta123** [comment]
Yes, I am able to use continuous scroll functionality in my project. But how would i be able to use all other functionalities like left navigation of chapters, bookmarks and page numbers which i was able to use with https://github.com/futurepress/epub.js/ source code. Along with continuous scroll , i wanted to use other functionalities of reader as well. Kindly help me out with this.
