### ISSUE TITLE
epub.js is not working with packaged chrome apps

### ISSUE THREAD

**Issue by hihemant84** [futurepress/epub.js#387]
Hi,

I am trying to use epub.js with my chrome packaged app, but looks like its not compatible with it to read the epub files from my local system. Is that any version pf epub.js exist which can work with chrome packaged app to work offline?

**Comment by FranklinSilva** [comment]
I'm with the same problem, but in my case after fix issues with document.write and unload event to proper work in Chromeapps it trows me the following error:

TypeError: Cannot read property 'map' of null(…) epub.js 3019

**Comment by fchasen** [comment]
Chrome Packaged Apps aren't supported.

**Comment by clarodanesh** [comment]
@fchasen are packaged apps still not supported?
