### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by vstirbu** [futurepress/epub.js#39]
It would be really nice if the library can be installed using [Bower](http://bower.io). Thanks!

**Comment by benwalsh** [comment]
Is there a file in the Bower build that can be included via `RequireJS`? I'm not having much luck.

**Comment by yashtatsme92** [comment]
It seems that one of the bower dependencies (marks-pane) does not get resolved. Thanks!

**Comment by fchasen** [comment]
Ugh, sorry I don't test with Bower much - could you create a new issue for this?
(Also any PRs fixes for this by someone who uses Bower would be greatly appreciated)
