### ISSUE TITLE
Pagination and Locations problem

### ISSUE THREAD

**Issue by snsxn** [futurepress/epub.js#399]
Hi and thanks for creating the amazing epub.js !

I'm having problem while trying to show the current page and total pages of the book (_for mobile using cordova_).

Using paginate method it returns repeated page number:

- I'm on page 1, it says page 1

- Turn to page 2, it says page 2

- Turn to page 3, it says page 3

- Turn to page 4, it says page 4

- Turn to page 5, it says page 4

And so on...

And using locations I'm not able to get the current page from percentages.

How can I accomplish these?

**Comment by snsxn** [comment]
It's client intensive for the first time, but after saving it to a JSON, the pageList pagination method is working fine:
```javascript
Book.ready.all.then(function(){
    Book.generatePagination();
});
Book.pageListReady.then(function(pageList) {
    // console.log(JSON.stringify(pageList)); // Here you can save the result
    rendered.then(function(){
        var currentLocation = Book.getCurrentLocationCfi();
	currentPage = Book.pagination.pageFromCfi(currentLocation);
    });
    console.log('Total pages: ' + Book.pagination.totalPages);
});
Book.on('book:pageChanged', function(location){
    console.log('Current page: ' + location.anchorPage);
});
```

**Comment by sengemann** [comment]
My guess is you were using an older version?
