### ISSUE TITLE
Get CFI of a query or scentence

### ISSUE THREAD

**Issue by Seanberite** [futurepress/epub.js#404]
Hi! Is it possible to extract a cfi given a specific chapter/xhtml source and a word or sentence i.e "what cfi do i have" or "where".
And look for that sentence in chapter01.xhtml

Thanks

**Comment by fchasen** [comment]
Not at the moment, though `chapter.find` might come close to what you where looking for: https://github.com/futurepress/epub.js/blob/master/src/chapter.js#L217
