### ISSUE TITLE
Current page number

### ISSUE THREAD

**Issue by JayMorrison-by** [futurepress/epub.js#405]
How i can take current page number?
Have code 
        <script src="../build/epub.js"></script>
    <script src="../build/libs/zip.min.js"></script>

```
     <script>
        "use strict";
        var Book = ePub({ restore: true }); 
        Book.open("http://readthis.by/books/1.epub");   
    </script>
</head>
<body>
    <div id="main">
      <div id="prev" onclick="Book.prevPage();" class="arrow">‹</div>
      <div id="area"></div>
      <div id="next" onclick="Book.nextPage();" class="arrow">›</div>
      <div id="pages">
    </div>

    <script>
        Book.renderTo("area");
    </script>
</body>
```

</html>
or code like examples/search.html

**Comment by jamesvanhallen** [comment]
function curPage() {
        var currentLocation = Book.getCurrentLocationCfi();
        var currentPage = Book.pagination.pageFromCfi(currentLocation);
        alert("_current" + currentPage);
        var page = Book.pageList[currentPage-1];
        alert("_bookmark" + page.cfi);
    }you can catch alert in WebChromeClient onAlertJS() method

**Comment by JayMorrison-by** [comment]
CurrentPage always equal to -1

**Comment by jamesvanhallen** [comment]
Book.renderTo("area");
    Book.ready.all.then(function () {
        Book.generatePagination();
    });

    Book.pageListReady.then(function (pageList) {
        alert("_pages" + Book.pagination.totalPages);
    });

    Book.on('book:pageChanged', function (location) {
        var currentLocation = Book.getCurrentLocationCfi();
        var currentPage = Book.pagination.pageFromCfi(currentLocation);
        alert("_current" + currentPage);
        var page = Book.pageList[currentPage-1];
        alert("_bookmark" + page.cfi);
    });

try this after book init

**Comment by JayMorrison-by** [comment]
It's work! Thank you very much.

**Comment by jamesvanhallen** [comment]
Maybe you know how to find and highlight text?)

**Comment by JayMorrison-by** [comment]
sorry, but no :C

**Comment by fchasen** [comment]
Sorry I'm late to this conversation, but page num will always be -1 if the pageList isn't present. `generatePagination` will create a pageList but it has to load and render every chapter of the book so use it with caution. I'd recommend using locations instead, like in this example: https://github.com/futurepress/epub.js/blob/master/examples/locations.html
