### ISSUE TITLE
Change license short identifier

### ISSUE THREAD

**Issue by danielnixon** [futurepress/epub.js#406]
Please update the license short identifier in package.json and bower.json from `FreeBSD` to `BSD` or `BSD-2-Clause` (as per https://spdx.org/licenses/). This change would allow epub.js to be published automatically as a [WebJar](http://webjars.org/) on BinTray (see [BinTray's list of licenses](https://bintray.com/docs/api/#_footnote_1)).

**Comment by fchasen** [comment]
Will do
