### ISSUE TITLE
How can I get standard ePub page numbers

### ISSUE THREAD

**Issue by geek1011** [futurepress/epub.js#409]
When I use epub.js to get page numbers, they are different on different screen sizes and on a window resize. I also use the Kobo ereader and calibre to read books. They always have consistent page numbers.

Is there a way to get these same consistent page numbers with ePub.js?

**Comment by snsxn** [comment]
I'm also interested!

**Comment by fchasen** [comment]
You can load a ePub pageList with the page numbers in it or you can generate locations which are based on content word counting and are consistent, or generate pages which are based on rendered page size.

My preference is to use locations like in this example: https://github.com/futurepress/epub.js/blob/master/examples/locations.html

**Comment by snsxn** [comment]
Using pageList or Locations on iOS page numbers are not consistent for me because it repeats some of them like 1, 2, 2, 3, 3, 4...
Maybe a problem with the fixed layout on small screens?

**Comment by geek1011** [comment]
According to many sources, Adobe ePub pages are 1024 characters. I have tried `book.locations.generate(1024);` but it still is not consisstent with Adobe Digital Editions.

**Comment by geek1011** [comment]
I don't think this will be possible as Adobe used 1024 bytes of the compressed ebook, not of the text.

**Comment by sengemann** [comment]
Are we sure that it's 1024 bytes? I found this: https://www.mobileread.com/forums/showthread.php?t=214242

**Comment by geek1011** [comment]
Maybe. I don't remember the exact source of where I found the 1024 bytes, but I know I read it somewhere. I haven't used ADE or anything RMSDK-based much recently, so I can't say much more.
