### ISSUE TITLE
EPUBJS on Joomla! platform

### ISSUE THREAD

**Issue by chiemekailo** [futurepress/epub.js#410]
I have the ePub.js package working on my Joomla 2.5 installation. But I cannot work any of the EPUBJS.Book functions such as "on". Hence I cannot listen for any events (such as; book:pageChanged) that would have helped make the reading experience more engaging.
What do I need to do?!

**Comment by fchasen** [comment]
Please try asking in [Gitter](https://gitter.im/futurepress/epub.js) or in the [Google group](https://groups.google.com/forum/#!forum/epubjs).
