### ISSUE TITLE
Not getting epub file from response 

### ISSUE THREAD

**Issue by JustPepper** [futurepress/epub.js#415]
window.reader = ePubReader(http://web.com/storage/images) <- i have this URL from a controller in my server 

this urls returns a response with the epub file but im getting this error  :

epub.min.js:8 Could not load book at: META-INF/container.xml

**Comment by fchasen** [comment]
If the epub is a zip, force it to use that by passing 
```
var book = ePub("http://web.com/storage/images", {contained : true})
```
