### ISSUE TITLE
prevPage() or nextPage() not working properly

### ISSUE THREAD

**Issue by hussainanver52** [futurepress/epub.js#418]
hello i am trying to create a inapp epub reader for ionic app. I am trying to go to next and  previous page in epub as specified below, its working fine till few pages and then the pagination stops working 

`$scope.Book = ePub("https://s3.amazonaws.com/moby-dick/", { restore: true });
$scope.Book.renderTo("epub");
/* working fine but after few pages not working*/
$scope.nextPage = function(){
$scope.Book.nextPage();
};
`
i tried 
1. `$scope.Book.generatePagination().then(function(toc){})`
2. `EPUBJS.Render.Iframe.prototype.setLeft = function(leftPos){
    this.document.documentElement.style.WebkitTransform = 'translate("-"' + leftPos +'"px", 0)';
  };`
3. tried to log errors

but nothing worked
same implementation and issue for prevPage() also

any help will be appreciated
thank you

**Comment by ssomnoremac** [comment]
this is how I'm using the hypothesis-oa [v0.3] branch in coffeescript angular  ( @ = $scope )

    book.loaded.spine
      .then (s) =>
        @rendition = book.renderTo "area", {}
        
        next = document.getElementById("next")
        next.addEventListener "click", () =>
          @rendition.next()
        , false

        prev = document.getElementById("prev")
        prev.addEventListener "click", () =>
          @rendition.prev()
        , false

take a look at[ this example](https://github.com/futurepress/epub.js/blob/hypothesis-oa/examples/hypothesis.html) for how to use v0.3 and use the epub.js from this branch's dist folder
