### ISSUE TITLE
Use epub.js on Android

### ISSUE THREAD

**Issue by bellec1u** [futurepress/epub.js#419]
Hello,
For my project, I need to read files to epub format in an Android application.
Currently, I can play them in a WebView but the layout is not beautiful.
My question is, how to use epub.js in android to read the epub files even without internet connection?
Thank you and sorry for my bad English.

**Comment by ssomnoremac** [comment]
@bellec1u I will say that my organization has plans to use epubjs in React-Native on Android. The `view_managers` branch is what we plan to be using. It isn't done yet, but it should be there soon.

**Comment by mpadiy** [comment]
@ssomnoremac  expect coming soon

**Comment by fchasen** [comment]
At the moment, the best way it is load the library using something like PhoneGap.
