### ISSUE TITLE
how use bookmarks 

### ISSUE THREAD

**Issue by laurent6** [futurepress/epub.js#420]
hi, 

I have a problems with bookmarks. It's work find but i don't understand how get it for save in database, and how load it when i open epub. If somenone can help me ... 

Laurent.

**Comment by ConProgramming** [comment]
same question

**Comment by fchasen** [comment]
Please try asking in [Gitter](https://gitter.im/futurepress/epub.js) or in the [Google group](https://groups.google.com/forum/#!forum/epubjs).

**Comment by jkrehm** [comment]
I know this is old and closed, but in case someone else comes across it, the best way I've found so far to store the bookmarks is to listen for the add event and then do what you will with the value, e.g. AJAX request to store it in a database, store it in localStorage, etc.

For example:
```javascript
const reader = ePubReader("{{ url_for('static', filename=bookid) }}/");
reader.on("reader:bookmarked", function (location) {
  console.log(location); // e.g. epubcfi(/6/4[id7]!/4[307]/4/1:0)
});
```
