### ISSUE TITLE
Using epub.js with system.js module loader

### ISSUE THREAD

**Issue by crebuh** [futurepress/epub.js#423]
Hi!

I want to use the epub library in a project. Due to the fact we are using Angular2 and Typescript, I've got some problems with the integration of the library into our project. I've seen in the source, that there is a module support:

```
    //exports to multiple environments
if (typeof define === 'function' && define.amd) {
    //AMD
    define(['rsvp', 'jszip', 'localforage'], function(RSVP, JSZip, localForage){ return ePub; });
} else if (typeof module != "undefined" && module.exports) {
    //Node
    global.RSVP = require('rsvp');
    global.JSZip = require('jszip');
    global.localForage = require('localforage');
    module.exports = ePub;
}
```

which basically means that the library supports amd and common js module definition? 

Does anybody had similar problems and can give me some advice how to integrated the epub library into my project?

**Comment by fchasen** [comment]
You should just be able to `require('epubjs')`
