### ISSUE TITLE
The IE Chinese garbled，But  the Google、Firefox browser normal。How to solve？Help me！！！

### ISSUE THREAD

**Issue by Ch-garbled** [futurepress/epub.js#428]

**Comment by nancyXixi** [comment]
解决了吗，我也遇到在ie下乱码的问题

**Comment by Ch-garbled** [comment]
解决了，这个插件IE下要求内容必须是XHTML的文件。但不知道这是不是唯一的解决办法。搜索功能你可以用吗？

**Comment by nancyXixi** [comment]
我测之前测试也是，xhtml格式的确实可以正常显示。我没有做搜索功能。

**Comment by fchasen** [comment]
Closing for now as I'm not sure how to reproduce this, any further help with this would be appreciated.

Feel free to reopen.

**Comment by georgezouq** [comment]
@Ch-garbled  怎么解决的 能分享一下吗？？

**Comment by georgezouq** [comment]
@Ch-garbled  试过ie10以下浏览器吗？？
