### ISSUE TITLE
question: is it possible to read just a chapter instead of a entire book?

### ISSUE THREAD

**Issue by paulocheque** [futurepress/epub.js#435]
Is that feasible?

Thanks in advance!

**Comment by JakeHartnell** [comment]
Can you clarify your question a bit? Do you want to limit access to a chapter of the book and put the rest behind a pay wall for instance.

**Comment by paulocheque** [comment]
This could be a situation. But I was thinking about another situation, when the epub file is to big and I want to serve one chapter at a time.

Something like: 
1) user requests the next chapter
2) js code downloads the next epub chapter via ajax
3) use epub.js to display only the downloaded chapter

**Comment by injectless** [comment]
that's kinda how it works.
it loads the next chapter when you hit the one you're about to read.

**Comment by GoogleQian** [comment]
I mean a large ePub file. In order to increase the user experience, I want to return the front-end ePub file in the back end according to the chapter. How do I monitor and connect the chapter? For example, how to transition to the next chapter，Thanks anyway!

**Comment by GoogleQian** [comment]
Me too!     Now I mean a large ePub file. In order to increase the user experience, I want to return the front-end ePub file in the back end according to the chapter. How do I monitor and connect the chapter? For example, how to transition to the next chapter，Thanks anyway!
