### ISSUE TITLE
Loading ePub from a blob url not working

### ISSUE THREAD

**Issue by geek1011** [futurepress/epub.js#436]
I cannot load a epub from a blob URL. The url is valid, but the problem is epub.js thinks it is a decompressed epub, and therefore gives me the error: `GET XHR http://localhost:8000/META-INF/container.xml [HTTP/1.0 404 File not found 6ms]` . Is it possible to force epub.js to treat it as a zip file so it does not do this?

**Comment by geek1011** [comment]
I got it working. The trick was to pass it an ArrayBuffer instead of a blob url. 

```
    var reader = new FileReader();
    reader.addEventListener("load", function() {
        Book = new ePub(reader.result);
    }, false);
    if (fileObj) {
        reader.readAsArrayBuffer(fileObj);
    }
```

**Comment by Nipun04** [comment]
Hey,
can your  solution work for the following issue

[](https://github.com/janpio/ionic-epubjs/issues/39#issuecomment-348685400)

**Comment by missionsave** [comment]
instead of readFile(objectUrl);
shouldn't be  var book = ePub(objectUrl); ?

**Comment by tuphan-dn** [comment]
For anyone who looking for reading epub from `blob`

```ts
import { Book } from 'epubjs'

const blob: Blob = ... // Blob from HTTP request or file uploading

const buf = await blob.arrayBuffer()
const book = new Book(buf as any, { openAs: 'binary' })
```

The line of `buf as any` because the incorrect type definition in `epubjs`, however, it's ok to use.
