### ISSUE TITLE
rendering problem in Safari 9.1.1

### ISSUE THREAD

**Issue by gBritz** [futurepress/epub.js#437]
Hi,

I found a rendering problem when the iframe loads a page from the browser cache: the page does not apply styles from external stylesheets.
This happens only on Safari 9.1.1.
I put together an example replicating the issue:

![bug-layout](https://cloud.githubusercontent.com/assets/4161527/16597238/40e28eb4-42ce-11e6-8530-2e33fbf3d00f.gif)

You can simulate this error with the following files:

[index.html](https://github.com/futurepress/epub.js/files/348473/index.html.txt)
[epub-test.epub](https://github.com/futurepress/epub.js/files/348474/epub-test.epub.txt)

**Comment by fchasen** [comment]
I believe this was fixed by switching to not reusing the iframe here: https://github.com/futurepress/epub.js/commit/70fb1c957017db6010d77c541da889825aa88fb9

Included in v0.2.15 - https://github.com/futurepress/epub.js/releases/tag/v0.2.15
