### ISSUE TITLE
how can i use EPUB stream with this library?

### ISSUE THREAD

**Issue by notice90** [futurepress/epub.js#441]
how can i use EPUB stream with this library? I have string something like this from my backend, pulled it using ajax then pasted it in ePub("<stream string>"). 

Here's my example of EPub Stream string

PK
4}�Doa�,mimetypeapplication/epub+zipPK
4}�D�rL���toc.ncx���r�0���)6��-M�f�3  !�L�4d����=ؒ+������i��0\����߮�p�WY
_d�Yule6룗ɽu���k�gw����?���}|�0=<�1��ܕ]�9�:G��b��+��˥�D�m.f������8��F`�_D^���=�f�&�J�ᡬ�1���96�-7�$�ڭ�{fY0�)D<M�R�G���*E Q4�@A���@�F�����(S��6KX��I�b.)��ج\�z�x�d�-��T�$Z<���]��2p-

**Comment by fchasen** [comment]
Setting up a http server for your backend it required to serve the epubs
