### ISSUE TITLE
Help review pull requests

### ISSUE THREAD

**Issue by JakeHartnell** [futurepress/epub.js#445]
We have ten open PRs: https://github.com/futurepress/epub.js/pulls

It would be great if the community could help review them.

If it looks like there is consensus, I might hit the merge button. 

Currently working full time on http://commongarden.org, so unfortunately don't have time for much else.

**Comment by fchasen** [comment]
I'll look through the backlog, but unfortunately I need to keep some of them unmerged as I am using the diffs to transfer them into the v0.3 branch. (Especially the great work on vertical rendering)

The new Rendition api is very very close to compliation, should be ready to go soon!

**Comment by JakeHartnell** [comment]
No worries! Closing.

**Comment by JakeHartnell** [comment]
Cool! Can't wait to give it a spin. : )
