### ISSUE TITLE
 How do I get people to the extension .epub file in the path?

### ISSUE THREAD

**Issue by kimkwanho** [futurepress/epub.js#448]
I watched by running a sample of the basic file.
It operates satisfactorily .
<Script>
            "Use strict";
            //var Book = ePub ( "https://s3.amazonaws.com/moby-dick/");
            var Book = ePub ( "C: / Users / Administrator / Downloads / epubFile / testingEpubFile001");
        </ Script>
How do I get people to the extension .epub file path, as in the comment section below pro ?

The attached image is the error information.
![default](https://cloud.githubusercontent.com/assets/20715794/17795504/e57a4f78-65f3-11e6-873d-e38e0486fcd5.png)

**Comment by fchasen** [comment]
I'd be able to help more in our [gitter](https://gitter.im/futurepress/epub.js) or in the google groups page.
