### ISSUE TITLE
v0.3 change style

### ISSUE THREAD

**Issue by timfreiheit** [futurepress/epub.js#452]
I could found a ways to set the style for the chapters like it is done in v0.2 (book.setStyle)

**Comment by fchasen** [comment]
Added a Themes class to handle setting the styles which you can access at `rendition.themes`

You can register themes

```js
rendition.themes.register({
   "dark" : "themes.css",
    "light" : "themes.css",
    "tan" : "themes_tan.css"
});
```

Then apply the theme you want to use:
```js
rendition.themes.apply("tan");
```

Or set font size or other css directly
```js
rendition.themes.fontSize("140%");
rendition.themes.override("color", "purple");
```
Example usage is here: https://github.com/futurepress/epub.js/blob/v0.3/examples/themes.html
