### ISSUE TITLE
v0.3 dynamic dimension changes

### ISSUE THREAD

**Issue by timfreiheit** [futurepress/epub.js#453]
the chapter frame does not resize dynamically when the chapter content size changed.
for example after changing the text size or the font

**Comment by fchasen** [comment]
Yes, I'll need methods to adjust the css that trigger the iframe to expand after they are called.

**Comment by fchasen** [comment]
I've added a `rendition.themes` example to adjust the text or css and rerender here: https://github.com/futurepress/epub.js/blob/v0.3/examples/themes.html

Will add it to the documentation shortly.
