### ISSUE TITLE
v0.3 load local files

### ISSUE THREAD

**Issue by timfreiheit** [futurepress/epub.js#455]
currently it is not possible load load local files with file:// like it is done in v0.2.

```
Cross origin requests are only supported for protocol schemes: http, data, chrome, https.
```

**Comment by geek1011** [comment]
You can do it with a file input the way I do it in my epub reader. See https://github.com/geek1011/ePubViewer/blob/6ee37ce0e9a410187809d71b25d5d6094fc7e2ad/reader.js#L196-L219

**Comment by fchasen** [comment]
You can't load a local file with `XMLHttpRequest` in a browser, though you could set up an iOS or Android webview that allows local filesystem access.

If you want use a file directly, you'll need to use a `<input type="file" id="input">` and feed that file to epub.js. I'll added an example of that here: https://github.com/futurepress/epub.js/blob/v0.3/examples/input.html
