### ISSUE TITLE
TOC Related issue

### ISSUE THREAD

**Issue by SwatiKoli** [futurepress/epub.js#458]
I am having an issue in toc as it is showing a html file in a content.opf but it is not present when i am loading a chapters using epub.js as it contains 20+ chapters.Still when i print number of chapters it is showing only 15 chapters.Why this happens.Can anybody help me out in this

**Comment by fchasen** [comment]
Is there anyway to share the epub file? (Just the opf and toc file would be very helpful)

**Comment by fchasen** [comment]
Going to close this for now, would be happy to dig into more it if you could share the opf and toc to reproduce it.
