### ISSUE TITLE
Page swipe left / right functionality is missing

### ISSUE THREAD

**Issue by dghag** [futurepress/epub.js#46]
Page swipe functionality is not there. How to add it?

**Comment by yinhaibo** [comment]
Yes, fchasen's idea is very good, but have little problem while the scripts load. I make some change, and it can works now. Thanks.
```javascript
EPUBJS.Hooks.register("beforeChapterDisplay").swipeDetection = function(callback, renderer){

        function getBaseUrl() {
            var re = new RegExp(/^.*\//);
            return re.exec(window.location.href);
        }
        
        function executeScriptAfterLoad(){
            //-- Create a script element, you could also load this from an external file like above
            var script = renderer.doc.createElement("script");

            //-- Listen for swipe events
             script.text = '\
                $(window).on("swipeleft", function() {\
                    parent.Book.nextPage();\
                });\
                $(window).on("swiperight", function() {\
                    parent.Book.prevPage();\
                });\
                $(document).bind( "tap", function(event){\
                    parent.actionBookHeaderAndFooter("toggle");\
                });';

            renderer.doc.head.appendChild(script);
        }
        
        //-- Load jQuery into iframe header
        EPUBJS.core.addScripts([getBaseUrl() + "jquery/2.1.4/jquery-2.1.4.min.js",
                                getBaseUrl() + "jquerymobile/1.4.5/jquery.mobile-1.4.5.min.js"], executeScriptAfterLoad, renderer.doc.head);

        
        if(callback) callback();        
}
```

**Comment by watf** [comment]
@yinhaibo it throws me this error
Uncaught TypeError: Cannot read property 'mobile' of undefined

**Comment by MifRea1** [comment]
Another option (you don't need jQuery):
```js
EPUBJS.Hooks.register('beforeChapterDisplay').swipeDetection = function(callback, renderer) {
  function detectSwipe() {
    var script = renderer.doc.createElement('script');
    script.text = "\
      var swiper = new Hammer(document);\
      swiper.on('swipeleft', function() {\
        parent.Book.nextPage();\
      });\
      swiper.on('swiperight', function() {\
        parent.Book.prevPage();\
      });";
    renderer.doc.head.appendChild(script);
  }
  EPUBJS.core.addScript('https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.6/hammer.min.js', detectSwipe, renderer.doc.head);
  if (callback) {
    callback();
  }
};
```

**Comment by naeimrezaeian** [comment]
MifRea1 thanks for your help - can you send full source code!! 
i add this code but doses`t work swipe page

**Comment by MifRea1** [comment]
I've added a couple of new lines to [the first example](https://gist.github.com/MifRea1/cac929a11228b4d1abb3#file-single-html-L50-L67).

**Comment by Mrjaid** [comment]
For anybody having same issue with me, I modified @yinhaibo , I replaced 
 parent.Book.nextPage();
with 
 this.parent.document.getElementById("prev").click();
that is : 

EPUBJS.Hooks.register("beforeChapterDisplay").swipeDetection = function (callback, renderer) {

                function executeScriptAfterLoad() {
                    //-- Create a script element, you could also load this from an external file like above
                    var script = renderer.doc.createElement("script");
                    //-- Listen for swipe events
                    script.text = '\
                $(window).on("swipeleft", function() {\
                       this.parent.document.getElementById("next").click();\
                });\
                $(window).on("swiperight", function() {\
                 this.parent.document.getElementById("prev").click();\
                });';
                    renderer.doc.head.appendChild(script);
                }

                //-- Load jQuery into iframe header

                EPUBJS.core.addScripts(["../../../reader/js/libs/jquery.min.js",
                    "../../../reader/js/libs/jquery.mobile.js"], executeScriptAfterLoad, renderer.doc.head);
                if (callback)
                    callback();
            }

**Comment by yinhaibo** [comment]
@Mrjaid maybe the Book object is cannot access from iframe, parent.Book is assume that it is a global variable in parent document.

**Comment by Mrjaid** [comment]
yeah I am currently working with the hypothesis example.. i can see it has alot of hooks added

**Comment by drorwr** [comment]
Here's what worked for me.

Create a file inject.js that has in it:
`$(window).on('swipeleft', () => {
  parent.rendition.next();
});

$(window).on('swiperight', () => {
  parent.rendition.prev();
});
`

And to inject it into the epub do:

` rendition.hooks.render.register((view) => {
      view.contents.addScript('https://cdn.jsdelivr.net/jquery/3.0.0-beta1/jquery.min.js')
        .then(() => view.contents.addScript('https://cdnjs.cloudflare.com/ajax/libs/detect_swipe/2.1.1/jquery.detect_swipe.min.js'))
        .then(() => view.contents.addScript('/js/inject.js'));
  });
`

Keep in mind:
* adjust the path to inject.js
* make sure to call your rendition "rendition" or adjust the above code.
`

**Comment by drorm** [comment]
Need to add the previous comment:
In the parent window you need to set

`  window.rendition = rendition;`

So that the reference to parent.rendition will work.

**Comment by sengemann** [comment]
I just came up with an even simpler solution this morning (working with `v0.3`):

```JavaScript
let touchStart = 0;
let touchEnd = 0;

rendition.on('touchstart', event => {
  touchStart = event.changedTouches[0].screenX;
});

rendition.on('touchend', event => {
  touchEnd = event.changedTouches[0].screenX;
  if (touchStart < touchEnd) {
    // Swiped Right
  }
  if (touchStart > touchEnd) {
    // Swiped Left
  }
});
```

**Comment by dannwise** [comment]
Hi @sengemann, could you please share the complete example of your solution? I couldn't figure it out on my own.

**Comment by dghag** [comment]
-----------------------------------------------------------
Attention: Non-Delivery Report
-----------------------------------------------------------

This report is generated by the email server at:

       witsindia.com

The message with subject:

       "Re: [futurepress/epub.js] Page swipe left / right functionality is missing (#46)"

and attached to this report was not delivered to 
the following recipients:

Address: dipika.ghag@witsindia.com
Reason:  User not found (550)
--------------


-- 
http://www.wits-interactive.com <http://www.wits-interactive.com>
Copyright 
to all designs remains with the WITS Interactive, unless assigned in 
writing. Only WITS Interactive has the right to reproduce the design and 
has commercial right over the same. Any extension or modifications or 
reproductions or use of the design in any form electronically or in print 
or in any other way, other than the contract with WITS Interactive must be 
agreed with the WITS Interactive in writing. Copyright to all modules, 
designs, images, visualizations, graphics, photography or illustration 
remains with the WITS Interactive


All the data/ material provided above 
are under the copyright of M/s WITS Interactive and should not be 
reproduced in any form, electronically or in print or in any other way, 
without the prior consent of any authorized representative of M/s WITS 
Interactive Pvt. Ltd. Suitable action will be taken against those failing 
to comply. Copyright M/s WITS Interactive.
