### ISSUE TITLE
wordpress plugin

### ISSUE THREAD

**Issue by panshengjie** [futurepress/epub.js#468]
is epub.js planning to make a wordpress plugin in the near future?

**Comment by adamsargant** [comment]
I think that is something anyone familiar with WP plugins could do (I've made a start myself, but you know, time :-) )

**Comment by fchasen** [comment]
I think that would make a great project, but not currently in the works.

@JakeHartnell any interest?

**Comment by JakeHartnell** [comment]
Hah, I am a bit busy with https://github.com/CommonGarden/Grow-IoT at the moment, but like @adamsargant says, it's something that anyone familiar with Wordpress could do. : )
