### ISSUE TITLE
npm 0.3. is it possible?

### ISSUE THREAD

**Issue by paulocheque** [futurepress/epub.js#476]
There is a release for that?

Thanks in advance

**Comment by fchasen** [comment]
Not yet, I'll add it as a pre-release shortly

**Comment by fchasen** [comment]
I'm now publishing the v0.3 releases under the `beta` tag on NPM.

To get the latest by add the following to your `package.json`:
```
"epubjs": "beta"
```

**Comment by michelem09** [comment]
Please could you add also bower?
