### ISSUE TITLE
Problem loading epub file from url w/o .epub extension

### ISSUE THREAD

**Issue by hypersonic64** [futurepress/epub.js#479]
Hi,
I need to display epub files that are loaded from a server using a url like 
http://server.com/media.php?id=12345
This request causes the server to deliver a epub file content using mimetype "application/epub+zip".

During loading a js error is thrown "Uncaught TypeError: Cannot read property 'then' of undefined in epub.js 5612" in Book.prototype.open(), obviously because the script doesn't know how to handle the data and expects uncompressed files.

However, if use a url like http://server.com/media/test.epub all works well. But this is not possible, cause the epub files are not directly accessable from client.

Is there any way to tell the script to handle the incoming data as compressed epub file?
Or any other parameter I can use in the options?

Thanks a lot,
Hyper

**Comment by fchasen** [comment]
You can force it handle the books as contained epubs by passing: 
```
var Book = ePub("http://server.com/media.php?id=12345", { contained: true });
```

**Comment by hypersonic64** [comment]
yessss, works now with new v0.2.15.
Thank you so much!
