### ISSUE TITLE
Cannot use displayChapter or goto to display XHTML files from TOC

### ISSUE THREAD

**Issue by geek1011** [futurepress/epub.js#481]
I cannot use goto or displayChapter to open a TOC link to a XHTML document. 

When I use book.displayChapter("chapter_001.xhtml") or book.goto("chapter_001.xhtml") it does not do anything. FYI, my code is in https://github.com/geek1011/BookReader/blob/master/App/js/reader.js#L190-L212

This can be replicated with almost all the books from the [epub test suite](http://epubtest.org/testsuite/).

**Comment by fchasen** [comment]
That shouldn't be an issue, it is the way the demo here works: http://futurepress.github.io/epub.js/reader/

It sounds like it can't find that chapter in the spine, I will need to try to reproduce it.

**Comment by geek1011** [comment]
Try it with my eBook reader http://geek1011.github.io/BookReader and one of the epub test suite books.

On Oct 30, 2016 5:39 PM, Fred Chasen <notifications@github.com> wrote:

That shouldn't be an issue, it is the way the demo here works: http://futurepress.github.io/epub.js/reader/

It sounds like it can't find that chapter in the spine, I will need to try to reproduce it.
