### ISSUE TITLE
Generate pagination with custom css

### ISSUE THREAD

**Issue by geek1011** [futurepress/epub.js#482]
I am using the following code in my project http://github.com/geek1011/BookReader to have a consistent way to generate the pagination across different window sizes:

``` javascript
        book.generatePagination(600, 600).then(function() {
            console.log("Pagination generated: " + String(book.pagination.totalPages) + " pages");
            setInterval(function() {
                $(".pagenum").text("Page " + String(book.pagination.pageFromCfi(book.getCurrentLocationCfi()) + " of " + String(book.pagination.totalPages)));
            }, 500);
        });
```

The problem I am having is the pagination changes with different font sizes. Is there a way to set the css for just the pagination generation so I can have consistent pages for each book across different font settings?

**Comment by fchasen** [comment]
Could you try using the locations generation instead? It uses the content to create locations, so it will always be the same and not dependent on the css.

https://github.com/futurepress/epub.js/blob/master/examples/locations.html
