### ISSUE TITLE
Errors in Firefox while opening epubs with images

### ISSUE THREAD

**Issue by movsky** [futurepress/epub.js#484]
In Firefox I always get Errors when epubs containing images. Chrome works good, but Firefox has some trouble. I could not figure out what the problem is.

Every time the image is shown this error message shows up in console:

`error { target: <img>, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1476886214232890, originalTarget: <img>, explicitOriginalTarget: <img>, NONE: 0, CAPTURING_PHASE: 1 }`

**Comment by movsky** [comment]
![screenshot from 2016-10-20 12-40-22](https://cloud.githubusercontent.com/assets/3482728/19556667/6ebca098-96c2-11e6-8e83-9c36e7e4de92.png)

Get this every time the image is shown, so also when navigating through epub.

**Comment by fchasen** [comment]
Perfect, thanks for the screen grab. I'll investigate tomorrow.

**Comment by movsky** [comment]
Hey, no hurries, but could find out anything? :)

**Comment by fchasen** [comment]
I'm getting this as well, image still loads and displays fine but that error always fires even if I don't change the image src at all. I think it is safe to just remove the listener as there is a max timeout anyway.
