### ISSUE TITLE
How to epub. Js read file streams

### ISSUE THREAD

**Issue by hanbingxu** [futurepress/epub.js#486]
I want to take advantage of epub. Js to read through the server returns the file, could I do?

**Comment by fchasen** [comment]
This isn't currently possible but I am actively working on making the loading and parsing work with node.js. One big part of this will be accepting file streams.

**Comment by perlegocallum** [comment]
Hi @fchasen,

Really interested in the loading and parsing on node.js  Any idea when you will be finished?

**Comment by hrkazemi** [comment]
hi @fchasen,
does it support stream or render part of epub file?

**Comment by bentzibentz** [comment]
Is this working now? And if so is there any example or documentation about it? Can't find anything.
