### ISSUE TITLE
how the pagination works

### ISSUE THREAD

**Issue by kiyos88** [futurepress/epub.js#490]
@fchasen can you tell me how the pagination works, based on the width and height supplied if you can show me in plain html 10q

**Comment by fchasen** [comment]
The HTML chapters are paginated by adding css columns styles to the document element in `src/layout.js`. For instance here is the code for adding the reflowable spreads: https://github.com/futurepress/epub.js/blob/master/src/layout.js#L107-L110

Happy to discuss more on [gitter](https://gitter.im/futurepress/epub.js)
