### ISSUE TITLE
v0.3: selected / selectedRange event not being triggered on rendition

### ISSUE THREAD

**Issue by Rkallenkoot** [futurepress/epub.js#494]
Hi there,

Currently unable to receive the "selected" or "selectedRange" event via rendition.on() .

```
rendition.on("selected", function(cfiRange) {

});
```

I've checked and the event is being fired within the Iframe. Do you by any chance have an idea what could cause this?

Cheers!

**Comment by fchasen** [comment]
Rendition was listening to the view instead of to the contents, should be working now in v0.3.6

**Comment by anatoly314** [comment]
`selectedRange` event still doesn't work

**Comment by sepehr09** [comment]
the `rendition.on('selected')` event is not working! i'm using v.3.

code:

```js

rendition.on('selected', function(cfirange, contents) {
    console.log(cfirange, contents)
});
```

as i checked i found the problem maybe is that the event `this.emit(EVENTS.CONTENTS.SELECTED, cfirange)` witch inside the `triggerSelectedEvent` function in the `contents.js` is NOT captured by `contents.on(EVENTS.CONTENTS.SELECTED)` in `rendition.js` file. 

for testing i'm emitted simple `foo bar` event inside `contents.js` file but i didn't recieve any event inside `rendition.js` file. 

any idea?

**Comment by Gina0421** [comment]
when  I used  "rendition = book.renderTo("viewer", { width: '90%' });" The selected can be triggered.
I guess the settings make the "selected" not triggered possibly.
