### ISSUE TITLE
Error while opening ebook

### ISSUE THREAD

**Issue by gmastergreatee** [futurepress/epub.js#496]
![kol](https://cloud.githubusercontent.com/assets/17880848/20168841/21e9c26c-a74a-11e6-9077-c0af7468237d.gif)

**Comment by fchasen** [comment]
Can you post the error?

It seems likely that you need to pass `"contained" : true` in your settings if the book you are using is a .epub and the link doesn't say that.

**Comment by gmastergreatee** [comment]
Well, the epub file wasn't opening the way as was stated in the documentation but I will try passing the contained parameter.
