### ISSUE TITLE
ERROR examples/pagination.html  "_ is not defined(…)"

### ISSUE THREAD

**Issue by georgezouq** [futurepress/epub.js#498]
<img width="545" alt="2016-11-16 12 02 43" src="https://cloud.githubusercontent.com/assets/5990860/20312924/2072f864-ab90-11e6-9f21-df077564aa14.png">

This error near 
```javascript
            var throttledSlide = _.throttle(slide, 200);
            var mouseDown = false;
```
in examples/pagination.html

Is something missing??

**Comment by fchasen** [comment]
Removed the underscore but I highly suggest using the `locations.html` example instead. This one is very resource intensive.
