### ISSUE TITLE
Save pageList to database but generatePagination are incorrect

### ISSUE THREAD

**Issue by georgezouq** [futurepress/epub.js#520]
Hi! I use `generatePagination` to get pageList and save it to database.Next time when user visit, I will get pageList from database.But I get the num is incorrect. 2 - 4 pages will be compute as one page.
Is it because there are too many pictures? or I miss something?.I read the source code and I see when generate pagination it will execute renderer's `mapPage` function.Can I get more information about how this function compute pagination,so I can do something for that.

**Comment by georgezouq** [comment]
and when execute `generatePagination`,I got error like this.Is it because load image error and not compute with image's height? Url is not right. How can I set the right Url?
<img width="612" alt="2016-12-12 11 48 28" src="https://cloud.githubusercontent.com/assets/5990860/21105693/20e8844e-c0c6-11e6-911b-b4cf66a28316.png">

**Comment by fchasen** [comment]
Generate pagination isn't a good solution to page numbering and will be removed soon.

I'd recommend using Location as per this example: https://github.com/futurepress/epub.js/blob/master/examples/locations.html

**Comment by georgezouq** [comment]
@fchasen  But user always want pageNum
