### ISSUE TITLE
CFIs for TOC items and pagination items

### ISSUE THREAD

**Issue by Sunil-bb** [futurepress/epub.js#532]
@fchasen 
TOC items: 
Is it fine to generate CFIs for each of the TOC item as it planned (but no yet implemented) for pagination  items?
If yes, have few queries before I start implementing:
1.) Need to support Simple, Multi-level and  hidden attribute .
2.) To support multi-level, there is a need to load XHTML(content) files to browser. Is there a way where I can implement generating CFI without loading XHTML(content) into browser.

It would be great if you can suggest on the above . We can work on implementing it based on your suggestion.

**Comment by fchasen** [comment]
I think I understand what you are building, but not completely sure.

Are you trying to generate a cfi for each of the items in the ToC? That sounds pretty useful!

You can generate the cfi without rendering the content, but you will need to load it first as a section, find the element the ToC refers to with something like `el = section.document.getElementById("sect1")`  and then call `section.cfiFromElement(el)` to get the cfi.

**Comment by Sunil-bb** [comment]
Thanks for the reply Fred. 
Right. We are trying to generate CFI for each of the TOC entry during book load. But loading everything as section during book load seems to be very costly.  I guess we can drop the idea of creating CFI for TOC entry, hence closing the issue.
