### ISSUE TITLE
v0.3 Next-navigation in single column spread fails to load a new chapter

### ISSUE THREAD

**Issue by gerhardsletten** [futurepress/epub.js#534]
Hi, is there a bug in this code:
[src/managers/default/index.js (Line 283)](https://github.com/futurepress/epub.js/blob/v0.3/src/managers/default/index.js#L283)

What is the purpose of the the `else if` below, in a single spread layout at the end of a chapter it is called, causing the next chapter not to be loaded in.

```
if(left < this.container.scrollWidth) {
  this.scrollBy(this.layout.delta, 0);
} else if (left - this.layout.columnWidth === this.container.scrollWidth) {
  this.scrollTo(this.container.scrollWidth - this.layout.delta, 0); // <---- This line
} else {
  next = this.views.last().section.next();
}
```

**Comment by fchasen** [comment]
The purpose of this was to avoid over scrolling the end of chapter but it should be changed to also be loading the next chapter as well as scrolling.

**Comment by Sunil-bb** [comment]
@fchasen @gerhardsletten 
Raised https://github.com/futurepress/epub.js/pull/542
Please review and merge

**Comment by Sunil-bb** [comment]
@gerhardsletten 
This issue has been fixed. Please check and close the bug.
