### ISSUE TITLE
book.renderTo("divelement") not loading content

### ISSUE THREAD

**Issue by arjunmichel** [futurepress/epub.js#548]
a. We have an issue of epub book is not rendering to html div area.
b. while after debugging epub.js library , for the below url: 
https://s3.amazonaws.com/skillsoft-qa-cp-cdn/books/37616/OEBPS/ch01.xhtml
c. in epub.js for the below method which is responsibel for getting content for epub,  getting response as null.
     EPUBJS.core.request = function(url, type, withCredentials) //the url is above url

**Comment by fchasen** [comment]
I'd be happy to debug more with you on our gitter.
