### ISSUE TITLE
v0.3 Books with padding in the body cause the text to be cut off and affect the iframes movement

### ISSUE THREAD

**Issue by imefisto** [futurepress/epub.js#553]
We're moving from v0.2 to v0.3. I've noted that if a book has padding left/right in its stylesheet, the text in the iframes starts to be cut off.

To reproduce, I've prepended the following line to the file OPS/css/stylesheet.css from moby dick epub:

```
body {
  padding: 0 15px;
}
```

After the change, if you reload the example "spreads.html", you should see how the padding affects the iframes movement.

It can be mitigated by using a hook but I don't know if the hook is the best way:

```
contents.addStylesheetRules([
  ["body",
    ["padding", "0 !important"]
  ]
]);
```

**Comment by fchasen** [comment]
I'm seeing this as well in a number of books.

I've removed the padding from body inside the column method in Contents for the `0.3.13` release.
