### ISSUE TITLE
Generating Page Numbers

### ISSUE THREAD

**Issue by ClarenceR89A** [futurepress/epub.js#559]
Hi, 

In regards to generatePagination(w, h), how would i determine a default width and height for the books so that pagination would be the same as RMSDK(iOS) generated paging? 

What i need is a way to open my books in epubjs, in such a way that my paging is not coupled to the size of my div i am rendering to(book must be reflow-able), but where i will have a number of pages consistent with RMSDK(iOS).

I need this for reporting reasons so pages in the book will always be generated consistently across devices.

Any suggestions for how to generate the page numbers consistent with RMSDK(iOS).

Thanks,
CLR89A

**Comment by fchasen** [comment]
So sorry for the lack of documentation around pagination / locations.

The example here should generate the location information you are looking for irregardless of page size.

https://github.com/futurepress/epub.js/blob/master/examples/locations.html
