### ISSUE TITLE
version3.3.3   Book.nextPage(); Book.prevPage(); can not work with  keydown event  but it works in version  3.1.0

### ISSUE THREAD

**Issue by weijingxu** [futurepress/epub.js#560]
$(document).keydown(function(event){
      console.log(event.keyCode);
     if(event.keyCode==37){
         Book.prevPage(); 
      }
      if(event.keyCode==39){
         Book.nextPage(); 
      }
    });

**Comment by Copylefter** [comment]
How did you fix it?
