### ISSUE TITLE
Use epub.js to load file from document directory of iOS

### ISSUE THREAD

**Issue by anoop4real** [futurepress/epub.js#569]
Hi,

I am planning to use epub.js to load a downloaded epub and display in a WkWebview. In my iOS app I am downloading the epub from a remote location and saving it in the Documents directory of the app. In my WkWebview I am going to embed epub.js. Now how to tell epub.js to pick the file from the documents directory? Is this possible at all?
Especially here

```
<script>
   ---> var Book = ePub("Path to iOS directory??");<---
    Book.renderTo("area");
</script>
```

**Comment by fchasen** [comment]
If the webview has access to the local filesystem something with a path starting with `file://` might work. I'd recommend running a local webserver to access the files, such as https://github.com/swisspol/GCDWebServer

**Comment by anoop4real** [comment]
Hi,
WKWebview has access to file system via `file://` protocol, I am able to load saved htmls, but when I try to load an epub using epub.js it doesnt work, doesnt throw any exception or errors. Any pointers?

**Comment by GoldenStar1024** [comment]
I have the same issue

**Comment by GoldenStar1024** [comment]
Did you fix this issue?

**Comment by anoop4real** [comment]
I am using GCDWebserver now, I am saving all  files to a folder in the app and then I am starting a GCDWebserver in that folder, so that epub js can access it via http/https

**Comment by GoldenStar1024** [comment]
Hi,
Thanks for your help.

I am using epub.js to load a downloaded epub and display in a WkWebview. In my iOS app I am downloading the epub from a remote location and saving it in the Documents directory of the app. In my WkWebview I embed epub.js and I am loading the file from the documents directory in epub.js.
There are the html and javascript files in the resource folder.
How can epub js can access it via http?

**Comment by GoldenStar1024** [comment]
NSString* documentsPath = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) firstObject];
  self.webUploader = [[GCDWebUploader alloc] initWithUploadDirectory:documentsPath];
  [self.webUploader start];

-------

  NSString* path = [NSString stringWithFormat:@"%@%@", delegate.webUploader.serverURL, filename];

---
js file:
      epub = ePub(path, {
        minSpreadWidth: false,
        width: bookData.width,
        height: bookData.height,
        styles: { 'font-size': bookData.fontSize }
      });

**Comment by Asterism1985** [comment]
Hi,
I have the same issues.
Please help me.

**Comment by anoop4real** [comment]
Use the getHandler method of GCD 

`webserver` is just an instance of GCDWebserver
```
  webServer.addGETHandler(forBasePath: "/", directoryPath: documentsPath, indexFilename: nil, cacheAge: 3600, allowRangeRequests: true)
            webServer.start(withPort: 0, bonjourName: nil)
```

The above snippets will start GCD in the documents path after that you can access all the files that are dumped in the documents path via http://localhost:port

```
    func getFilePath() -> String {
        return "http://localhost:\(webServer.port)/file/test.html"
    }
```

**Comment by Asterism1985** [comment]
Hi, 

Thanks for your reply.
Can I use it without uploading the files to the server when I downloaded the files dynamically into the document folder ?

**Comment by anoop4real** [comment]
Yes, GCDWebServer is a framework which creates a webserver internally in a folder with in the app, you dont need to upload anything, check the documentation 
[https://github.com/swisspol/GCDWebServer](url)

**Comment by Asterism1985** [comment]
Hi,
I saved all files in the document directory and then I am starting a GCDWebserver in that folder.
But I can't load the js file in the html.
Please help me.

<!DOCTYPE html>
<html>

<body>
  <div id="book"></div>
  </div>
  <link rel="stylesheet" href="ebook.css">
  <script type="text/javascript" src="epub.min.js"></script>
  <script type="text/javascript" src="ebook.js"></script>
</body>

</html>

-----

self.webServer = [[GCDWebServer alloc] init];
  [self.webServer addGETHandlerForBasePath:@"/" directoryPath:documentsPath indexFilename:nil cacheAge:3600 allowRangeRequests:YES];
  [self.webServer startWithPort:8999 bonjourName:nil];
 
----

   NSString* documentsPath = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) firstObject];
    NSString *htmlPath = [documentsPath stringByAppendingPathComponent:@"ebook.html"];
    NSString *html = [NSString stringWithContentsOfFile:htmlPath encoding:NSUTF8StringEncoding error:nil];
    AppDelegate* delegate = (AppDelegate*)[[UIApplication sharedApplication] delegate];
    [_webView loadHTMLString:html baseURL: delegate.webServer.serverURL];
    [self addSubview:_webView];

**Comment by anoop4real** [comment]
Hi,
Please do the below steps
1. After startWithPort, please log the below variable
`webServer.serverURL`, you can also look for logs like below
`GCDWebServer started on port 12997 and reachable at  http://localhost:12997/`

2. Keep the app running, and copy the url and paste it in any browser, firefox/ safari etc. If this are configured properly, you will be able to see all the files in document directory there.

3. If the above step is success, instead of giving the document path as html path, you should give html path as 
'http://localhost:\(webServer.port)/ebook.html'

**Comment by Asterism1985** [comment]
Hi 
Thanks for your help.
But it is not working.
The server started the correctly and I called the HTML in wkweb view.
But I can't load the JS files in the HTML too.

    AppDelegate* delegate = (AppDelegate*)[[UIApplication sharedApplication] delegate];
    NSURL *htmlUrl = [NSURL URLWithString:[NSString stringWithFormat:@"%@ebook.html", delegate.webServer.serverURL]];
    [_webView loadRequest:[NSURLRequest requestWithURL:htmlUrl]];
    [self addSubview:_webView];

http://192.168.0.53:8999/ebook.html

**Comment by anoop4real** [comment]
Hi,
If you can sent me the project, probably I can try debugging and find it out.

-anoop

**Comment by aehlke** [comment]
Did y'all figure it out?

**Comment by OriIdan** [comment]
What I did was copy epub.js and all my HTML files to document directory and simply open a webview to view the book.
