### ISSUE TITLE
eBooks work locally, but not online

### ISSUE THREAD

**Issue by MC2013** [futurepress/epub.js#57]
I would greatly appreciate any help here.

I setup epub.js as per documentation and examples and it works superbly on my PC locally (Windows 8), but for some unknown reason to me, it is perpetually loading when I try to open eBooks online. Uploaded all files by ftp transfer to the hosting server.

Am I missing something here? I am really perplexed and a bit lost at this point.

**Comment by ssaleem-pikessoft** [comment]
> I figured out where the problem was. It's the server not having a specified MIME type for ".epub" files and so it does not know how to 'treat' it. I went under "user-configurable IIS settings" in IIs Administration Console and custom assigned ".epub" to "application/epub+zip" MIME type. The epub files are working now with the script above.
> 
> Thanks you guys for your help.

This also work for me
