### ISSUE TITLE
Resize event on paginated view causes to revert to beginning of 'section' rather than remember location

### ISSUE THREAD

**Issue by boolieman** [futurepress/epub.js#572]
If you use an ebook heavy with images, it loses its current location CFI and reverts to the beginning of the section if not the whole image is viewable. Currently working on finding a workaround for myself but would love to contribute to finding a solution for this.

EDIT: So i have been banging my head on the desk with this for a bit, it seems that every time the page gets 'resized' it forgets its current location, attaching a `rendition.display(oldLocation)` does not seem to solve the issue, something inside the view manager may be causing an issue here.

**Comment by boolieman** [comment]
This seems to be a sister issue to the images not navigating properly

**Comment by pravid** [comment]
Any solution on this?
