### ISSUE TITLE
Issue with WKWebView in IOS

### ISSUE THREAD

**Issue by anoop4real** [futurepress/epub.js#580]
Hi,

I am trying to use epub.js to render my epubs in a WKWebView. I am using epub's previous and next methods to navigate between the pages. Now the issue that I am facing is that, if the pages is very long the scroll contentsize of WKWebview is not getting adjusted. It is always the same as it is the first page, because of which the content of long pages are cut off. Since the navigation is completely taken care by epub.js....none of the wkdelegate method are invoked, so there is no handle back to iOS. Any help would be appreciated.

**Comment by anoop4real** [comment]
Or is there a tutorial to integrate epub.js with WKWebView?

**Comment by rhussell** [comment]
In render_iframe.js, 

EPUBJS.Render.Iframe.prototype.addIframe = function(){
	this.iframe = document.createElement('iframe');
	this.iframe.id = "epubjs-iframe:" + this.id;
	this.iframe.scrolling = this.scrolling || "no";
	this.iframe.seamless = "seamless";
	// Back up if seamless isn't supported
	this.iframe.style.border = "none";

	// For iOS safari
	// https://stackoverflow.com/questions/23083462/how-to-get-an-iframe-to-be-responsive-in-ios-safari
	this.iframe.style.width = "1px";
	this.iframe.style.minWidth = "100%";

	this.iframe.addEventListener("load", this.loaded.bind(this), false);

	if (this._width || this._height) {
		this.iframe.height = this._height;
		this.iframe.width = this._width;
	}
	return this.iframe;
};

**Comment by JakeHartnell** [comment]
> Or is there a tutorial to integrate epub.js with WKWebView?

This would be great, though questions like this belong in the [forum](https://groups.google.com/forum/#!forum/epubjs). @anoop4real, was @rhussell's code snippet helpful?

**Comment by gual** [comment]
Not @anoop4real but I was having the same issue and @rhussell code snippet was the solution. Thanks!
