### ISSUE TITLE
Firefox 54.0 reader crashes

### ISSUE THREAD

**Issue by AngelsDustz** [futurepress/epub.js#582]
When using the reader on firefox 54.* epubjs will slowly crawl into your memory cache untill it starts failing due to memory leaks.

**Comment by fchasen** [comment]
Any additional detail on reproducing this would be appreciated.

Did you use a specific epub? Was it zipped (.epub)?
Does it happen when paging through lots of chapter or just opening the epub?

**Comment by AngelsDustz** [comment]
It doesn't appear to be epub specific, it seems that just being on a page that has epub.js loaded long enough will cause it to fail by failing to allocate 'contents' variable. After that it will just keep increasing in memory usage if you refresh. Even when you don't cache any javascript it still fills the memory.

All of the epubs tested were zipped versions, tho the reader doesn't seem to have any issues with that its the moment it tries to draw it to the screen it will fail.

**Comment by AngelsDustz** [comment]
Just cloned the latest version and build it. Memory leak is still very pressent. It used up 4GB ram over the span of 1.5-2 hours.

I think its related to render part.

**Comment by KevinBeckers** [comment]
Is there already some info about this issue?

**Comment by AngelsDustz** [comment]
It still leaks memory, afaik the issue hasn't been pinned down to a specific thing.

**Comment by AngelsDustz** [comment]
I found a way to reproduce it for everyone.

1. Open firefox
2. Go to: http://futurepress.github.io/epub.js/reader/#epubcfi(/6/2[cover]!4/1:0)
3. Press F5 about 100 times and watch as it is taking a few gigabyte of ram.

It seems everytime you refresh it allocates about 10MB, it does this about 4/5 times, then it clears the stack but not all of it is cleared, aprox 20-30MB will be gone.

Loop that a few times and your memory is full.

**Comment by AngelsDustz** [comment]
I have managed to track this down to an issue in Firefox it self.
