### ISSUE TITLE
epub.js for vue(bundle tool webpack)

### ISSUE THREAD

**Issue by heng1025** [futurepress/epub.js#590]
When i use epub.js in vue project,it implict can't find vertx. And i find some library in github,the result is nothing for javascript. Who can tell me how to solve this problem.  Thanks a lot.

**Comment by fchasen** [comment]
Haven't used epub.js with vue before, though I'd love an example of this.
I don't think vertx is an issue with epub.js though, as there is no variable names that.

Feel free to re-open with a little more details (an example setup would be ideal).

**Comment by heng1025** [comment]
In my project, i use this lib by `import Epub from 'epub.js/build/epub.js` or `import Epub from 'epub.js`,
something has wrong.
when i use build tools,it hints below:
```
This dependency was not found:

* vertx in ./~/epub.js/build/epub.js

To install it, you can run: npm install --save vertx
> Listening at http://localhost:8088
```
next, according this hint, i install `vertx` by *npm* or *yarn*,below is the result:
```
λ c npm install --save vertx
npm ERR! code E404
npm ERR! 404 Not Found: vertx
npm ERR! 404
npm ERR! 404  'vertx' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

so,i check the source code ,and then i find this function
```
function attemptVertex() {
  try {
    var r = require;
    var vertx = r('vertx');    // which is the reason
    vertxNext = vertx.runOnLoop || vertx.runOnContext;
    return useVertxTimer();
  } catch (e) {
    return useSetTimeout();
  }
}
```

**Comment by mairasala** [comment]
has this been addressed?

**Comment by fchasen** [comment]
Ah that is from the RSVP library: https://github.com/tildeio/rsvp.js/blob/b1c4a3f3452b8bf8fa1a1542b5a55014dabba2ae/lib/rsvp/asap.js#L84

Not sure why it is causing issues with vue but you should be able to just list`vertx` as an external library in the webpack config.
