### ISSUE TITLE
Why use legacy library for v0.3?

### ISSUE THREAD

**Issue by boolieman** [futurepress/epub.js#600]
From reading web pack the difference is using polyfill on the url.js, why not always use polyfill on it and support more browsers from the get go? Is it that much more taxing to run it that a user would care which version (leagacy vs non-legacy) that they use?

**Comment by fchasen** [comment]
It also loads the babel polyfill which includes a ton of other polyfills for things like promises.

Additionally, I need to add xmldom to it to address a the xmlserialization in ie.

It's great to be able to use babel and webpack to have slim versions that take advantage of the latest browser features and a heavy version with all the needed polyfills.
