### ISSUE TITLE
when will v0.3 release?

### ISSUE THREAD

**Issue by epubreader** [futurepress/epub.js#602]
when will v0.3 release?
and how to show slider bar on reader page for v0.3?

**Comment by MrXyfir** [comment]
+1

Also curious about v0.3 release. Soon? A month or longer?

**Comment by georgezouq** [comment]
+1 too

**Comment by snsxn** [comment]
+1 too

**Comment by MrXyfir** [comment]
Anytime this year?

**Comment by JakeHartnell** [comment]
Soon.
