### ISSUE TITLE
v0.3.27, Cannot read property 'createBlob' of undefined

### ISSUE THREAD

**Issue by zarkone** [futurepress/epub.js#608]
I want to make package for CLJSJS of epub.js to use it in clojurescript application.

However, my use-case is a bit different from examples, because I want to grab epubs from urls like /api/files/127/download, which return epub file with Content-Disposition attachment; filename=my-book.epub.

I end up with this code which should work for me
(just as an example, because my actual code in cljs):

```
book = new ePub({replacements: "blobUrl"});
o = book.open("https://localhost:3000/api/files/127/download", "epub"); // Actually, same results with https://s3.amazonaws.com/moby-dick/moby-dick.epub
```

But I got an error:
```
book.js:404 TypeError: Cannot read property 'createBlob' of undefined
    at createBlobUrl (core.js:267)
    at resources.js:226
(anonymous)	@	book.js:404
```

#607

**Comment by zarkone** [comment]
Another similar error: 

```
epub.js:2835 Uncaught TypeError: Cannot read property 'width' of undefined
    at Contents.width (epub.js:2835)
    at Contents.columns (epub.js:3509)
    at Layout.format (epub.js:8919)
    at IframeView.reframe (epub.js:7995)
    at IframeView.resize (epub.js:7961)
    at IframeView.lock (epub.js:7825)
    at IframeView.size (epub.js:7805)
    at IframeView.render (epub.js:7745)
    at IframeView.display (epub.js:8126)
    at ContinuousViewManager.update (epub.js:7251)
```

**Comment by gimox** [comment]
+1
 i left the 0.3 branch, too many problem with blobUrl.
waiting for fix...

**Comment by zarkone** [comment]
@gimox this request was merged, but I still have some troubles with continuous scroll. Going to check it out in near future

**Comment by gimox** [comment]
@zarkone same here!

**Comment by gimox** [comment]
try with options.encoding = "binary", it render the page but with some error.

**Comment by zarkone** [comment]
Thanks a lot! Will try it. 

When I scroll, sometimes it just stops render new pages and I see this width related error.

**Comment by fchasen** [comment]
createBlob issue should be fixed now. Could you create a new issue with the `width` error so we can track that one down?
