### ISSUE TITLE
how to debug epub.js?

### ISSUE THREAD

**Issue by bizos** [futurepress/epub.js#610]
I use  node-inspector, node --debug server.js,  then I set first line on server.js, and first line one base.js, but don't work, when I access http://localhost:8080/examples/basic-dev.html , the breakpoint did not fired.
I also try npm devtool,  node --inspect ,  all are the same result.
Does anyone know how to debug epub.js? 
thanks.

**Comment by bizos** [comment]
I also place a breakpoint on book.js's EPUBJS.Book.prototype.nextPage function, but when I click the next button, the breakpoint didn't fired too.

**Comment by fchasen** [comment]
I think this could be better answered on gitter or in the forums.
