### ISSUE TITLE
how to read local epub file 

### ISSUE THREAD

**Issue by sachinsahu731** [futurepress/epub.js#640]
i give this line of url in my local file
ePub("file/moby-dick.epub")

i get the error in my console
Object {message: null, stack: "Error↵    at XMLHttpRequest.j (file:///F:/practise/local%20epub/epub.min.js:8:40632)"}
message
:
null
stack
:
"Error↵    at XMLHttpRequest.j (file:///F:/practise/local%20epub/epub.min.js:8:40632)"
__proto__
:
Object

**Comment by JakeHartnell** [comment]
You might have the wrong URL or path to the Epub. Please double check.

**Comment by sachinsahu731** [comment]
thanks a lot @JakeHartnell
