### ISSUE TITLE
NPM install size

### ISSUE THREAD

**Issue by jkrehm** [futurepress/epub.js#647]
The package size is quite large when installing via NPM/Yarn (136 MB). Almost all of that comes from the `books` directory (a git submodule?). I don't know of a way to ignore it during install. I think it needs to be done when publishing, perhaps via https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package.

Is that a possibility?

**Comment by JakeHartnell** [comment]
Yes, we just need a `.npmignore` file: https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by fchasen** [comment]
Thanks! Fixed in epubjs@0.2.21
