### ISSUE TITLE
Use epub.js to extract contents from .EPUB

### ISSUE THREAD

**Issue by matikbird** [futurepress/epub.js#659]
Hi.
Since this library can unzip and read the whole document without the need of server-side management; I was wondering if there's something like Parsing an Ebook.

Like..
epub(file).then(data){
var author = data.metadata.author;
data.chapters.forEach(function(text){
var html = text; 
})

I tried other libraries but it must work in browser only, without the need of a server.
Any thoughts on this?
@fchasen @JakeHartnell

**Comment by MrXyfir** [comment]
You might have already found a solution for this, but [jszip](https://github.com/Stuk/jszip) does the actual extracting. If you just want to access the files within the `epub` file then jszip can do that on its own. If you still want to use epub.js you can access the files through `epub.zip.zip.files` (at least in v0.2, not sure if it has changed in v0.3).

**Comment by fchasen** [comment]
With `v0.3` you can do something like:

```
const epub = ePub(url);

epub.loaded.spine.then((spine) => {
  spine.each((item) => {
    item.load().then((contents) => {
      console.log(contents);
    });
  });
});
```

**Comment by rafaelsaback** [comment]
In case someone have issues using the code provided by @fchasen, in my case I could only make it work by providing **this.book.load.bind(this.book)** as the argument to item.load did the job for me:
```javascript
this.book.loaded.spine.then((spine) => {
  spine.each((item) => {
    item.load(this.book.load.bind(this.book)).then((contents) => {
      console.log(contents);
    });
  });
});
```

**Comment by AndreiSoroka** [comment]
my solution:

```ts
import ePub from "epubjs";
import type Section from "epubjs/types/section";

export default async function getChaptersFromEpub(epub: string | ArrayBuffer): Promise<string[]> {
  const book = ePub(epub);
  await book.ready;

  const sectionPromises: Promise<string>[] = [];

  book.spine.each((section: Section) => {
    const sectionPromise = (async () => {
      const chapter = await book.load(section.href);
      if (!(chapter instanceof Document) || !chapter.body?.textContent) {
        return "";
      }
      return chapter.body.textContent.trim();
    })();

    sectionPromises.push(sectionPromise);
  });

  const content = await Promise.all(sectionPromises);
  return content.filter(text => text);
}

```

**Comment by Faxraddin** [comment]
I have an issue with displaying images. https://stackoverflow.com/questions/78998547/cant-extract-images-from-epub-file-by-using-epubjs
