### ISSUE TITLE
Version v0.3 page no binding by percentage

### ISSUE THREAD

**Issue by rohitpal99** [futurepress/epub.js#670]
Hi,
Version v0.3 has introduced new APIs for getting locations from cfids like 

> percentageFromCfi
> pageFromCfi

I would like to have page no from currentLocation but I always get -1 value from **_pageFromCfi_** api 
In v0.2 I could have used pageListReady, but it is not available in v0.3
Please suggest a way to do this.

Found identical issue #386

**Comment by fchasen** [comment]
Unless the epub you are working with has a pageList, those will return -1.

You can generate locations with `book.locations.generate()` and then percentages will be reported with currentLocation.

See the [locations example](https://github.com/futurepress/epub.js/blob/v0.3/examples/locations.html) for a more detailed setup.
