### ISSUE TITLE
index.js?6d1f:551 Uncaught TypeError: Cannot read property 'spread' of undefined

### ISSUE THREAD

**Issue by epubreader** [futurepress/epub.js#687]
index.js?6d1f:551 Uncaught TypeError: Cannot read property 'spread' of undefined
    at ContinuousViewManager.updateAxis (index.js?6d1f:551)
    at ContinuousViewManager.updateFlow (index.js?d7b9:892)
    at Rendition.flow (rendition.js?fd4f:584)
    at Rendition.start (rendition.js?fd4f:213)
    at Queue.dequeue (queue.js?2df4:81)
    at eval (queue.js?2df4:133)

`    // Load the opf
    var book = ePub("http://localhost:8080/hollywood.zip/");
    var rendition = book.renderTo(document.body, {
        manager: "continuous",
        //flow: "paginated",
        //flow: "scrolled-continuous",

        width: "100%",

    });

    var currentSectionIndex = undefined;
    var displayed = rendition.display(currentSectionIndex);

    displayed.then(function(renderer){
        // -- do stuff
    });

    // Navigation loaded
    book.loaded.navigation.then(function(toc){
        // console.log(toc);
    });
`

**Comment by epubreader** [comment]
epub v0.3 not working for continuous scrolled

**Comment by fchasen** [comment]
Fix is published in `epubjs@0.3.58`

**Comment by BBoyBreaker** [comment]
I have version 0.3.58 and it seems doesn't fixed yet

**Comment by endigo** [comment]
@fchasen Hi, Please rebuild this version. An error is not fixed in v0.3.58.
