### ISSUE TITLE
Memory leak when using zipped epubs.

### ISSUE THREAD

**Issue by jmwierzbicki** [futurepress/epub.js#688]
Whenever epub is loaded with zipped file, it allocates object for given book, this causes constant increment in memory size.

This example shows heap snapshot for 4 iterations of same book loading.

![image](https://user-images.githubusercontent.com/11833720/33273152-ba83bffe-d38c-11e7-9129-91d6ca31b7a0.png)

![image](https://user-images.githubusercontent.com/11833720/33273208-e33104c0-d38c-11e7-8898-1e95595bc5e0.png)

every time before opening new epub, im destroing book object by book.destroy() but this doesn't seems to remove this object from memory

**Comment by fchasen** [comment]
Thanks, I'll take a look why the zip is not being released.

**Comment by fchasen** [comment]
Zip should be released in v0.3, but may require calling `book.destroy()` to trigger clean up.
