### ISSUE TITLE
example android-patch.html not works because of losing RSVP lib

### ISSUE THREAD

**Issue by TangMonk** [futurepress/epub.js#690]
https://github.com/futurepress/epub.js/blob/86ba893a29e5fef57f79b8ec4ff94a869d327324/examples/android-patch.html#L22

**Comment by TangMonk** [comment]
and another libs also losing:

![image](https://user-images.githubusercontent.com/3498786/33366852-7e872b70-d527-11e7-8683-978b568a5727.png)

**Comment by fchasen** [comment]
That example has been removed.
