### ISSUE TITLE
Use http urls to load book instead of files from assets/book/ (locally) - Ionic App

### ISSUE THREAD

**Issue by Nipun04** [futurepress/epub.js#694]
How can we use http urls to load book in Ionic app using epubjs:

https://github.com/janpio/ionic-epubjs/issues/39#issuecomment-348685400

**Comment by Evolution0** [comment]
But you can? The Basic example actually does this, simply give it a url and not a filepath.

**Comment by jonatanrinckus** [comment]
Can't use a http urls here on plain html page. it returns:

 No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.

**Comment by Nipun04** [comment]
Do you have a solution ?

**Comment by jonatanrinckus** [comment]
The problem was on server side, or in azure blob in this case, just allowed CORS on azure blob and works.

**Comment by Nipun04** [comment]
I've tried everything 
but i'm unable to solve it.

I want to simply use such URLs ( http://maheshsinghsawant.scienceontheweb.net/moby-dick.epub ) to open epub file 
@jonatanrinckus @Evolution0
