### ISSUE TITLE
Highlight Text on current page

### ISSUE THREAD

**Issue by AmarTFT** [futurepress/epub.js#701]
I need to highlight some of the text shown on the page.
I am implementing search functionality and need to highlight the particular word. Please help.

**Comment by AmarTFT** [comment]
Found a workaround. You can get the html of the currently loaded chapter and alter it through JQuery. Here is what I did-
//Get the html of the chapter
 var displayHtml = $("#area>div>iframe").contents().find("body").html();

//Your code to highlight the particular text
displayHtml = displayHtml.replace(searchText, "<span style='background-color:yellow'>" + searchText + "</span>");

//Now Apply this html
 $("#area>div>iframe").contents().find("body").html(displayHtml);

Note: 'area' is the id of the div which is loading the epub.

**Comment by shakenovv** [comment]
Your code highlights only first text. 
To highlight ALL text use regexp, like this: 

displayHtml = displayHtml.replace(new RegExp(searchText, 'g'), "" + searchText + "");

**Comment by AmarTFT** [comment]
Yeah, later I had used regex to highlight all of them. Thanks !
