### ISSUE TITLE
Unable to search within the entire ePub

### ISSUE THREAD

**Issue by AmarTFT** [futurepress/epub.js#702]
I could find a function
 Book.currentChapter.find(searchText)

but this searches only current chapter. Please let me know if there is a function to search in the entire ePub as well?

**Comment by AmarTFT** [comment]
Closing this thread as I have implemented a work around to achieve the same.

I have searched for the text occurrences in current chapter and then moved to next one and searched there... kept on moving to chapters to cover all of them then finally landed the user at the page from where he/she had started search. Works fine.

**Comment by shakenovv** [comment]
Can you show how did you do it? please

**Comment by AmarTFT** [comment]
You can search text in current chapter using-
Book.currentChapter.find(searchText)

You can also move to next and prev chapter through in built functions of library.
So move to the first chapter. Search there and then move to next chapter. Keep doing this until you reach the last one.

You can get the list of chapters by Book.getTOC() function of library.

**Comment by geek1011** [comment]
For v0.3, I've added an [example](https://github.com/futurepress/epub.js/wiki/Tips-and-Tricks-(v0.3)#searching-the-entire-book) in the wiki.

**Comment by OpenSesyme** [comment]
Does anybody have a use example of @geek1011 's Code for searching entire book?
