### ISSUE TITLE
Font-size customizer?

### ISSUE THREAD

**Issue by enclary** [futurepress/epub.js#703]
Hello, like i know, epub.js create iframe and take all settings from css in .epub file, but maybe i can add stylesheet for all epub books on site without editing all loaded files, adding my fonts, styles e.t.c, maybe someone have a permission epub.js reader with customizer.

**Comment by Numilog** [comment]
Hello Enclary,
You can simply add style to the epub by using this : Book.setStyle("font-size", "1.2em");
This will add an font-size attribute on the <body> element

==> see the documentation : https://github.com/futurepress/epub.js/tree/master/documentation

**Comment by enclary** [comment]
I can use function call for Book.setStyle? and 2-3 tags in one spippet?

like Book.setStyle("font-size", "1.2em"; "color","white";"background", "#212121");

and it rewrite styles in css file from epub document?
________________________________
От: Thomas GERBIG <notifications@github.com>
Отправлено: 8 января 2018 г. 23:10
Кому: futurepress/epub.js
Копия: enclary; Author
Тема: Re: [futurepress/epub.js] Font-size customizer? (#703)


Hello Enclary,
You can simply add style to the epub by using this : Book.setStyle("font-size", "1.2em");
This will add an font-size attribute on the element

==> see the documentation : https://github.com/futurepress/epub.js/tree/master/documentation

**Comment by Numilog** [comment]
You can also add style by injecting a css file in the header :

Book.addHeadTag('link',{'rel':'stylesheet','href':'MyCustomCss.css'});

Just try it ;)

**Comment by enclary** [comment]
Okay, im working about light novel reading portal, and choise for reader your js framework, cuz she usefull for my terms, on this month im want end work reader pages, and if all be good, im link/fork it for u)

wanna, create online reader for epub files on server, with download, and customizer( mode"night/light" font-size,font-family) information about book,author e.t.c

so i'm try, im ui/ux desinger, but want create this project for people, now only reader without customizer, but maybe i can do it.

my js skill very low:D
________________________________
От: Thomas GERBIG <notifications@github.com>
Отправлено: 9 января 2018 г. 10:43
Кому: futurepress/epub.js
Копия: enclary; Author
Тема: Re: [futurepress/epub.js] Font-size customizer? (#703)


You can also add style by injecting a css file in the header :

Book.addHeadTag('link',{'rel':'stylesheet','href':'MyCustomCss.css'});

Just try it ;)

**Comment by libertab** [comment]
Hi,
I tried to use both book.addHeadTag and book.setStyle but it tells me they are not functions....
(while book alone it is defined).

Is there a new way to change font size and family?

thanks

**Comment by fchasen** [comment]
Yep! Have a look at the themes example https://github.com/futurepress/epub.js/blob/master/examples/themes.html

**Comment by looknear** [comment]
But, on scrolled view  - the iframe size stay the same... 
It is not adjusting to the changed content height.
in fact, in many cases - the iframe is cutting the inner page content. even in epub.js scrolled example.
