### ISSUE TITLE
Troubles with  epubs encoding utf-8 bom.

### ISSUE THREAD

**Issue by siabuba121** [futurepress/epub.js#706]
Opening those types of documents is not working  
![image](https://user-images.githubusercontent.com/22898048/34766049-1c2f6dc2-f5eb-11e7-9e4d-e6c6fb183e9e.png)
This is a screen of error that popup but after deep analysis it comes out that it is becouse of bom is there any posible quick solution to open that kind of docs?

**Comment by fchasen** [comment]
Are you using an archived epub?

If so, the byte order mark should be remove by this code: https://github.com/futurepress/epub.js/blob/5089717c0311029e0d9406dd9775f95587128395/src/unarchiver.js#L33-L37

Any chance you could send a link to an epub that is failing?

**Comment by siabuba121** [comment]
I cannot send it but i removed bom from file by the server side, so if there is no solution for opening not removing bom we can close this issue.

**Comment by fchasen** [comment]
Were you serving `.epub` files or unzipped files from the server?

**Comment by siabuba121** [comment]
it was epub file
