### ISSUE TITLE
v3: Issue with marks-pane package

### ISSUE THREAD

**Issue by gerhardsletten** [futurepress/epub.js#708]
@fchasen Please see pull request in the marks-pane, this package is not correctly transpiled to es5, so it will break in uglifyjs when webpack is runned with the -p parameter.

[https://github.com/fchasen/marks/pull/2](https://github.com/fchasen/marks/pull/2)

The best-practices is that in all packages on npm should point to a transpiled es5 version of their code in the `main` field.

**Comment by fchasen** [comment]
Thanks, updated
