### ISSUE TITLE
book.goto() does not change the page to the right point in the book

### ISSUE THREAD

**Issue by twmobius** [futurepress/epub.js#71]
I am experiencing something strange. I use a Greek (UTF-8) epub book with epub.js and although the reader works pretty good I've noticed something strange while browsing through the contents via the table of contents

Although I direct the library to goto to 'chapter18.html#page150" which is a valid anchor point (by doing a ```book.goto("chapter18.html#page150")```), I am not being sent to the correct point but a couple of pages later. 

I've tried the EPUB with your demo application directly (just replacing the path of the epub location) because initially I thought that it could be a problem with my custom layout but the same thing happens there as well. I am thinking the the spread layout doesn't work that good, perhaps because of the UTF-8 Greek contents.

Also I've tried the EPUB with iBooks and Calibre and didn't experience any problems.

Could you please advice me on how to debug this?

**Comment by JakeHartnell** [comment]
No demo, so nothing we can do... closing.
