### ISSUE TITLE
Page Cfi from percentage never works

### ISSUE THREAD

**Issue by prsolucoes** [futurepress/epub.js#716]
Hi,

Im trying use the function:
```
ebook.locations.cfiFromPercentage
```

But it always return "-1"

![image](https://user-images.githubusercontent.com/395096/35700856-571606ac-077b-11e8-965d-e65aa0b8864c.png)

**Comment by MrXyfir** [comment]
Did you generate locations first? `book.locations.generate(1000)`

**Comment by prsolucoes** [comment]
Hi.

No. But after you sad, it is working now :)

What the correct value to use? Always 1000?

**Comment by MrXyfir** [comment]
See https://github.com/futurepress/epub.js/blob/v0.3/src/locations.js#L38

I don't remember why I settled on 1000, it's been a while since I had to integrate that code into my reader. It works well for me though.

**Comment by prsolucoes** [comment]
Ok.

When i call ebook.generatePagination and resize the ebook with ebook.resize, i need call generatePagination again?

**Comment by MrXyfir** [comment]
Wait, are you on v0.2.X or v0.3.X? I've been referring to 0.3.

**Comment by prsolucoes** [comment]
Hi,

Im on master version.

Your solution is working.

But attached to this question i want understand other related thing, that is the generate pagination using the width/height.

I need call generatePagination every time that resize happens?

**Comment by MrXyfir** [comment]
Master version is 0.2. I *think* you need to regenerate pagination every time the size changes but I don't remember, it's been a while since I've used 0.2.

**Comment by prsolucoes** [comment]
Ok. I will use the version 0.3. What i need do in version 0.3?

**Comment by MrXyfir** [comment]
A lot. It is not an easy update at all, and the documentation is very bad. I don't remember everything needed to upgrade from 0.2 to 0.3, but it took me a few days and mostly I had to read the source code because the documentation was not good enough.

Now there is also 0.4 in the works and I'm not sure if 0.3 will continue to receive updates. Might be best to stick with 0.2, but it's up to you.

**Comment by MrXyfir** [comment]
Are you just starting a new 0.2 project? If so it'll be much easier to go to 0.3.

**Comment by prsolucoes** [comment]
Yes, im starting a new project. Do you have hangout or something like this? I downloaded 0.4 branch and im using it now.

**Comment by MrXyfir** [comment]
I don't know if 0.4 is ready for use yet, I haven't tried it. Currently using 0.3.58.

I must go for a while now. If you have any questions I'll try to answer them when I get back. Use the documentation that is available, the examples, and then the source code when needed. One thing to note is that 0.3 does not have pagination like 0.2, you only need to generate locations, and those locations will be fine if the size changes.

**Comment by prsolucoes** [comment]
Hi,

Im using version 0.3. I have a lot of questions now :) Too many things different.

1 - My epub file dont load more, but an amazon sample loaded:

```
var epubUrl = 'http://localhost:9000/ebook.epub'; // dont load
var epubUrl = 'https://s3.amazonaws.com/moby-dick/OPS/package.opf'; // load
var ebook = ePub(epubUrl);
```

2 - How to listen to page changed?

3 - How to get current page number and current page cfi and current page percentage?

Thanks.

**Comment by prsolucoes** [comment]
I get the infos using:

```
var percent = ebook.locations.percentageFromCfi(location.start.cfi);
var percentage = Math.floor(percent * 100);
var page = location.start.displayed.page;
```

But page is the page inside chapter/spine and not the global page. How can i get the global page number, like the old anchorPage?
