### ISSUE TITLE
Unable to open EPUBs

### ISSUE THREAD

**Issue by JZadd** [futurepress/epub.js#724]
Hello to whoever reads this...
I've been trying to use epub.js lately and it works just fine with the books that are uploaded here in the lib's github, and same with some epubs I have, but with there are others that I've not been able to read because it's presenting the next error:
![image](https://user-images.githubusercontent.com/28794233/36317472-2cf45388-130b-11e8-8f70-b983332b0b53.png)

The problem is that I don't know why it happens nor how to solve it; if anyone could help me or give me some guide on how to proceed, thanks.

BTW, sorry if my english isn't that good, it ain't my first language

**Comment by geek1011** [comment]
Which version are you using, and are you able to upload a copy of the book?

**Comment by JZadd** [comment]
I was using the version 0.2.15.  Changed to 0.2.21 and it now works...

But I have a doubt... ¿How do I use .epub compressed books? Haven't been able to use it compressed, only unzipped as a folder... Maybe (surely) I'm lacking something, but don't know what...
