### ISSUE TITLE
getBoundingClientRect on selection range returns 0 in RTL

### ISSUE THREAD

**Issue by cordoba-ro** [futurepress/epub.js#728]
This is for RTL books at https://www.quran.link/books/read/14/
There's no way to know the bounding rect for the selection so we can display a toolbar next to it
We're using v0.3 because previous versions didn't do paging correctly for RTL

**Comment by fchasen** [comment]
You can get a DOMRange from the CFI Range that is passed by the selected event.

```
rendition.on("selected", function(cfiRange, contents) {
   var range = contents.range(cfiRange);
   var rect = range.getClientBoundingRect();
   console.log(rect)
});
```

**Comment by hungnguyentiki** [comment]
> You can get a DOMRange from the CFI Range that is passed by the selected event.
> 
> ```
> rendition.on("selected", function(cfiRange, contents) {
>    var range = contents.range(cfiRange);
>    var rect = range.getClientBoundingRect();
>    console.log(rect)
> });
> ```

I think it should be `range.getBoundingClientRect()` instead of `range.getClientBoundingRect() `
