### ISSUE TITLE
What is the best version for usage? 2, 3 or 4

### ISSUE THREAD

**Issue by androidovshchik** [futurepress/epub.js#737]
Hi
There are a lot of versions of this library for choose
I know that 2 is stable (latest), 3 is beta and 4 is alpha
But i wonder which of these is prefered to use or please describe the best and the worst side each of them

**Comment by geek1011** [comment]
**2:** Works fine most of the time, best browser support, sometimes a bit slow, supports pagination, buggy with some epubs
**3:** More modular, only modern browsers, more modes (scroll/pagination/no iframe), slightly less stable, works better with epub3s
**4:** Basically the same as 3

Personally, I use 3, unless I need the browser support of 2. If you want to know more, you can ask a more specific question about your use case.

**Comment by MrXyfir** [comment]
I'm currently using v0.3 as well. Waiting for 0.4 to be finished. @geek1011 have you encountered any big problems with 0.4? I assume there's some reason you're still using 0.3?

**Comment by geek1011** [comment]
@MrXyfir I mainly use 0.3 due to the fact that it will change less than 0.4 (which is [being changed](https://github.com/futurepress/epub.js/compare/v0.3...v0.4) quite a bit). Also, 0.3 does everything I need.

**Comment by fchasen** [comment]
Version 3 (now master) is the version to use.

0.4 is mostly the same on the rendering side, but updates the parsing to use a Web or Service worker and isn't stable yet.
