### ISSUE TITLE
v0.3 iOS Cordova app loads an empty body

### ISSUE THREAD

**Issue by wnabil** [futurepress/epub.js#739]
I'm using epubjs v0.3 on a cordova based project using angular 5 framework, i am using the continues scroll example and after a lot of retries i got it working successfully on desktop and also on Android, But on iOS its rendering an empty body, the book is loaded and i can see and print the table of content but the content of the body inside the iframe doesn't have any element.

**Comment by wnabil** [comment]
Never mind it was a security issue and it is not related to epubjs
Thanks.

**Comment by pravinkumarputta** [comment]
> Never mind it was a security issue and it is not related to epubjs
> Thanks.

Hi @wnabil ,
I'm facing the same issue. Can you please tell me how did you solve this?
