### ISSUE TITLE
v2 -> v3 Cannot Open Zipped ePubs

### ISSUE THREAD

**Issue by jlag34** [futurepress/epub.js#746]
I'm moving from v2 to v3 and I can't open epub files anymore. If I use the example Moby Dick link ("https://s3.amazonaws.com/moby-dick/moby-dick.epub") I can load them no problem. However, if I try to load from my AWS link (https://s3.amazonaws.com/joe-test-bucket002/53930186-8735-4e49-891a-d0efaa869e95) I can't open the ePub.

In v2 I was passing { contained: true };

```
const Book = ePub('https://s3.amazonaws.com/joe-test-bucket002/53930186-8735-4e49-891a-d0efaa869e95', { contained: true });
```

and that was working. Now there is no option like that and after looking at the new docs/wiki I still can't figure it out.

Feel free to try using the link, no permissions needed to get the ePub from the bucket.

**Comment by jlag34** [comment]
I fixed my issue by fetching the data outside of the `ePub` method:

```
fetch(this.props.book.book)
  .then(blobRes => blobRes.blob())
  .then(blob => {
    const Book = ePub(blob, { replacements: 'blobUrl' });
    Book.ready.then(a => { // do stuff });
  });
```

I saved to epub to AWS as a blob, fetching it as a blob and passing the settings object did the trick.

**Comment by fchasen** [comment]
I had intended for [epub.open](http://epubjs.org/documentation/0.3/#bookopen) to handle setting the type when determining the input type isn't possible.

```js
const book = ePub({ replacements: 'blobUrl' });
book.open('https://s3.amazonaws.com/joe-test-bucket002/53930186-8735-4e49-891a-d0efaa869e95', 'epub')
```

Would be a good idea to add back and option to pass the link type.
Something like:
```
ePub("...", { openAs: "epub" })
```
