### ISSUE TITLE
Opening local archived files in iOS WebView

### ISSUE THREAD

**Issue by peancored** [futurepress/epub.js#750]
Hello!

I'm trying to use this library to display epub books in a vuejs + cordova application on iOS.
It works fine until I try to load **local** files with the `.epub` extension in iOS WebView.

```vue
<template>
 <div id="area"></div>
</template>

<script>
import {default as ePub} from 'epubjs';

export default {
  name: 'home',

  data() {
    return {};
  },

  methods: {
  },

  mounted: function() {
    window.testUrls = [
      './static/HarryPotter.epub',
      'https://s3.amazonaws.com/moby-dick/OPS/package.opf',
      'https://s3.amazonaws.com/moby-dick/moby-dick.epub',
      './static/moby-dick/OPS/package.opf',
      './static/moby-dick.epub'
    ];

    window.renderBook = function(bookUrl) {
      const element = document.getElementById('area');
      window.ePub = ePub;
      window.book = ePub(bookUrl);
      window.rendition = window.book.renderTo(element, {
        width: '100%',
        height: '100%'
      });
      window.rendition.display();
    };

    window.renderBook(window.testUrls[4]);
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
``` 
As you can see I have 5 test books, 2 of them are remote, 1 is unzipped local and 2 of them are zipped local. **I'm able to open all of these except zipped local files**.

It successfully fetches the file:
![image](https://user-images.githubusercontent.com/5630034/39968106-825900f4-56d0-11e8-995d-9659faea28e8.png)

But then I get nothing; the promise that `rendition.display()` returns is always pending and the area is empty. The area element is also empty (no `iframe` is added there):
![image](https://user-images.githubusercontent.com/5630034/39968185-cd2a8afc-56d1-11e8-835c-efce5c67a9fc.png)

However, the same code works in browser.

I assume this is some issue with unzipping local files but I can't understand how **local** files differ from **remote** ones and why I'm simultaneously able to open remote `.epub` file.
Can you please advice something?

**Comment by peancored** [comment]
Found out what caused the issue:
https://github.com/futurepress/epub.js/blob/b7643d3a1d498b3a76f80a4b0fa6defee285b00b/src/utils/request.js#L83
When trying to request a static file using `file://` protocol, the status is 0.
So, defining my own `request` method with the fix and passing it to 
```javascript
ePub('path/to/book', {requestMethod: request});
```
solves the issue.
However, I would like this to be a default behaviour, thus I will submit a PR.

**Comment by csantanu** [comment]
@peancored Hi can you explain a bit ePub('path/to/book', {requestMethod: request}); how you are defining the request ? I am facing same issue and the remote epub is downloading correctly but it's not getting displayed in the rendition.
