### ISSUE TITLE
Navigator is not defined when using SSR

### ISSUE THREAD

**Issue by gunningham** [futurepress/epub.js#752]
`
/node_modules/epubjs/lib/contents.js:31
var isChrome = /Chrome/.test(navigator.userAgent)
ReferenceError: navigator is not defined
`

Any way this could work without relying on window? It's not available when using SSR so unfortunately this module doesn't work for us

**Comment by fchasen** [comment]
Yep, should just return false if navigator isn't defined.

**Comment by RedHeadDigital** [comment]
@fchasen [PR Created](https://github.com/futurepress/epub.js/pull/754)

**Comment by fchasen** [comment]
Perfect - Thanks
