### ISSUE TITLE
MathML support is gone?

### ISSUE THREAD

**Issue by UncleGene** [futurepress/epub.js#753]
Newest revision does not have any reference/does not support MathML

**Comment by fchasen** [comment]
MathML via Mathjax is still supported in a hook, though the syntax has changed.
I'll add the hook below to the documentation shortly:

```js
var book = ePub("https://s3.amazonaws.com/moby-dick/OPS/package.opf");
var rendition = book.renderTo("viewer");

rendition.hooks.render.register(function (view) {
    return view.addScript('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML');
})
```

**Comment by UncleGene** [comment]
Thank you.
This example shows adding Mathjax to all pages. Is it possible to reproduce old behavior (add only to chapters that need it)? Also, does this work for both 0.3 and 0.4?

**Comment by fchasen** [comment]
Sorry about that, updated the snippet above.

I made a mathml example here: https://github.com/futurepress/epub.js/blob/master/examples/mathml.html#L151-L158

**Comment by UncleGene** [comment]
Thank you, this works!

**Comment by Cifyger** [comment]
Including Mathml breaks EpubCfi for me and i am no longer able to use any annotations. Is there a workaround for this?

**Comment by fchasen** [comment]
If you can add a class to Mathml, you can tell the EpubCFI parse to ignore that class in the rendition `ignoreClass`: http://epubjs.org/documentation/0.3/#rendition
