### ISSUE TITLE
Search Displayed Text / Chapter v3

### ISSUE THREAD

**Issue by jlag34** [futurepress/epub.js#762]
I'm still not very familiar with the API and the docs are sometimes difficult to understand. Thanks @geek1011 for starting an example area. I saw that you have a search for the entire book but what about text that is about to be displayed, text being displayed, or text only from that chapter?

I feel like v2 was much easier to figure out and use (book.currentChapter.find("the") --- simple way to search the chapter in v2).

**Comment by geek1011** [comment]
Yep, I agree about the docs.

For text only in the current chapter, I've added an example to the wiki:
````javascript
function doChapterSearch(q) {
    let item = book.spine.get(rendition.location.start.cfi);
    return item.load(book.load.bind(book)).then(item.find.bind(item, q)).finally(item.unload.bind(item));
};
````

For text in the next chapter, change `book.spine.get(rendition.location.start.cfi)` to `book.spine.get(rendition.location.start.cfi).next()`.

**Comment by jlag34** [comment]
Awesome, works. Thanks!
