### ISSUE TITLE
how to set request headers?

### ISSUE THREAD

**Issue by finalight** [futurepress/epub.js#769]
```
    const headers = {
      api_key: "QWERTYUIIPP"
    }

let book = ePub("http://localhost:3000/books/test.epub", { requestHeaders: headers });
```

I've checked my backend but it doesn't receive the headers

I've tried on the normal HTTP request and it works.

So I am not sure am I doing it the correct way or not

**Comment by mikkelvp** [comment]
You are doing it correctly.
Inspect requests in browser dev tools and see request headers.

My request headers with your example:

    GET /9788282059312/OPS/xhtml/04_Kapittel1.xhtml HTTP/1.1
    Host: 127.0.0.1:8080
    Connection: keep-alive
    Pragma: no-cache
    Cache-Control: no-cache
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36
    api_key: QWERTYUIIPP
    Accept: */*
    Referer: http://127.0.0.1:8080/
    Accept-Encoding: gzip, deflate, br
    Accept-Language: en-US,en;q=0.9,da;q=0.8,nb;q=0.7

**Comment by fchasen** [comment]
Seems to be working ok, closing this for now

**Comment by Oliveiracorpdev01** [comment]
When I try to get the .opf and pass an authorization key, the xhr is incomplete, consequently it doesn't load.
Any souls to help me?

```
    const headers = {
      Authorization: "Bearer tokentest"
    }

let book = ePub("http://localhost:8000/test/epub//test.opf", { requestHeaders: headers });
```
![Screenshot from 2022-08-19 15-57-01](https://user-images.githubusercontent.com/104578272/185688413-b427d109-687b-4826-a228-5ad05f60f74b.png)

**Comment by mikkelvp** [comment]
@Oliveiracorpdev01 Your code snippet and image does not match.
Code snippet: you probably want to remove the extra `/` after `epub` in the url.
Image: You need `Bearer` to have `" "` before the token like your code snippet.
