### ISSUE TITLE
Safari: prev() renders first page going back a section

### ISSUE THREAD

**Issue by mikkelvp** [futurepress/epub.js#772]
Using `rendition.prev()` to go back to previous section displays the first page of the section instead of the last.
The scrollLeft property is correctly set on the container, but Safari does not actually scroll to the given x position if the DOM element is not visible.
Calling `this.views.show();` before setting scrollLeft seems to work, but will of course flash the first page on slow devices.

Setting it when promise from prev resolves is possible, but it must be a different value for Safari to repaint (so again, a flash of first page occurs). Currently using this temp fix:

        rendition.prev().then(() => {
            if (isSafari) {
                const left = rendition.manager.stage.container.scrollLeft;
                rendition.manager.stage.container.scrollLeft = left > 0 ? left - 1 : 0;
                rendition.manager.stage.container.scrollLeft = left;
            }
        });

**Comment by mikkelvp** [comment]
Using opacity instead of visibility to hide/show works, but will also flash first page.

**Comment by fchasen** [comment]
I made a [codepen](https://codepen.io/fchasen/pen/jvWPxN) to confirm that the scrolling works ok.
Safari just needs a little tap to remind it to redraw the iframe so I've added a temporary transform like in https://gist.github.com/madrobby/1362093

https://github.com/futurepress/epub.js/blob/master/src/managers/views/iframe.js#L488-L491

Published in `epubjs@0.3.70`

**Comment by yh54321** [comment]
@fchasen This bug still exists, this shouldn't be closed.

**Comment by mikkelvp** [comment]
It was fixed. I belive Safari has reintroduced the issue.
The fix 
```
			// Remind Safari to redraw the iframe
			this.iframe.style.transform = "translateZ(0)";
			this.iframe.offsetWidth;
			this.iframe.style.transform = null;
```
https://github.com/futurepress/epub.js/blob/b5be5514e2b04991bd69337439dc65713bfea07f/src/managers/views/iframe.js :532
Doesn't make Safari redraw

**Comment by yh54321** [comment]
@mikkelvp I see you are correct it is fixed. I was using an older version without these lines.
