### ISSUE TITLE
No way to force disabling of spreads with v0.3 of epub.js

### ISSUE THREAD

**Issue by mfhscoobydoo** [futurepress/epub.js#773]
I'm going to guess there is a method to accomplish this, but as far as I can see, it's nowhere in the documentation or examples. And I know that spreads are auto disabled after the rendered area is the proper ratio, but I would like to disable spreads for ALL sizes and devices.

I have also tried setting the flow to be a scrolled-doc, but that still shows both pages of the spread, but one right below the other on the page.

**Comment by fchasen** [comment]
`minSpreadWidth` should be an integer value but you can disable spreads with

```
"spread": "none"
```

**Comment by JowelTisso** [comment]
@fchasen Thanks I was stuck with this issue with past few hours and now it is fixed... Thanks alot... It helped me...
