### ISSUE TITLE
packaged epubs wont render on IOS 9

### ISSUE THREAD

**Issue by mfhscoobydoo** [futurepress/epub.js#774]
the reader seems to work fine on ios with this opf file, but not an epub.
https://s3.amazonaws.com/epubjs/books/moby-dick/OPS/package.opf

just a note, I am properly linking jszip, and this problem only seems to be IOS.

**Comment by fchasen** [comment]
Are you getting any errors or have a link you can share?

Just tested https://s3.amazonaws.com/epubjs.org/examples/archived.html on ios 9.3 and had no issues.
