### ISSUE TITLE
Does not open epub file in android webview using external link?

### ISSUE THREAD

**Issue by bleedweedsuz** [futurepress/epub.js#776]
```
var book= ePub("lib/test.epub");// [this works] (inside asset folder)

var book = ePub("file:///storage/emulated/0/documents/test/"); //[this work after extract epub file] (internal storage)

var book = ePub("file:///storage/emulated/0/documents/test.epub"); //[this does not work] (internal storage)

book.renderTo("area");
```

did i miss something here or it's a bug??

**Comment by mikkelvp** [comment]
Not sure what you are trying to do here, but your issue seems to be related to Android and not epub.js
Test in a desktop browser first. 

Maybe you forgot to include jszip? Or you might need to adjust your webview settings:

        settings.javaScriptEnabled = true
        settings.allowFileAccessFromFileURLs = true
        settings.allowUniversalAccessFromFileURLs = true

**Comment by bleedweedsuz** [comment]
@mikkelvp 
`var book= ePub("lib/test.epub");// [this works] (inside asset folder)` here I used android asset directory to save epub file and load it from webview it load perfectly. I added all those settings in webview that's why it load the assets epub file ("which means jszip is working") but if is used external link like `file:///storage/emulated/0/documents/test.epub` epub file does not load it does not show any error it just does not load file. I don't know what to do next??

So i extract epub file and used is as directory `file:///storage/emulated/0/documents/test/` this works 

my question is why asset directory .epub file run but not external link?? weird is epub extracted folder works too ... O.o if you have a time i can send you my full project?

Note* I used epub.js the **reader** one [epubjs-reader] i did create issue there no one response so i create here.

![1](https://user-images.githubusercontent.com/10117919/42422060-6f80a03a-82ff-11e8-9972-18ae464c4dfd.JPG)

![2](https://user-images.githubusercontent.com/10117919/42422129-703482de-8300-11e8-8b10-b7c16680ae35.JPG)

**Comment by mikkelvp** [comment]
Set `WebView.setWebContentsDebuggingEnabled(true);` and inspect webview from chrome://inspect/#devices

Can't say why. But jszip seems to not be able to unzip. Get source-maps or development builds and debug.

Or unzip. You probably want to unzip to a folder in `context.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS);`

**Comment by bleedweedsuz** [comment]
```
        var zip = new JSZip();
        zip.file("Hello.txt", "Hello World\n");
        zip.generateAsync({type:"blob"})
        .then(function(content) {
            // see FileSaver.js
            console.log("Positive:" + content);
        });
```
**i think jszip is working** console output:
`.../chromium: [INFO:CONSOLE(39)] "Positive:[object Blob]", source: file:///android_asset/epubjs/epub.html ...`

yes unzip file is working i already mention that in previous comment. Can you look into my source code i already post it https://drive.google.com/open?id=1RIBtKzdX1yQkXnlYx7tYYtsLAWjcvdeG

**Comment by mikkelvp** [comment]
I did. I could see that webview fetched the epub file and then nothing happened. That's why i told you to debug in chrome.

Anyway i just added an updated version of epub.js with source-maps in your project. And it works just fine now.
So maybe next time update your library before creating issues.

**Comment by bleedweedsuz** [comment]
aww man i thought that this was the new version dang it. Thanks for the reply Awesome it works now :laughing:
