### ISSUE TITLE
Capture Text on Screen with v3

### ISSUE THREAD

**Issue by jlag34** [futurepress/epub.js#777]
Is there any way to get the current text on the screen using v3?

**Comment by mikkelvp** [comment]
var range = rendition.getRange(rendition.currentLocation().start.cfi);
        var endRange = rendition.getRange(rendition.currentLocation().end.cfi);
        range.setEnd(endRange.startContainer, endRange.startOffset);
        console.log(range.toString()); // Current text on screen

**Comment by fchasen** [comment]
☝️ works great but you need to make sure the start and end cfi's are in the same chapter.

You could also use a CFI range like in this example: https://github.com/futurepress/epub.js/blob/master/examples/contents.html
