### ISSUE TITLE
Creating a Night Mode with v3

### ISSUE THREAD

**Issue by jlag34** [futurepress/epub.js#778]
Trying to figure out how to add styles to the iframe using the API. There is a [Contents](http://epubjs.org/documentation/0.3/#contentscss) area with a CSS instance but I'm really not sure how to add it in.

I'm trying to flip the colors, black background and white text.

**Comment by mikkelvp** [comment]
http://epubjs.org/documentation/0.3/#themes

**Comment by jlag34** [comment]
@mikkelvp 

I saw that. I also saw the example here:

https://github.com/futurepress/epub.js/blob/master/examples/highlights.html

I'm using React, I have the following function that fires on a button click:

```
toggleNightmode() {
  const { rendition } = this.state;
  rendition.themes.register({ "body": { "background": "black"}});
  this.setState({ rendition });
}
```

I saved `rendition` to state after I handled the initial book load. Nothing changes when I fire this function.

**Comment by mikkelvp** [comment]
I don't see why you would want rendition in state. Anyway your state does not actually change since it's the same rendition object you call setState with.
Try to move rendition out of state to `this.rendition` and then use state or props to store user settings. Then in `componentWillUpdate` or your eventHandler you can apply settings/css to rendition.
Been a while since i worked with React, but i think this would work.

**Comment by jlag34** [comment]
@mikkelvp I do the following in my `componentDidMount`:

```
const Book = ePub(blob, { openAs: 'epub' });
Book.ready.then(() => {
  Book.loaded.navigation.then(navigation => {
    const rendition = Book.renderTo(this.readerEl, {
      height: "100%"
    });
    rendition.display();

    rendition.themes.register({ "body": { "background": "purple"}});
  });
});
```


Still can't get the color to change. The reason I put rendition on state because I need functions like `rendition.next()`,  `rendition.prev()`, `rendition.display()`. This is how the docs create the `rendition` variable I was unsure how to access it again outside of `componentDidMount`.

**Comment by geek1011** [comment]
For me, I just ignore the built-in themes functionality and make my own. Here is a bit of the code I'm using right now:

````javascript
function applyTheme() {
    let theme = {
        bg: "#ffffff",
        fg: "#000000",
        l: "#0B4085",
        ff: "'Open Sans', sans-serif",
        fs: "11pt",
        lh: "1.4",
        ta: "justify",
        m: "0"
    };

    rendition.getContents().forEach(c => c.addStylesheetRules({
        "body": {
            "background": theme.bg,
            "color": theme.fg,
            "font-family": `${theme.ff} !important`,
            "font-size": `${theme.fs} !important`,
            "line-height": `${theme.lh} !important`,
            "text-align": `${theme.ta} !important`,
            "padding-top": theme.m,
            "padding-bottom": theme.m
        },
        "a": {
            "color": "inherit !important",
            "text-decoration": "none !important",
            "-webkit-text-fill-color": "inherit !important"
        },
        "a:link": {
            "color": `${theme.l} !important`,
            "text-decoration": "none !important",
            "-webkit-text-fill-color": `${theme.l} !important`
        },
        "a:link:hover": {
            "background": "rgba(0, 0, 0, 0.1) !important"
        },
        "img": {
            "max-width": "100% !important"
        },
    }));
}

rendition.hooks.content.register(applyTheme);
````

**Comment by mikkelvp** [comment]
@jlag34 Either name your theme and then select it or use themes.default and select default.

    rendition.themes.register("purple", { "body": { "background": "purple"}});
    rendition.themes.select("purple");

In your React component, just do `this.rendition = Book.renderTo(this.readerEl, {...`
You can always access this.rendition from within that component.

**Comment by jlag34** [comment]
@mikkelvp got it working using your example. The `select` method is not part of the API docs.

@geek1011 I would recommend using this method, seems a bit cleaner.

**Comment by geek1011** [comment]
It is cleaner, but in my actual code, I have more than that. My method allows me to do more than just CSS.
