### ISSUE TITLE
epub loads in development but not after an npm build and deployment to prod

### ISSUE THREAD

**Issue by jshamel** [futurepress/epub.js#779]
I have the following code:

 rendition = book.renderTo(this.state.viewerId, {
	     manager: "default",
	      width: viewerWidth,
	      height: viewerHeight,
	      spread: "always"
	    });
	    rendition.display()

Works fine in development but all I get is an empty div after I bundle and deploy it. 

I have tried using the promise that is returned to no avail. After bundling the promise never returns. 

Any ideas

**Comment by mikkelvp** [comment]
Create a sourcemap and debug.
Not enough info to help you further than that.
