### ISSUE TITLE
Hypothesis links don't include full URL to EPUB

### ISSUE THREAD

**Issue by xolotl** [futurepress/epub.js#783]
@fchasen sorry if this is something you've already seen, but I was experimenting with a new demo of epub.js with Hypothesis annotation and it's all working perfectly...except...

The URLs recorded by Hypothesis don't match the actual URL of the annotated EPUB.

Here's an example:
EPUB: http://xolotl.org/library/hypothesis-spreads.html?loc=chapter_001.xhtml

But annotations on that EPUB are saved with links back to it like: https://hyp.is/jY5FSINXEeipiDdv1p__mg/xolotl.org/OPS/chapter_001.xhtml

This means that one is not able to get back to the EPUB location from the annotation (eg https://hypothes.is/a/dSVXRINXEeiTY0-mTNJO9A), nor from user profile/search views like https://hypothes.is/users/nateangell

FWIW: I built this demo directly from a fresh install of the main epub.js code and files from the examples directory there rather than the https://github.com/futurepress/hypothesis-reader repository, which seemed like it might not be as current.

**Comment by fchasen** [comment]
That example is missing the [`canonical` function](http://epubjs.org/documentation/0.3/#book) needed to set the correct canonical link back to the page.

I've added it now, and the annotator seems to be picking it up correctly.

**Comment by fchasen** [comment]
Looks like it was already present on `hypothesis-reader` at https://github.com/futurepress/hypothesis-reader/blob/master/js/reader.js#L9-L11

But as you mentioned that code needs to be updated to the latest epubjs release.

**Comment by xolotl** [comment]
I have confirmed your fix addresses the issue...thank you for the very quick work @fchasen!
