### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by jarecsni** [futurepress/epub.js#787]
Hi,

This looks like an excellent framework, and I’m about to integrate it into a project. Just wandering if the project is still alive (not much activity), and also keen to know about any plans or future directions for the project.

Also, which branch to use for the time being, 0.3 or 0.4?

Apologies for slightly abusing the issue tracker, but I got no reply on gitter.

Many thanks,
Janos

**Comment by fchasen** [comment]
The 0.3.X version on master / npm is the one to use for now.

0.4 isn't quite ready yet, but is actively being worked on.
