### ISSUE TITLE
How to use / install EpubCFI & EpubCFI.compare()?

### ISSUE THREAD

**Issue by viking2917** [futurepress/epub.js#827]
I have a reader app which makes use of the epub.js library (which, btw, AMAZING Thank you!).

I include epub.js from here: 

https://github.com/futurepress/epub.js/releases/tag/v0.3.66

Things work fine. However, I'd like to use the compare function from EpubCFI, to sort my list of bookmarks (cfis). (https://github.com/futurepress/epub.js/blob/master/documentation/md/API.md#epubcfi). 

However, EpubCFI seems not to be defined, i.e. in a console window:

```
> ePub
ƒ ePub(url, options) {
  return new _book2.default(url, options);
}
> EpubCFI
VM13652:1 Uncaught ReferenceError: EpubCFI is not defined
    at <anonymous>:1:1
(anonymous) @ VM13652:1
> var cfi = new EpubCFI;
VM13683:1 Uncaught ReferenceError: EpubCFI is not defined
    at <anonymous>:1:11
(anonymous) @ VM13683:1

```

I am assuming either I have something set up incorrectly, or I don't know how to get ahold of the EpubCFI object so I can call methods. Anyone know how?

**Comment by fchasen** [comment]
`ePub.CFI` should let you create new EpubCFIs.

You can see the full list of methods available with `ePub` here: https://github.com/futurepress/epub.js/blob/master/src/epub.js#L30-L34

You might also want to consider using es6 style imports and webpack, like `import ePub, { EpubCFI } from 'epubjs'`

**Comment by viking2917** [comment]
Thank you @fchasen . The documentation for the compare method doesn't indicate the types of the arguments, it just says cfione and cfitwo. But the code shows that you can just pass it cfiRange strings, and I already have those, I just want to compare them. That's the part I can't figure out, is how to get to the compare() method....perhaps I am not understanding your answer.

I will look into doing imports es6 style, but hoping I can get to the compare method either way....

**Comment by viking2917** [comment]
Here's what ended up working for me, in case anyone runs into this. The answer from @fchasen had the answer, I was just missing the _new_ keyword, e.g.

```
var EpubCFI =  new ePub.CFI();
EpubCFI.compare(cfi1, cfi2);
```
