### ISSUE TITLE
Is there event for clicking link?

### ISSUE THREAD

**Issue by bleedweedsuz** [futurepress/epub.js#828]
there can be a link in epub books so, is thre is a trigger event for **href** just like in **annotation**?

**Comment by fchasen** [comment]
Where do the links go to?

Currently only links to other chapters in the book are handled in https://github.com/futurepress/epub.js/blob/99273e7356fb009d277053649b8d43c90bc89170/src/utils/replacements.js#L85-L113

**Comment by bleedweedsuz** [comment]
Awesome man :+1:
