### ISSUE TITLE
Navigation.get returns wrong TOC item.

### ISSUE THREAD

**Issue by nielslanting** [futurepress/epub.js#831]
The navigation has a get method however it only works top level toc items. If the TOC has subitems, the navigation's get method will never return the correct TOC item given an id/href.

The navigation's unpack method recursively unpacks the subitems, but doesn't pass on the parent's id. So first subitem will always return the first TOC item.

Is this done by design?
Or should the navigation class index subitems by id/href correctly?

**Comment by tpolat** [comment]
I using this format; 

page 1;
<h1>Title 1</h1>
<h2>Title 1.1</h2>
<h3>Title  1.1.1</h3>

page 2;
<h1>Title 2</h1>
<h2>Title 2.1</h2>
<h3>Title  2.1.1</h3>
    
this format forking for me. I using tree and have sub items.

my tree showing like this;

Title 1
 Sub Title 1.1
    Sub Title 1.1.1
    Sub Title 1.1.2
    Sub Title 1.1.3
 Sub Title 1.
    Sub Title 1.2.1
    Sub Title 1.2.2
Title 2
 Sub Title 2.1
    Sub Title 2.1.1
