### ISSUE TITLE
Japanese filename images that embed in epub are not displayed

### ISSUE THREAD

**Issue by mogken** [futurepress/epub.js#834]
It occurs in epub written from Indesign.
Images with file names including Japanese are not displayed at all.
I've unconfirmed other type objects are the same phenomenon or not.

[epub_sample.zip](https://github.com/futurepress/epub.js/files/2425906/epub_sample.zip)

**Comment by fchasen** [comment]
Thanks for the sample, I'll take a look at why the table of contents is empty with it.

**Comment by fchasen** [comment]
Look like the ToC is just empty in epub, never mind on that.

How are you viewing the epubs? With Chrome 69 both images show up fine.

<img width="407" alt="screen shot 2018-09-28 at 5 39 05 pm" src="https://user-images.githubusercontent.com/213312/46238858-96810e00-c345-11e8-9615-6c030a3debc8.png">

**Comment by mogken** [comment]
I can see samples of the same epub on iBook of MacOS., it will display correctly.
http://webtest.mogken.com/epub.js/epub/jptest.epub

**Comment by mogken** [comment]
In Readium.js, images with Japanese file names are displayed correctly. However, as EPUB's reproducibility was higher in epub.js, we are considering adopting epub.js.

I will continue to wait for answers.

**Comment by danielweck** [comment]
Oh sure, I just wanted to double-check with you, just in case there was also a bug in Readium :)

**Comment by fchasen** [comment]
Ah ok, this is only on zipped epub files. If you serve the uncompressed file it works fine.

There is an issue on JSZip (the zip library we use) that covers how to set the filename encoding:
https://github.com/Stuk/jszip/issues/384#issuecomment-267435837
