### ISSUE TITLE
URL encoded href causing 404 on images

### ISSUE THREAD

**Issue by K1tson** [futurepress/epub.js#838]
I've noticed that images with a URL encoded href value are showing as 404 when attempting to view them. I'm guessing it's down to the image not being correctly stored as blob as it's attempting to GET the image with its true true href value.

**Error:**
![image](https://user-images.githubusercontent.com/20926532/46261456-bce0ae00-c4eb-11e8-8811-4c5b66593fa4.png)

**OPF**
![image](https://user-images.githubusercontent.com/20926532/46261496-39738c80-c4ec-11e8-9032-f1aec36af897.png)

Thanks.

**Comment by K1tson** [comment]
I temporarily fixed the issue. It was down to the `<img src=""` located in the XHTML pages not containing URL friendly characters therefore unable to match with RegEx causing the URL to no rewrite. I was able to get around in code by adding the below to the substitute function:

```
function substitute(content, urls, replacements) {
	urls.forEach(function (url, i) {
        if (url && replacements[i]) {
            content = content.replace(decodeURI(url), replacements[i]); //Added to catch incorrect urls.
			content = content.replace(new RegExp(url, "g"), replacements[i]);
		}
	});
	return content;
}
```

**Comment by raphaeldas** [comment]
I get a similar error. Assets get loaded correctly but not with the image "E+H_2c.png": 
http://localhost:8080/OEBPS/image/E+H_2c.png
But I got the latest version installed: 0.3.93
Are there some other settings i have to pay attention?

**Comment by OriIdan** [comment]
File names encoded with special characters like + should be avoided.
Check the file name in the manifest section of your OPF file.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by raphaeldas** [comment]
Thank you @OriIdan for your reply. 
Unfortunately, i have little control over the epub files because i receive them directly from the client. Will find a solution with the client.

Thanks
