### ISSUE TITLE
Bug in bookmark.

### ISSUE THREAD

**Issue by bleedweedsuz** [futurepress/epub.js#839]
As you can see in video extracting name of the current page bookmarked is wrong. 
In video I am in Chapter 11: Nightgown after i bookmark it i saw that in bookmark list it says Chapter 13: Wheelbarrow.

Can you look into this coz i m having same issue with my app too. 

https://drive.google.com/open?id=1_l9rdaPzkxJH2WXSYqxT8SpcEbhd9Ok9

in video i m using https://futurepress.github.io/epubjs-reader/ official reader website

Thank you :smile_cat: 

Edit:
  ```
var cfi = Rendition.currentLocation().start.cfi;
var TOCIndex = Book.spine.get(cfi).index;

//current output is like cfi = epubcfi(/6/6[chapter1.1]!/4/2/2/1:0) and TOCIndex = 2

//needed output should be cfi = epubcfi(/6/6[chapter1.1]!/4/2/2/1:0) and TOCIndex = 1
```
while i debugging it i found that CFI is good but index is wrong

**Comment by sharvan-capsitech** [comment]
Use this cfi to display two times and get the right redirection of the bookmark.
Like below -
rendition.display(cfi);
rendition.display(cfi);
