### ISSUE TITLE
Compare() documentation backwards/incorrect?

### ISSUE THREAD

**Issue by viking2917** [futurepress/epub.js#841]
The [documentation for epubcfi.compare()](https://github.com/futurepress/epub.js/blob/master/documentation/md/API.md#compare) states:

> Returns number First is earlier = 1, Second is earlier = -1, They are equal = 0

However it seems to do the opposite (unless I am missing something). E.g. using the epub file

`https://standardebooks.org/ebooks/robert-louis-stevenson/treasure-island/milo-winter/dist/robert-louis-stevenson_treasure-island.epub`, 

and doing: 

```
EpubCFI.compare(
"epubcfi(/6/16[chapter-2.xhtml]!/4/2[part-1]/2[chapter-2]/22/1:0)", 
"epubcfi(/6/16[chapter-2.xhtml]!/4/2[part-1]/2[chapter-2]/30/1:0)")
```

returns -1, when the first CFI is earlier in the book.

This is re-enforced by the following code line:

```
if (terminalA.offset < terminalB.offset) {
				return -1;
			}
```

which seems to mean the function will return _-1_ if the first cfi is earlier.

Should the documentation not say:

> Returns number First is earlier = **-1**, Second is earlier = **1**, They are equal = 0

Or am I misunderstanding something?

**Comment by viking2917** [comment]
@geek1011 it does make sense that earlier = -1 - it's just the doc says its the other way :)

**Comment by geek1011** [comment]
Oh, I see what you mean. I don't use the documentation much due to things like that. It is usually easier to read the code. Even so, this should be fixed. I'll open a PR when I have time (or you can if you want).

**Comment by viking2917** [comment]
@geek1011 I'll do the PR. It'll be my first :) Good learning opp.

**Comment by viking2917** [comment]
The PR was merged. Closing this.
