### ISSUE TITLE
Request headers not being set to prevent CORS errors

### ISSUE THREAD

**Issue by ihhcarus** [futurepress/epub.js#865]
Hello, I'm using the library's version [0.3.73](https://github.com/futurepress/epub.js/releases/tag/v0.3.73) and trying to work around CORS problems by setting the `Access-Control-Allow-Origin` header in the requests.

The code I have is as follows:
`var book = ePub("https://bode-soe.s3.amazonaws.com/soe/ebooks/python_p0M4E1g.epub", {requestHeaders: {'Access-Control-Allow-Origin': '*'}});`

By monitoring the browser's network requests I see that the sent headers are as follows:
```
Provisional headers are shown
DNT: 1
Origin: [my_website]
Referer: [my_website]
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
```
By checking that the headers I set are not there I figure something is wrong?

Thanks

**Comment by murlock** [comment]
The `Access-Control-Allow-Origin` should be in the response of AWS.
Have you specified CORS in your bucket ?

Links:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

**Comment by ihhcarus** [comment]
@murlock That makes sense... Sorry about my "newbieness". I'll try to check what you suggested and come back with the results.
Thanks!

**Comment by ihhcarus** [comment]
I've changed the "CORS configuration" in my S3's "Permissions" tab with the following and now it's working normally:
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>Authorization</AllowedHeader>
    <AllowedHeader>Content-*</AllowedHeader>
    <AllowedHeader>Host</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

Beware that this is a very permissive configuration so your files will be available for requests from any domains.

**Comment by murlock** [comment]
Please note that CORS is not related to protect files but to protect browser / user to use dangerous files ;)
