### ISSUE TITLE
Converted EPUB using "Calibre" is not loaded

### ISSUE THREAD

**Issue by icarovirtual** [futurepress/epub.js#869]
Hello, I'm using [Calibre](https://calibre-ebook.com/) to convert PDFs to EPUBs but the output files are not being loaded by the library. No errors or messages are printed in the browser's console.

I'm using the default settings for the conversion and an example file is below:
https://we.tl/t-YEIorjGebc

Thanks!

**Comment by Fredxingxing** [comment]
i meet the same problems.
any solutions suggest?

**Comment by icarovirtual** [comment]
@Fredxingxing it's been a long time since I did this in one of my projects but I think that I ended up having to ask to be provided EPUB files directly instead of converting them. This way they worked normally with the library.
Sorry if I can't help further.
