### ISSUE TITLE
Books not viewing on Android 4.3 and older versions

### ISSUE THREAD

**Issue by tpolat** [futurepress/epub.js#870]
Hi;
I have an ionic v1 project and using epub js v0.3. I tested on android 4.3 but my book not viewing on screen. The book loaded, toc and metada working, but book contents not show on screen. My codes;

                            $rootScope.Book = ePub("books/" + $rootScope.currentBook.file); 

				$rootScope.Rendition = $rootScope.Book.renderTo("area", { 
					width: "100%", height: "100%",
					flow: "scrolled-doc",
					ignoreClass: 'annotator-hl'
				});

				/********toc******** */
				$rootScope.Book.loaded.navigation.then(function (navigation) {
					$rootScope.toc = navigation.toc;
				});
				/********Meta******** */
				$rootScope.Book.loaded.metadata.then(function (metadata) {
					$rootScope.meta = metadata;
				});

**Comment by toyosix** [comment]
Experiencing same issue using Android webview epubjs v0.3 .` Uncaught SyntaxError: Unexpected token >` on 
```
book.loaded.metadata.then((metadata) => {
});
```

This is happening on Android 4.4 and older versions

**Comment by tpolat** [comment]
@toyosix metadata and toc loaded as successfuly on Android 4.4 and 4.3 when i shange 
book.loaded.metadata.then((metadata) => {
});

to

book.loaded.metadata.then(function (metadata) {
				var meta = metadata;
			});
Es6 code(for exp. (metadata) =>) not work on old versions. Change '(metadata) => { }'  to 'function (metadata) { }

The error code block

var rendition = book.renderTo("area", { 
				width: "100%", height: "100%",
				flow: "scrolled-doc",
				ignoreClass: 'annotator-hl'
			});

renderTo method not working.  I've detected the code block that occured error in epub js. 
The kod block;

this.tick.call(window, function () {
   if (_this._q.length) {
      _this.dequeue().then(function () {
         this.run();
      }.bind(_this));
   } else {
      _this.defered.resolve();
      _this.running = undefined;
   }
});
