### ISSUE TITLE
Limiting reader to the first chapter only

### ISSUE THREAD

**Issue by nicisme** [futurepress/epub.js#896]
Just a question, I am trying to have a reader where it only displays the first chapter of an ebook (or a set number of pages). So users can read the first chapter for free, but no more.

Been trying to figure it out but just not getting anywhere. 

Tried implementing this https://github.com/futurepress/epub.js/issues/326 but those functions are deprecated.

Can anybody help? Many thanks

**Comment by nicisme** [comment]
That makes sense. Thank you. I'll try give that a go and will post my solution for future viewers...

**Comment by fchasen** [comment]
Server side (or atleast checking in with the server on every chapter load) is definitely the way to go, but for the UI you can try listening for the `relocated` like here: https://github.com/futurepress/epub.js/blob/98ebd6e7dcdade189197c44b930e457480145013/examples/embedded.html#L48-L52

If the location is past what you wan't to show you could pop up a modal or call `rendition.destroy()`
