### ISSUE TITLE
Mobile Safari text selection broken for many ePubs on iOS (iPad)

### ISSUE THREAD

**Issue by viking2917** [futurepress/epub.js#904]
Text selection is broken/un-usable for many (but not all) ePubs on Mobile Safari (iOS devices)

On iOS one taps and holds on a single word, then the drag handles appear so one can expand/contract the selection region. However, with the production ePub js, in many ePubs, as soon as you touch one of the drag handles, the drag region contracts to one character and cannot be altered thereafter. This makes text highlighting and selection impossible. 

To reproduce (using Safari on an iPad or the iPad Simulator): 
1. go to (e.g.) https://futurepress.github.io/epubjs-reader/?bookPath=https://standardebooks.org/ebooks/epictetus/the-enchiridion/elizabeth-carter/dist/epictetus_the-enchiridion.epub
2. Move to chapter 2. Tap and hold the word "promises", then try to alter the selection region. The region will collapse. 

This occurs as well on many Project Gutenberg books as well, it is not specific to this epub. The default book, Moby Dick, does not show this problem. (_update: per the below, Moby Dick has the problem as well_).

This can also be reproduced on other readers using the epubjs engine, e.g. https://github.com/viking2917/ionic-epub-reader and https://github.com/geek1011/BookBrowser show it as well. 

The attached images show the before/after effects of selecting a word and clicking on the right-most drag handle. 

After selection of word:
![screen shot 2019-01-19 at 12 13 36 pm](https://user-images.githubusercontent.com/7691349/51432908-dd8c5b00-1be3-11e9-8c6a-34b77e76c3c5.png)

After attempting to drag the rightmost drag handle:
![screen shot 2019-01-19 at 12 13 52 pm](https://user-images.githubusercontent.com/7691349/51432909-dd8c5b00-1be3-11e9-9930-faf8834c6b15.png)

This youtube video shows the incorrect behavior in its entirety: https://www.youtube.com/watch?v=60ZBPWiMoHo&feature=youtu.be

Strangely, this bug mainly seems to occur on iPad. The same scenario seems not to occur on iPhones.

I would happily try to work on a fix if anyone has any pointers, it severely limits the reader on iPads.

(note: the Readium reader does not share this issue for this epub, and the ePubJS reader works fine in non-mobile browsers).

**Comment by viking2917** [comment]
I can confirm this happens in Chrome on iPad as well, so it's not specific to Safari. And I can reproduce it in Moby Dick, the default example as well, and that it's somehow dependent on where you select - picking two words right next to each other will provoke the behavior on one word, and not on the other. For example, in the first sentence of Moby Dick, tapping on "Years" will work fine, whereas three words later tapping on "Mind" will behave quite erratically.

**Comment by viking2917** [comment]
On further investigation, it looks like this may be a browser-level bug. I can reproduce a similar effect completely outside of epub.js. Details here: https://stackoverflow.com/questions/54300608/cannot-select-text-with-iframe-on-ios-devices-webkit and webkit bug filed here: https://bugs.webkit.org/show_bug.cgi?id=193663.

The problem appears to be that for iframes that are offset / padded from the top of the screen (as is the epub.js iframe), the location of the drag handles gets offset by that extra amount, and the effect gets worse the further into a book/chapter one goes. My attempts at absolute positioning and pad/offset on the iFrame don't seem to help. 

So, epub.js is basically unable to do any reliable text selection on iPads, from what I can see. Pretty unfortunate and makes the library pretty much un-usable for any kind of annotation or highlighting on iPads. Why this is specific to iPads is a mystery to me.

**Comment by viking2917** [comment]
This appears to be solved in iOS 12.2. I have tested the fix from the developer in the iOS beta, details here: https://bugs.webkit.org/show_bug.cgi?id=193663

I'll close this when 12.2 is released and I can verify in production. In the meantime I'm implementing a workaround using my own region selection (a pain, btw), happy to share if someone needs it.

**Comment by vblazenka** [comment]
Hi @viking2917 I'm interested in your region selection solution if you did it. :)

**Comment by viking2917** [comment]
Hi @vblazenka 

Attached is my modified version of the epub.js file. It is a modified version of the 0.66 version of the epub.js file. 

https://github.com/futurepress/epub.js/releases/tag/v0.3.66

You can diff the two files to see all the changes. Most of the changes are simply appended to the bottom of the file, but there are a few event handler changes higher up. 

Basically, the changes do the following (only for iPad, by testing user agent string)

* lengthen the duration for selection (I had to do this to make normal selection work right on mobile devices in general)
* dynamically add Desandro's "Draggabilly" script for easy management of region selection drag handles (https://github.com/desandro/draggabilly) (it has to be added dynamically because epub.js is constantly re-creating iframes, so it has to be re-injected whenever it's created).
* the function emulateIOSSelection() basically rewires the appropriate event handlers to keep track of the start and end of region selection and managing the dragging to alter the selection region.

Once you stop dragging for a period of time, the browser will select the range and epub.js will emit a selection event as it does normally.

Let me know of questions. I think all the changes are confined to this file. 

This feels hacky to me, but it is in production and being used OK. I'm looking forward to 12.2 being released so I can get rid of it :)

[epub.v0.3.66.sel.js.zip](https://github.com/futurepress/epub.js/files/2923762/epub.v0.3.66.sel.js.zip)

**Comment by fchasen** [comment]
Thanks for sharing this @viking2917

**Comment by viking2917** [comment]
I have confirmed that this is fixed in the recently released iOS 12.2. Closing this.
