### ISSUE TITLE
how to preventdefault on redition touch event?

### ISSUE THREAD

**Issue by ShootToThrill** [futurepress/epub.js#905]
` rendition.on("touchstart", e => {
        const touch = e.touches[0];
        this.touchStartX = touch.clientX;
        this.touchStartTime = e.timeStamp;
        e.preventDefault()
        e.stopPropagation()
      });`

i use `e.preventDefault()`
but chrome say `Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>`

**Comment by viking2917** [comment]
don't have a particular insight, but you might look at this and referenced articles to see if it contains a workaround: https://github.com/bevacqua/dragula/issues/468
