### ISSUE TITLE
fontsize()do no work

### ISSUE THREAD

**Issue by ShootToThrill** [futurepress/epub.js#907]
![image](https://user-images.githubusercontent.com/17040474/51486583-0bd48b00-1ddc-11e9-81b0-6a7014c3e1ce.png)
The set font size is covered 

there is a css file blob:http://192.168.1.9:8080/fc01c010-3014-4a7e-9ba4-c4b046e8fcce
set font-size:small so epub.js set the fontsize on body do not work

so What should I do?

**Comment by ShootToThrill** [comment]
@geek1011 i tried  !important but is not work 。If I manually inject css, how can I inject it into that iframe? If I don't inject it into the iframe, the css selector will be very long and long. It seems a bit stupid.

**Comment by tushar9989** [comment]
It works for me.
The javascript code https://github.com/tushar9989/e-reader/blob/master/public/static/reader/epub/view.js#L22-L39

The injected css file.

**Comment by fchasen** [comment]
You can use a hook to inject into the iframe like shown here: http://epubjs.org/documentation/0.3/#rendition
