### ISSUE TITLE
how to unhook eventlistener from rendition

### ISSUE THREAD

**Issue by Janglee123** [futurepress/epub.js#910]
I am working on epub reader [app](https://github.com/Janglee123/eplee) based on electron. For keyboard shortcuts I am using [mousetrap](https://github.com/ccampbell/mousetrap) as mentioned in [docs](https://electronjs.org/docs/tutorial/keyboard-shortcuts#shortcuts-within-a-browserwindow). But when rendition is in focus keyboard shortcuts are not working because rendition is capturing events.
Is there any way to solve this problem ?

**Comment by BrianSladek** [comment]
Not sure about mousetrap but you can listen for standard javascript events in the rendition this way:
`this.rendition.on('keydown', this.handleKeyDown);`
where handleKeyDown is your function to react to the event.

**Comment by Janglee123** [comment]
yes it works, but only when rendition is focused that's unusual for app.

**Comment by BrianSladek** [comment]
So if you add:
`document.addEventListener("keydown", this.handleKeyDown);`

It should work both when the rendition has focus and when some other part of the document has focus.

**Comment by Janglee123** [comment]
that is easy to use but using keyboard shortcut like "ctrl+plus" or "ctrl+minus" is headache in javascript that's why use of mousetrap necessary.
