### ISSUE TITLE
Question: in section.render, does the request argument allow me to make a custom request? 

### ISSUE THREAD

**Issue by mnishizawa** [futurepress/epub.js#912]
I would like to pull sections of an ebook from a dedicated content server.  The documentation on the render and load methods indicate that the argument you are passing in is a function, which is further reinforced by the TypeScript definition that accepts a Function.  If I understand that code correctly, it falls back from the function argument, to a member variable, to a standard request method, but that indicates to me that I can totally override the fetch functionality to do what I want and even manipulate the content before control is handed back to the rest of the rendering logic.  

My question is, am I correct in the way I am reading the code and, if so, do you have any examples or advice on implementing it?

**Comment by fchasen** [comment]
That is correct, you can override the fetch to whatever function is needed.
This was primary made to handle different fetch methods for node or react native though.

Can you share any more information on what you are trying to accomplish with replacing fetch? There might be a hook that can implement it easier.

**Comment by mnishizawa** [comment]
It was a need to receive encrypted data and unencrypt before opening.
