### ISSUE TITLE
Not an Element error

### ISSUE THREAD

**Issue by vdyagilev** [futurepress/epub.js#917]
Using the code
`var book = ePub("https://standardebooks.org/ebooks/marcus-aurelius/meditations/george-long/dist/marcus-aurelius_meditations.epub");`
` var rendition = book.renderTo("area", {width: 600, height: 400});`
throws an error when book.renderTo() is called, with the following error message: 
`epub.min.js:formatted:10024 Uncaught Error: Not an Element
    at e.value (epub.min.js:formatted:10024)
    at e.value (epub.min.js:formatted:10030)
    at e.value (epub.min.js:formatted:2946)
    at e.<anonymous> (epub.min.js:formatted:4500)
    at e.value (epub.min.js:formatted:1925)
    at epub.min.js:formatted:1954`
Does anyone know the source of the error?

**Comment by Xuchao1996** [comment]
me too

**Comment by Xuchao1996** [comment]
you don't have <div id="area"></div> in your html

**Comment by Xuchao1996** [comment]
you don't have a div tag. id = 'area'
