### ISSUE TITLE
Feature request: Add type definitions for Typescript and make it available on NPM

### ISSUE THREAD

**Issue by hesampour** [futurepress/epub.js#928]
I would like to request "type definitions" for Typescript for this library. It would be great to use this library in my Typescript projects.

Thanks.

**Comment by nielslanting** [comment]
There is a types folder: [https://github.com/futurepress/epub.js/tree/master/types](https://github.com/futurepress/epub.js/tree/master/types)

**Comment by fchasen** [comment]
Please feel free to reopen if those types aren’t working for some reason.

**Comment by hesampour** [comment]
thanks a lot.
how can I use it in my typescript project. I can import Book,Rendition,Contents,Layout,EpubCFI but I can't import ePub.
