### ISSUE TITLE
There is a types folder: [https://github.com/futurepress/epub.js/tree/master/types](https://github.com/futurepress/epub.js/tree/master/types)

### ISSUE THREAD

**Issue by hesampour** [futurepress/epub.js#929]
There is a types folder: [https://github.com/futurepress/epub.js/tree/master/types](https://github.com/futurepress/epub.js/tree/master/types)

_Originally posted by @nielslanting in https://github.com/futurepress/epub.js/issues/928#issuecomment-472879942_

I get this error. 

 ERROR in node_modules/@ionic/storage/node_modules/localforage/typings/localforage.d.ts(122,14): error TS2300: Duplicate identifier 'localforage'.
[ng] node_modules/epubjs/node_modules/localforage/typings/localforage.d.ts(122,14): error TS2300: Duplicate identifier 'localforage'.

**Comment by hesampour** [comment]
I removed the ionic storage and this problem fixed but now I get this error

Module not found: Error: Can't resolve 'epubjs/types' in 'D:\current_projects\maz 9\library\mazLibrary\src\app\book'

I have imported the Book in this way
import {Book } from 'epubjs/types'
there is no problem in vs code and code completion works completely but I get the error when executing with ionic serve

**Comment by hesampour** [comment]
I imported in this way 
import * as epub from 'epubjs'
and there was another error 
ERROR in ./node_modules/jszip/lib/readable-stream-browser.js
[ng] Module not found: Error: Can't resolve 'stream' in

and I changed the stream to readable-stream in /jszip/lib/readable-stream-browser.js file and the problem fixed.
thanks a lot.

**Comment by hesampour** [comment]
Everything is ok in this way but auto complete not works correctly.

**Comment by fchasen** [comment]
Not sure this is an issue in epub.js

**Comment by Zeratoxx** [comment]
According to localforage and this issue: https://github.com/localForage/localForage/issues/680
The depency @types/localforage is not neccessary any more.
