### ISSUE TITLE
Publish project to epub.js or rename project to epubjs?

### ISSUE THREAD

**Issue by ksrb** [futurepress/epub.js#941]
Is there a reason why there's a older version of this project published under the name `epub.js`? It's a bit confusing and I ended up installing the wrong one the first time 😅 . 

I had to look at this project's `package.json` to spot that it was in fact being published under the name `epubjs` (no period before the `js`).

https://github.com/futurepress/epub.js/blob/b957ccf0fbffc6cc97b86f0dd206b76ababe8d36/package.json#L2

# NPM
https://www.npmjs.com/package/epubjs - Latest
https://www.npmjs.com/package/epub.js - Older version

# Related issue
https://github.com/futurepress/epub.js/issues/622

**Comment by sengemann** [comment]
Agreed.

**Comment by Losses** [comment]
What about @futurepress/epub.js ?

**Comment by fchasen** [comment]
Thanks, the `epub.js` package was started before it was clear that having a package that ended in `.js` wasn't a great idea for import resolvers. Most libraries I've seen (such as `pdf.js`) will publish without the dot.

I've now deprecated the `epub.js` package on NPM.
