### ISSUE TITLE
book.renderTo is not a function?? Working code stopped working.

### ISSUE THREAD

**Issue by EmilAways** [futurepress/epub.js#944]
So I had a smoothly working script fetching books with epub.min.js, but when I tried it again today, it had stopped working. It seems like the book.renderTo() function has moved into a weird stub called _v? What's going on? This only concerns the latest Firefox AFAIK. Even the demo on FuturePress.org has the same issue.

**Comment by sengemann** [comment]
Could you provide a code-snipit?

Here's what I'm doing:

```JavaScript
const bookOptions = { openAs: 'opf', requestHeaders: { "Accept": "text/xml" } };
let bookUri = './assets/opf/moby-dick/OPS/package.opf';
let book = ePub(bookUri, bookOptions);
let progress = 0;
let rendition = book.renderTo('epubContainer', {
    flow: 'paginated', // For generic books
    manager: 'continuous', // For generic books
    spread: 'always', // For generic books
    width: "100%"
});

book.ready.then(function() {
    const stored = localStorage.getItem(book.key() + '-locations');
    console.log('metadata:', book.package.metadata);
    if (stored) {
        $('.page.hidden').removeClass('hidden');
        $('.loading').addClass('hidden');
        return book.locations.load(stored);
    } else {
        return book.locations.generate(1024); // Generates CFI for every X characters
    }
}).then(function(location) {
    localStorage.setItem(book.key() + '-locations', book.locations.save());
});

let displayed = rendition.display(window.location.hash.substr(1) || undefined);
```

**Comment by EmilAways** [comment]
Hi Sengemann. (Norwegian, you too? :p)
I used an old version of the library and it started working again, but the issue was experienced on the example on FuturePress.org's main page too, so I guess you could check that code if you want. I checked with 2 different computers, just to make sure. Now it seems to work (just checked the main page's example), so I guess it's fixed, but I'll stay with the old version to avoid future changes. It was probably a change in the code or a change in Firefox. I guess we can close it? My first time interacting with github.

**Comment by sengemann** [comment]
My guess is that it's an issue with FireFox that was recently fixed (I can't 100% confirm that though). Glad it's working for you. (German/Dutch. :D)
