### ISSUE TITLE
Issue with the highlighting functionality

### ISSUE THREAD

**Issue by SonephetR2** [futurepress/epub.js#952]
Hi! It seems that the `selected` event that is the intended way to do highlights (as this is what is used in the [highlights.html example](https://github.com/futurepress/epub.js/blob/master/examples/highlights.html)) set the highlight event to fire after a timeout rather than on mouseup.

This leads to poor user experience as highlights are very hard to apply properly, basically getting applied based on a timer with a very short fuse. 

In practical terms, when I select the text that is to be highlighted on [Foliate](https://github.com/johnfactotum/foliate), an Epub.js-based Epub reader, the selection will be interrupted if I am not fast enough. Highlighting long sentences in one go is therefore all but impossible and most highlights will be missing a few words. The usual way of implementing such a tool in highlighter-enabled PDF viewers or the rare highlighter-enabled EPUB viewers (Bluefire on Windows and Android for instance) is to apply the highlighting when the mouse click is released ("onmouseup"), which allows for much better user experience for serial highlighters such as myself.

Would that be possible with Epub.js?

**Comment by SonephetR2** [comment]
Update: the Foliate developers clearly managed to find some sort of work-around. The latest version rocks! :)

**Comment by liviaab** [comment]
Hi! My team and I were having the same problem. Your approach helped a lot, thanks for sharing and updating the issue!
