### ISSUE TITLE
EPUBs with vertical text not working properly in WebKit

### ISSUE THREAD

**Issue by johnfactotum** [futurepress/epub.js#957]
In WebKit, books with vertical text only displays the beginning of each chapter (spine item). For example, when `rendition.next()` is called, it displays the next chapter instead of the next page. This only happens in WebKit; it works fine in Firefox and Chromium.

A book sample that can demonstrate this problem can be downloaded here: https://www.mobileread.com/forums/showthread.php?t=215310

**Comment by fchasen** [comment]
Very strange. I'd guess that the measurements of the text height are returning the wrong value in WebKit, so it thinks there is only 1 page.

Will need to investigate some more.

**Comment by johnfactotum** [comment]
Not sure if this would be helpful, but I've stumbled across a blog post in which a vertical text book seems to be correctly handled by Epub.js: http://moebuntu.blog48.fc2.com/blog-entry-1292.html. So apparently it doesn't happen with all books with vertical text.

**Comment by johnfactotum** [comment]
It seems to have gotten worse in 0.3.87.

Using 0.3.86:
![image](https://user-images.githubusercontent.com/50942278/82139549-13f9da80-9818-11ea-9ca3-49dabf9e50ec.png)

Using 0.3.87:
![image](https://user-images.githubusercontent.com/50942278/82139568-2bd15e80-9818-11ea-8444-027c31639ba1.png)

Furthermore, with 0.3.86, it's only broken on WebKit, but now in 0.3.87, it's broken in Firefox and Chromium as well.

**Comment by fchasen** [comment]
Humm, taking a look. I suspect it isn't getting the correct text direction.

**Comment by fchasen** [comment]
Looks like this original issue was cause by `-webkit-column-axis=horizontal` being applied to the vertical text.

The new issues in 0.3.87 was from `direction: rtl` being applied to the vertical text and causing all sorts of strange layout in chrome.

Both fixed in https://github.com/futurepress/epub.js/pull/1064

**Comment by johnfactotum** [comment]
The fix works great! But I'm encountering two problems:
- When leaving `height` undefined in the `renderTo` options, with horizontal text it will automatically set the height to 100%, but with vertical text, instead of setting the height at 100% it seems to set it to the height of the entire section.
- In Firefox and Chromium, if the height is big enough, it will show two vertical columns, but in WebKit, it only ever shows one column.
