### ISSUE TITLE
Save highlights/annotations to localStorage

### ISSUE THREAD

**Issue by strattonpress** [futurepress/epub.js#970]
Based on the Highlights example, we can get the location of the selected text by using
`book.getRange(cfiHere).then(function (range) {
  console.log(range);
})`

And also, using the code in the Highlights example, it creates an svg element in highlighting the text. Now, how do I save this in the localStorage so when I reload the page, the text will still be highlighted?

**Comment by johnfactotum** [comment]
You can save the CFI string in localStorage. And then when loading the page, read the saved CFI string from localStorage, and do `rendition.annotations.highlight(cfiHere)`.

**Comment by strattonpress** [comment]
Thanks, @johnfactotum ! It worked!
