### ISSUE TITLE
Load unpacked epub from Firebase Storage

### ISSUE THREAD

**Issue by strattonpress** [futurepress/epub.js#973]
Can epubjs load files from Firebase Storage? I tried this:

```javascript
var storage = firebase.storage();
var fileFromFirebase = storage.ref().child("books").child("Rain").child("content.opf");

fileFromFirebase.getDownloadURL().then(function(url) {
    var epubjs = ePub(url);
    var rendition = epubjs.renderTo("viewer", {});
    rendition.display();
});
```

but nothing is loaded.

**Comment by geek1011** [comment]
That doesn't work because the book is unpacked, and I don't think the relative URLs will resolve properly with Firebase. One option would be to load packed `.epub`s.

**Comment by strattonpress** [comment]
@geek1011 Thanks for the reply. How about AWS storage? Will it work with the unpacked ?
