### ISSUE TITLE
Prevent Copy and Cut text

### ISSUE THREAD

**Issue by ezequiel9** [futurepress/epub.js#978]
I am trying to find a way to prevent to copy and cut text in the book. I have tried something several ways like this and does not work. I am wondering is there some event to catch on rendition or book object?
```

$("html").on("contextmenu",function(e){
    return false;
});
// Disable cut, copy and paste on web page
$('html').bind('cut copy paste', function (e) {
     e.preventDefault();
});


```

**Comment by ezequiel9** [comment]
Oh I have solved that by doing this:

```
        /**
         * Prevent Selection
         */
        rendition.themes.default({
            'body': {
                '-webkit-touch-callout': 'none', /* iOS Safari */
                '-webkit-user-select': 'none', /* Safari */
                '-khtml-user-select': 'none', /* Konqueror HTML */
                '-moz-user-select': 'none', /* Firefox */
                '-ms-user-select': 'none', /* Internet Explorer/Edge */
                'user-select': 'none'
            }
        });
```

**Comment by hesampour** [comment]
Is there a way to prevent  Copy and Cut but enable selection? 
I want to enable have highlight. by disabling the user selection the highlight menu also disables.

**Comment by rahmatputrawiranata** [comment]
is there a way to prevent user from right click .

i now if this think is just a useless but my client need it ,

**Comment by nikhilbhalwankar** [comment]
> Oh I have solved that by doing this:
> 
> ```
>         /**
>          * Prevent Selection
>          */
>         rendition.themes.default({
>             'body': {
>                 '-webkit-touch-callout': 'none', /* iOS Safari */
>                 '-webkit-user-select': 'none', /* Safari */
>                 '-khtml-user-select': 'none', /* Konqueror HTML */
>                 '-moz-user-select': 'none', /* Firefox */
>                 '-ms-user-select': 'none', /* Internet Explorer/Edge */
>                 'user-select': 'none'
>             }
>         });
> ```

Can you please let me know where to add this code? I tried to add this at the bottom of epub.js file but still it allows copy and paste.
