### ISSUE TITLE
What are the options for using epub.js as a standalone solution, i.e. no node.js ?

### ISSUE THREAD

**Issue by carbontracking** [futurepress/epub.js#98]
Hello,

From the Readme it sems as though node.js is required in order to read epub files locally. I'm looking for a library like epub.js which will allow me to create a manner for distributing epub books to be read in a browser i.e. client-side only. The aim is no installation apart from unzipping a file to create a directory structure with an index.html at the root.
Can epub.js do this or is a server component always necessary ?
Best regards,
Colm

**Comment by hihemant84** [comment]
Hi, can anyone please help me to find out how its working in Chrome without using any server like node.js.... actually I am developing a Chrome packaged app and want to use the local file system to read the ePub file using ePub.js and zip.js..... thanks in advance for any help.

**Comment by GavinBrelstaff** [comment]
> find out how its working in Chrome without using any server
Chrome can still access files if you start it using the commandline option:
"-–allow-file-access-from-files".
On windows this means changing the shortcut target to:
`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "-–allow-file-access-from-files"
`

**Comment by hihemant84** [comment]
Hi GavinBrelstaff, thanks a lot for your reply.... just to be more specific - I am developing a Chrome packaged app and want to use the local file system to read the ePub file using ePub.js and zip.js.

Till now I have explored that ePub.js is not designed to use a local file for a offline chrome packaged app... I may be wrong though... so if you have any link or any kind of resource which can help me out in this, could you please share it. Thanks

**Comment by GavinBrelstaff** [comment]
zip.js. worked offline when I adopted it for my own use last year to read (but not write) from disk some ODT files made in libreoffice writer.

**Comment by hihemant84** [comment]
Thanks GavinBrelstaff for the help.. I will try to do like you have suggested. I will see if I can use the output(the way you have suggested above) to ePub.js to read the epub files locally(offline).
