### ISSUE TITLE
Estimated read time

### ISSUE THREAD

**Issue by igorcardozo** [futurepress/epub.js#996]
Hi,

I'm trying to get the estimated read time from an epub (like Medium)

![image](https://user-images.githubusercontent.com/23110384/68049804-8b27b100-fcc2-11e9-9035-730bd488462e.png)

Is there a way to do that ?
Or at least to get the number of words ?

Many thanks !

**Comment by johnfactotum** [comment]
What I've done is simply using [`book.locations.generate()`](https://github.com/futurepress/epub.js/blob/master/documentation/md/API.md#generate) to get the total number of characters in a book. The time is calculated as

```js
// the percentage of the book left
// `1` will calculate the estimated time for the whole book
percentage 

* book.locations.total

// the `chars` argument passed to `locations.generate`
* CHARACTERS_PER_PAGE

// roughly 6 for English; I've used 2.5 for CJK languages
/ CHARACTERS_PER_WORD

// roughly 200
/ WORDS_PER_MINUTE
```

It's a very rough estimate, but from my testing the results are similar to those given by Medium and other platforms.

**Comment by igorcardozo** [comment]
Thank you @johnfactotum for the answer !

I ended up with this approach:
`
    rendition.hooks.content.register((content, view) => {
      const contentWithoutSpaces = content.documentElement.textContent.replace(/^\s*\n/gm, '');
      console.log('content: ', contentWithoutSpaces.split(' '));
    });
`

However, I'll try yours and let you know if something comes up.

Thanks again for the answer !

**Comment by igorcardozo** [comment]
Doesn't work on continuous scrolled render:

```
    const node = viewerRef.current;
    rendition = book.renderTo(node, {
      manager: 'continuous',
      flow: 'scrolled',
      width: '100vw',
      height: '100vh',
    });
```

**Comment by johnfactotum** [comment]
I could be wrong, but I think both scrolled-doc and continuous scrolled only work properly when you render to `document.body`.

**Comment by igorcardozo** [comment]
`book.locations.total` returns always 0.

I decided to go with this approach:
`rendition.hooks.content.register((content, view) => {
  const contentWithoutSpaces = content.documentElement.textContent.replace(/^\s*\n/gm, '');
  const words = contentWithoutSpaces.split(' ');
  const totalWords = words.length;
  const readTime = Math.round(totalWords / WORDS_PER_MINUTE);
});`

Thank you @johnfactotum for your answers ! I really appreciate it.

**Comment by johnfactotum** [comment]
You need to call `book.locations.generate()` and wait for it to finish before you can use `book.locations.total` and other related functions.

**Comment by fchasen** [comment]
This would be a great method to add!
